### ISSUE TITLE
Adding google auth functionality

### ISSUE THREAD

**Issue by Prashant-2505** [MonalikaPatnaik/UMatter#1]
Sigin functionality is not working 
this error can fix by adding google auth functionality and  email authorization 

assign this issue to me(Gssoc' 23 contributor)

**Comment by PayalPadmalyaPrusty** [comment]
@Prashant-2505 I want to contribute.Please assign me

**Comment by MonalikaPatnaik** [comment]
Thanks @Prashant-2505 for raising the issue..you can work on this!

**Comment by Prashant-2505** [comment]
Thanks for assigning . I start working on it from today

**Comment by Prashant-2505** [comment]
> Thanks @Prashant-2505 for raising the issue..you can work on this!

i done chnaging and i also genrate pull request can u please check it out or merge if you find i do good work or resolve the issue

**Comment by Prashant-2505** [comment]
> 

In last pull request there is some issue was occured during commit so i again genrate pull request so please check it out and if you find i do good work or resolve the issue  then merge otherwise its not then give me some suggestion to improve it
