### ISSUE TITLE
Working on responsiveness of page 

### ISSUE THREAD

**Issue by Vishal-Parasram** [MonalikaPatnaik/UMatter#10]
Hey I noticed that some part of page is not responsive so I want to work on this issue and want to fix this issue so assign me under GSSoC-23 Thanks. ![Screenshot_2023_0520_020303.jpg](https://github.com/MonalikaPatnaik/UMatter/assets/93524129/4af565d3-1f03-4f16-b192-b08127de8faa)

**Comment by MonalikaPatnaik** [comment]
Sure @Vishal-Parasram..Go ahead!

**Comment by Vishal-Parasram** [comment]
@MonalikaPatnaik Thanks for assigning me. I'm working on this issue.

**Comment by MonalikaPatnaik** [comment]
Hey are you done with your changes?It's been long otherwise will assign to someone else!

**Comment by Vishal-Parasram** [comment]
@MonalikaPatnaik Sorry but I can't work on this issue you can assign anyone.

**Comment by i-am-SnehaChauhan** [comment]
@Vishal-Parasram it's ok you can look other issues and resolve them Thanks :)

**Comment by Kalyan-velu** [comment]
@i-am-SnehaChauhan Can you assign me this?

If there are any additional details or requirements for this issue, please let me know.

**Comment by i-am-SnehaChauhan** [comment]
Hey, @Kalyan-velu now it's only for responsiveness do it ASAP.
Thanks:)

**Comment by Kalyan-velu** [comment]
Hey @i-am-SnehaChauhan / @MonalikaPatnaik / @Mansi168 ,

I have been assigned the issue related to the ResponsiveUI of the website. While working on this issue, I found that the Footer component is causing the UI to be unresponsive on smaller screens. I believe fixing the Footer component will resolve the issue.

Before proceeding with the changes to the Footer component, I wanted to ask for permission from the project admins. Could you please let me know if anyone is currently working on the Footer section or if it's okay for me to make the necessary modifications?

I want to ensure that my changes align with the project's development plans and avoid any conflicts with ongoing work.

Looking forward to your guidance.

Thank you!
