### ISSUE TITLE
No module downloading section

### ISSUE THREAD

**Issue by eshita-18** [MonalikaPatnaik/UMatter#100]

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by eshita-18** [comment]
I will download some dummy download materials like brochers and all the downladed  section of the website that is'nt working 
then i  will edit .js in admisson section to display successfully admission done message  ,sucess stories of the college,i will create the project of recreationand student life

**Comment by MonalikaPatnaik** [comment]
I didn't understand the context behind this..Could you tell me where would u incorporate this?

> I will download some dummy download materials like brochers and all for downladed section of the website that is'nt working then i will edit .js in admisson section to display successfully admission done message ,sucess stories of the college,i will create the page of recreationand student life

**Comment by MonalikaPatnaik** [comment]
Okay..make a PR then..will merge it if looks good!
