### ISSUE TITLE
BUG: Footer texts on hover shows wrong color

### ISSUE THREAD

**Issue by YaShRaJ0P** [MonalikaPatnaik/UMatter#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On hovering texts in footer, it should show green color but it shows blue color when we hover on underline of text.

### Add ScreenShots

<img width="950" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/121381832/24be29cc-22da-4efd-a112-e8a48a46a247">

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Safari, Arc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Neha626177** [comment]
I would like to work on this issue. Please assign me this .
Thank You!
