### ISSUE TITLE
Responsive 

### ISSUE THREAD

**Issue by AmanSingh6574** [MonalikaPatnaik/UMatter#101]
Issue
1. Overlaping of sections in mobile responsive mode.

![image](https://github.com/MonalikaPatnaik/UMatter/assets/113782984/9bdac34d-f7f0-429d-a717-3ef3d94453d0)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/113782984/2897d12c-9d94-4e1f-a5af-3d20f1f79ca2)

I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23. @MonalikaPatnaik

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by MonalikaPatnaik** [comment]
I think it's already being done..
Thanks!
