### ISSUE TITLE
DOC: Update README.md (snapshots and sections)

### ISSUE THREAD

**Issue by nashira26** [MonalikaPatnaik/UMatter#1016]
### What's wrong with the existing documentation

The current README file has the website snapshots that are outdated. And also it does not have information about sections such as testimonials and feedback.

Please assign this to me under GSSoC'23

### Add ScreenShots

**The snapshot of about page in the README.md file**

![Screenshot 2023-07-09 162625](https://github.com/MonalikaPatnaik/UMatter/assets/32673772/b4063fdb-cc7f-41c0-812d-305bcf74337a)

**Snapshot of the about page as per last updated website UI.**

![Screenshot 2023-07-09 162657](https://github.com/MonalikaPatnaik/UMatter/assets/32673772/4568bb69-796d-46f9-b971-2eba01ce0e79)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by abuharish02** [comment]
Assign to me. I will fix it.
