### ISSUE TITLE
BUG:The contact page is not changing on switching to dark mode

### ISSUE THREAD

**Issue by karthiknadar1204** [MonalikaPatnaik/UMatter#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

MAke the background black to make it react on dark mode

### Add ScreenShots

<img width="1790" alt="Screenshot 2023-07-09 at 9 57 13 PM" src="https://github.com/MonalikaPatnaik/UMatter/assets/95973644/f92a3b49-2596-41fd-aa08-eff16d678b1d">

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by karthiknadar1204** [comment]
I would like to work on this issue inder gssoc'23

**Comment by MonalikaPatnaik** [comment]
The contact page is been completely redesigned.
