### ISSUE TITLE
Feat:Adding scroll to top button

### ISSUE THREAD

**Issue by ManishaSwain8** [MonalikaPatnaik/UMatter#1025]
### Describe the feature

As user goes down in every page ..they have to again scroll all the way up..so which affects the user experience.
So adding a scroll to top in every page will be a good idea.
If this feature req. do assign : |)
Changes will be done in no time
### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by karthiknadar1204** [comment]
@ManishaSwain8 The button already exists in the project, check the bottom left corner of the page once

**Comment by ManishaSwain8** [comment]
oh yes  : \ 
Sorry for inconvenience I missed it some how I should have checked properly !
