### ISSUE TITLE
Margin is not set between social icons

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#103]
Margin is not set between social icons, Space between  icons  is too much in icons
![umtr icond](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/505542ae-e8b0-43b7-9ca5-a16ef26ab65d)
![umtr icon](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/2a8b536f-b136-49b1-9011-12e756a185f4)

**Comment by avnigoyal25** [comment]
i want to work on this issue

**Comment by MonalikaPatnaik** [comment]
Hey @HimanshuNarware you can work on this!
Thanks for contributing!
