### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by kasturimandlik** [MonalikaPatnaik/UMatter#104]
I want to create a fully functional sign up page for the website.

The sign up page will have all the necessary details which should be collected from the user like email address, name, password, mobile number, username, etc.

I would like to work on this issue under GSSOC'23. Please assign me this isse

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by i-am-SnehaChauhan** [comment]
This issue is already raised before #91.

**Comment by shivam-sharma7** [comment]
@kasturimandlik close this
