### ISSUE TITLE
BUG: Logo not redirecting to home page

### ISSUE THREAD

**Issue by anamika7153** [MonalikaPatnaik/UMatter#1041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- Whenever Logo is clicked, it's not redirecting to the home page

### Add ScreenShots

https://github.com/MonalikaPatnaik/UMatter/assets/66116440/bbe39ea6-e08f-48e4-a7c7-5a8afbad32b8

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by debdutta04** [comment]
please assign this to me

**Comment by abhisar-yadav** [comment]
@anamika7153 
PLEASE ASSIGN ME THIS ISSUE
