### ISSUE TITLE
Feat: Search results

### ISSUE THREAD

**Issue by VijayalakshmiGanesh** [MonalikaPatnaik/UMatter#1044]
### Describe the feature

Display a message to user "No results found" when the search result is null for better user experience

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/104077094/b30c0856-6718-4cb4-be52-8d5195606e06)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MrTbag** [comment]
I opened a PR related to this issue and added the desired result. It passed the tests. The issue should be handled now.

**Comment by VijayalakshmiGanesh** [comment]
> I opened a PR related to this issue and added the desired result. It passed the tests. The issue should be handled now.

But bro, I wanted to work on this issue
