### ISSUE TITLE
Placeholder is  missing in the Sign in form

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#105]
In the sign-in form the placeholder for email is missing, I want to work on this issue. kindly assign me this issue
![placeholder](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/333471b8-0745-43df-af4d-7530f81ea2ef)

**Comment by Soyeb01** [comment]
I would like to work in this issue under GSSOC'23. Please assign me this issue.
