### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by yuvraj6446** [MonalikaPatnaik/UMatter#1052]
### Describe the feature

Hey, I want to add some gradient in navbar background and to make it sticky, It will give a good look to Home.we can also change Text colour.

### Add ScreenShots

We can add background to navbar and can change text color to make it attractive and can make navbar sticky to make home look better

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Codename-shaShank** [comment]
Hello I want to change the background which doesn't respond on switching to light mode
