### ISSUE TITLE
Fixing the footer

### ISSUE THREAD

**Issue by AmanSingh6574** [MonalikaPatnaik/UMatter#106]
Issue 
1. Buttons are not working 
2. Fixing the UI of footer

![image](https://github.com/MonalikaPatnaik/UMatter/assets/113782984/5061c3d5-5382-4340-bafb-179480863183)

3. On clicking the button the page is not responding
![image](https://github.com/MonalikaPatnaik/UMatter/assets/113782984/7133c6e1-7359-44df-a680-9a84509f73e3)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/113782984/cb8e979d-2491-4d53-923f-aca51d650940)

I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23. @i-am-SnehaChauhan

**Comment by Tathagt** [comment]
I would like to work on this issue under GSSOC'23.
Please assign me this issue

**Comment by KashiwalHarsh** [comment]
I want to contribute to this issue under GSSOC'23 can you please assign it to me

**Comment by MonalikaPatnaik** [comment]
Hey button in footer is already fixed.. do u want to change the ui for footer?What improvements you are planning to do? Could you elaborate your approach..

**Comment by AmanSingh6574** [comment]
Yes, I want to work on the footer UI 
Issue - 
1. If u see the contents are not properly aligned 
2. the position of the icons is not proper 
3.  On hovering any icon the color is the same I will change it according to the application logo color
4. The icons link are not working

here is the eg of one of my projects 

![image](https://github.com/MonalikaPatnaik/UMatter/assets/113782984/8a116286-9832-4a69-b48d-c98f11beeff7)

I can make it look like it, if u like this design
Please assign this issue to me as a part of GSSOC'23 @MonalikaPatnaik

**Comment by KashiwalHarsh** [comment]
Hey, I want to work on the footer of UMatter -

As you can see right now the footer is not that attractive for light mode 
The UI does not look good and
The Icons do not have a good color scheme and are not working

I can make it look more professional and even different for dark and light theme
here is an example of a light theme

<img width="814" alt="Screenshot 2023-05-22 150620" src="https://github.com/MonalikaPatnaik/UMatter/assets/77677724/a5e2177b-786d-4324-be17-deaa6dbf42e1">

You can assign this issue to me if you like the design and theme of the footer under GSSOC'23
