### ISSUE TITLE
BUG: Signup button is not working

### ISSUE THREAD

**Issue by ayushrathore111** [MonalikaPatnaik/UMatter#1062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sign up button is not working and not accepting the information.

### Add ScreenShots

![Screenshot (272)](https://github.com/MonalikaPatnaik/UMatter/assets/94514710/fa63614c-606f-4642-bb8c-e27915b8493f)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Neha626177** [comment]
I want to solve this issue please assign me .
Thank you!

**Comment by akankshabach** [comment]
I would like to work on this task. Please assign it to me
Thank you!

**Comment by ayushrathore111** [comment]
alright !! I'm gonna start working on it..
