### ISSUE TITLE
Feat: Improving the UI of Doctors/Therapist Profiles section.

### ISSUE THREAD

**Issue by abhiy2k** [MonalikaPatnaik/UMatter#1065]
### Describe the feature

Currently when we visit the Doctors/Therapist Profiles section the two buttons view profile and schedule Appointment appear at the bottom of the photos of the doctors card instead I want to add the feature that instead of appearing in the bottom they appear on the photos of the doctors whenever the user hover on them, this provides a more dynamic and realistic feel and overall good user experience.
So Initially there will be no profile and schedule appointment button but as soon as the user hovers on the pic of the doctor, the photo will zoom a little providing a dynamic motion and profile and schedule Appointment button will Popup.

### Add ScreenShots

![Screenshot 2023-07-16 232923](https://github.com/MonalikaPatnaik/UMatter/assets/86073995/6a2a9c31-12b1-4b57-b1eb-1f5f619477a5)
![Screenshot 2023-07-16 231631](https://github.com/MonalikaPatnaik/UMatter/assets/86073995/a167fdee-6c4f-4fd5-9fb2-fdb2ec0200ce)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by abhiy2k** [comment]
@MonalikaPatnaik can you please review this asap.

**Comment by TechSpiritSS** [comment]
The concept looks good but you need to improve color scheme of button if you are planning them on the image

**Comment by abhiy2k** [comment]
What color Scheme do you Suggest ? maybe we can make the button more transparent and the buttons will not be permanently present on the image they will only appear when the user will hover on the image.
