### ISSUE TITLE
Feat: Redesigning the Home Page

### ISSUE THREAD

**Issue by MonalikaPatnaik** [MonalikaPatnaik/UMatter#1074]
### Describe the feature

Redesign the whole home page to the one shown below which matches the taste of the website( can use different images and color theme) 
Image like--
![Screenshot 2023-07-02 202837](https://github.com/MonalikaPatnaik/UMatter/assets/99353300/352d78c8-aa60-4860-894e-bd5ca6951fa6)

![Screenshot 2023-07-02 202434](https://github.com/MonalikaPatnaik/UMatter/assets/99353300/7fabb830-1871-469d-a68a-c4c1a5e11762)

**Time limit: 1 week**

### Add ScreenShots

![Screenshot 2023-07-02 203215](https://github.com/MonalikaPatnaik/UMatter/assets/99353300/3e1f02b0-c5c4-43e3-a090-b7ff23bc20a9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'23 contributor
- [ ] I want to work on this issue

**Comment by Malavi1** [comment]
I would like to work on this issue under Gssoc-2023.
could you please assign me

**Comment by Malavi1** [comment]
Hey, @MonalikaPatnaik should I need to send the images without applying them in the actual background home page or do I have to send the SS after applying them in the actual background?

**Comment by Malavi1** [comment]
@MonalikaPatnaik  WDT?
![Screenshot 2023-07-24 124953](https://github.com/MonalikaPatnaik/UMatter/assets/112646623/7381ae1e-08b0-4ab7-bd9f-2aef51693c40)

**Comment by Malavi1** [comment]
This too looks great for me WDT?

![Screenshot 2023-07-24 132614](https://github.com/MonalikaPatnaik/UMatter/assets/112646623/f6d6230d-39b6-40d1-9e9d-60202772a23f)
