### ISSUE TITLE
User dashboard UI

### ISSUE THREAD

**Issue by aishwarya1735** [MonalikaPatnaik/UMatter#109]
I will add a user account dashboard for them to manage their medications ,suggestions and many more. Kindly assign this to me.

**Comment by MonalikaPatnaik** [comment]
May i know where would you add this?

**Comment by aishwarya1735** [comment]
So I would add the symbol beside the logo for user to access their dashboard. When they click there, then they can be directed into another web page where they have their personal account details with few suggested articles or information to refer and then have their data of what they need.

**Comment by MonalikaPatnaik** [comment]
Sounds Good..You are assigned..go ahead..
Thanks for contributing!

**Comment by aishwarya1735** [comment]
Thank you monalika !!

**Comment by MonalikaPatnaik** [comment]
Hey @aishwarya1735..I recommend you to submit your PR soon so that we can merge it without conflicts!

**Comment by aishwarya1735** [comment]
Yess.. I've been caught up with my end sem exams so it's going a bit tough.. Will need some time to submit. I'll try to submit soon. 
Thank you for conveying this.
