### ISSUE TITLE
BUG: in github icon

### ISSUE THREAD

**Issue by Sushilverma002** [MonalikaPatnaik/UMatter#1093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the behavior of github icon se different from others

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/114687502/732131a3-0904-459f-9a3a-7a72d017e635)

https://github.com/MonalikaPatnaik/UMatter/assets/114687502/2df0abba-7c58-4445-b0b7-1c6cab8ab7b6

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by abhisar-yadav** [comment]
@Sushilverma002 
Please assign me this issue.
