### ISSUE TITLE
BUG: Buttons in hamburger menu 

### ISSUE THREAD

**Issue by Mayank-Sharma17** [MonalikaPatnaik/UMatter#1095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

>Minor bug

The border of buttons in the hamburger menu touching each other, I think there should be some space between them.

### Add ScreenShots

![Screenshot 2023-07-30 101632](https://github.com/MonalikaPatnaik/UMatter/assets/113251342/9d9be424-08fc-4646-9433-1b50d970fdf1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [x] I want to work on this issue

**Comment by debdutta04** [comment]
please assign me this issue under Gsooc'23
