### ISSUE TITLE
Update website url in the README.md

### ISSUE THREAD

**Issue by Manice18** [MonalikaPatnaik/UMatter#11]
changed **Check the Website [here](https://https://monalikapatnaik.github.io/UMatter/)**.  the proper url **Check the Website [here](https://monalikapatnaik.github.io/UMatter/)**.
Now the url link seems to be working.
Can I create a PR for this issue.

**Comment by AmanMittal-3305** [comment]
hii
please assign me this issue

**Comment by MonalikaPatnaik** [comment]
Hii @Manice18, the link in readme is updated,,can you work more on the content and alignment in readme?

**Comment by Manice18** [comment]
> Hii @Manice18, the link in readme is updated,,can you work more on the content and alignment in readme?

Should I update the readme as a whole and make it look more clean?

**Comment by MonalikaPatnaik** [comment]
> Should I update the readme more as a whole and make it look more clean? Is that what you are asking me to do?

Yess @Manice18..you can start working on this..

**Comment by MonalikaPatnaik** [comment]
Heyy @Manice18 are you working on this?

**Comment by Manice18** [comment]
Yes, I am , i'll be done within tomorrow, actually I have my semester practical exams today, so I was a bit busy. But I'll complete it with today.  Just give me 1day @MonalikaPatnaik

**Comment by Manice18** [comment]
![2](https://github.com/MonalikaPatnaik/UMatter/assets/91601706/b00217df-7dc3-47de-b24c-d006682b2ea9)

**Comment by Manice18** [comment]
![3](https://github.com/MonalikaPatnaik/UMatter/assets/91601706/a0b37fc9-ba7d-4d68-b8e0-b73ac9edb1d1)

**Comment by Manice18** [comment]
![5](https://github.com/MonalikaPatnaik/UMatter/assets/91601706/f50841a0-969b-41ea-816e-ec619cf25259)

**Comment by Manice18** [comment]
![6](https://github.com/MonalikaPatnaik/UMatter/assets/91601706/1a0e004a-1826-4c05-87fd-2919352bbe33)

**Comment by Manice18** [comment]
@MonalikaPatnaik  I updated the screenshots with the current version of the website
corrected urls of the project maintainers and made them clicklabe so that on click user is taken to the github profile of the clicked maintainer's profile
fixed typos
added few points in key features
adjusted height and width of project maintainer's profile images and also tech stack icons

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik @Mansi168 I added the screenshots, can you please verify and tell me if i am allowed to push the changes?
Yeah, you are good to go!
Thanks!

**Comment by Manice18** [comment]
Made the pr @MonalikaPatnaik !

**Comment by Manice18** [comment]
I am closing this issue now as the merge is complete @Mansi168 @MonalikaPatnaik
