### ISSUE TITLE
DOC: I found at least 5 cases of improper spaces and font sized in readme

### ISSUE THREAD

**Issue by 1Shubham7** [MonalikaPatnaik/UMatter#1101]
### What's wrong with the existing documentation

The readme file looks very unprofessional and unreadable with the current improper spacing and font sizes. I have given some examples below.

### Add ScreenShots

![me3](https://github.com/MonalikaPatnaik/UMatter/assets/116020663/2548e42e-5ef1-415b-891d-428c0d0bf28f)
![me4](https://github.com/MonalikaPatnaik/UMatter/assets/116020663/6cbf79cc-d673-45e0-a8bc-2a903c8abfa2)
![me1](https://github.com/MonalikaPatnaik/UMatter/assets/116020663/12536ba7-6f30-4577-bfbc-f7e9109202aa)
![me2](https://github.com/MonalikaPatnaik/UMatter/assets/116020663/b6078d8c-acd3-4eaa-90e0-3d1484acf113)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by abhisar-yadav** [comment]
@1Shubham7 
PLEASE ASSIGN ME THIS ISSUE
