### ISSUE TITLE
BUG: Smooth trasition not applied on github icon

### ISSUE THREAD

**Issue by sumitkr2000** [MonalikaPatnaik/UMatter#1108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey, @MonalikaPatnaik The github icon present in the footer doesn't have a smooth transition like other social icons. Pleas assign me this issue. Thank you!

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/100675296/eaa36063-2e79-4d7f-9651-5428b72dcd0e)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by AnushkaKohli** [comment]
I have checked. The github button doesn't have smooth transition. Please assign me the issue so I can fix it.

**Comment by Neha626177** [comment]
Please assign me this issue.
