### ISSUE TITLE
fixing bug in the navbar items.

### ISSUE THREAD

**Issue by JatinBisht2308** [MonalikaPatnaik/UMatter#111]
The navbar items have a bug.
bug: after going to the services section while clicking on the home nav item it is not going to the starting of the page which is generally very obvious thinking of the user which degrades the UX of the website.
Please assign this issue to me under gssoc23 as I am a gssoc23 contributor.

**Comment by MonalikaPatnaik** [comment]
It's already being resolved
Thanks!

**Comment by JatinBisht2308** [comment]
Okeh mam
