### ISSUE TITLE
BUG: NavBar buttons showing cursor doesn't look good

### ISSUE THREAD

**Issue by StephCurry07** [MonalikaPatnaik/UMatter#1114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As the items in the navbar are buttons, it shouldn't show cursor upon clicking them. It gives a feel of text field.

### Add ScreenShots

![gssocumatter](https://github.com/MonalikaPatnaik/UMatter/assets/76783882/d5d85fd3-c712-4371-95fe-dcc5c59e64bb)

### What browser are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Neha626177** [comment]
Please assign me this issue . I would like to solve this issue.
