### ISSUE TITLE
BUG:in blog section make the search bar in the middle

### ISSUE THREAD

**Issue by priyanshibhatn** [MonalikaPatnaik/UMatter#1120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in the blog page the search bar has to be in centre

### Add ScreenShots

![Screenshot (6)](https://github.com/MonalikaPatnaik/UMatter/assets/126306915/34c2f3c4-1fc1-428f-b8ef-b385149ce0e3)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Neha626177** [comment]
I would like to resolve this issue please assign me this issue
