### ISSUE TITLE
BUG: Want to change the Twitter logo

### ISSUE THREAD

**Issue by PatilHarshh** [MonalikaPatnaik/UMatter#1127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

AS Twitter logo is changed and want to change the twitter logo 

### Add ScreenShots

.

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@MonalikaPatnaik

**Comment by NextThread** [comment]
can i work on this
