### ISSUE TITLE
[style]:  Add stylish Scrollbar

### ISSUE THREAD

**Issue by piyushkhurana2019** [MonalikaPatnaik/UMatter#1141]
### What's the style idea?

We need to improve:- The website UI is very beautiful, just there is one thing which can enhance its beauty to a great extent that is scroll bar.
I want to add a stylish scroll bar to the website so that it looks more eye catching to the users
either this:-

<img width="1440" alt="Screenshot 2023-08-10 at 7 14 54 PM" src="https://github.com/MonalikaPatnaik/UMatter/assets/96003210/1eb94fb0-b6c5-41dd-8a52-1f4d9dd2a2c2">
 or this
 
<img width="1440" alt="Screenshot 2023-08-10 at 7 15 17 PM" src="https://github.com/MonalikaPatnaik/UMatter/assets/96003210/f8571242-6687-49a7-81b9-0d401d68158a">

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/MonalikaPatnaik/UMatter/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/MonalikaPatnaik/UMatter/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by GriffinAnnshual** [comment]
Hey can you assign this issue to me! I would like to work on it.
