### ISSUE TITLE
BUG: Text not visible

### ISSUE THREAD

**Issue by ManashAnand** [MonalikaPatnaik/UMatter#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Get started button is not visible on hover

### Add ScreenShots

![Screenshot 2023-08-15 233415](https://github.com/MonalikaPatnaik/UMatter/assets/91553087/0f672d08-e19b-4e62-97ed-904f7ac26a06)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by rj2704** [comment]
Hi @MonalikaPatnaik, You can assign this to me. I can fix this issue.

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik @Mansi168 @i-am-SnehaChauhan Are you still accepting pr's and issues on the project?

**Comment by ManashAnand** [comment]
@MonalikaPatnaik 
I have raised the issue 
So can you please check and assign this issue to me
So that I can start working on it
