### ISSUE TITLE
BUG:Get started button in the info section page is invisible on hovering

### ISSUE THREAD

**Issue by gitssz** [MonalikaPatnaik/UMatter#1144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the "get started" button of the info section (below the home page) is hovered the "get started" text is invisible because the text color is already white and a white background is applied on hovering. This happens in both the modes(light n dark).

### Add ScreenShots

![Screenshot from 2023-10-05 16-35-40](https://github.com/MonalikaPatnaik/UMatter/assets/83583240/edf8a405-72f9-44de-903b-eb15a4094a80)

### What browser are you seeing the problem on?

Firefox, Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by 4genie** [comment]
I would like to work on it. Please assign this to me
