### ISSUE TITLE
Add sign up page

### ISSUE THREAD

**Issue by sagnik3788** [MonalikaPatnaik/UMatter#12]
I can work on the  frontend part of the sign up page .please assign me @MonalikaPatnaik .

**Comment by AmanMittal-3305** [comment]
hii
please assign me this issue

**Comment by MonalikaPatnaik** [comment]
Sure @sagnik3788..you can work on this.. Thanks!

**Comment by sagnik3788** [comment]
ok

**Comment by MonalikaPatnaik** [comment]
Hey..are you done with your changes? I recommend to submit your PR soon!

**Comment by sagnik3788** [comment]
I just complete the UI part only  should i make the pr?

**Comment by krittika2004** [comment]
I want to help with this issue under gssoc 23 @MonalikaPatnaik @Mansi168

**Comment by MonalikaPatnaik** [comment]
> I just complete the UI part only should i make the pr?

Yes..make a pr..will review it!

**Comment by MonalikaPatnaik** [comment]
Hey @sagnik3788..the sign up is done! as You have raised this issue first.. I want you to contribute to this..Could you add some CSS and fix some alignment in the current Signup Page? 
Also, pls submit your PR asap once done!

**Comment by MonalikaPatnaik** [comment]
> Hey @sagnik3788..the sign up is done! as You have raised this issue first.. I want you to contribute to this..Could you add some CSS and fix some alignment in the current Signup Page? Are u willing to work on this! just lmk if u cann't.. Also, pls submit your PR asap once done!

@sagnik3788 are u working??

**Comment by sagnik3788** [comment]
Please assign this issue to other contributer @MonalikaPatnaik
