### ISSUE TITLE
add testimonial page

### ISSUE THREAD

**Issue by S-ishita** [MonalikaPatnaik/UMatter#120]
I want to add testimonial page.Features:
 

- similar UI
- testimonial content 

Please assign this issue to me under GSSOC

**Comment by S-ishita** [comment]
can i make it using html css only ? @MonalikaPatnaik

**Comment by Mansi168** [comment]
hey @S-ishita this is a react project..you have to make page in react only and route it to app.js! 
let me know if u face any issue!

**Comment by S-ishita** [comment]
Ya.. actually I had some deadlines to meet so you can assign this to someone else.I shall raise new issues later :)
