### ISSUE TITLE
Navbar can be improve 

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [MonalikaPatnaik/UMatter#122]
Current navbar has simple design and we can change it by changing it position and the button can be added instead of link. 

Please assign me this issue to solve the problem and to fix it as a GSSoC '23 Contributor.

**Comment by i-am-SnehaChauhan** [comment]
Hiii, @Rupantar-Borphukan 
This issue is similar to #86 
Please msg here Thanks :)
