### ISSUE TITLE
Adding an error 404 page

### ISSUE THREAD

**Issue by him-raw99** [MonalikaPatnaik/UMatter#124]
# Adding an custom error-404 page

when someone visits a random page on UMatter they are redirected to a default error 404 page.

like this : 

![image](https://github.com/MonalikaPatnaik/UMatter/assets/97152850/857398ab-077b-4897-9db2-f6e7d0d6ad8b)

>I would like to contribute as a GSSOC contributor by adding a custom error 404 page with better ui for a user to navigate out of there or to find the page that they were looking for. 

kindly assign me this issue

**Comment by Mansi168** [comment]
@him-raw99 u r assigned....go ahead :)

**Comment by him-raw99** [comment]
hi, you just merged my PR I think you should close this issue now 

![image](https://github.com/MonalikaPatnaik/UMatter/assets/97152850/02a48a18-ffbd-4aa6-99ba-16762f498257)

thanks for the opportunity @Mansi168

**Comment by Mansi168** [comment]
it is closed :)
good luck !
