### ISSUE TITLE
Background Image 

### ISSUE THREAD

**Issue by Heena31** [MonalikaPatnaik/UMatter#126]
First of all, when someone opens a website, the home page and background image are the first things they see. It must be intriguing and visually pleasing. I can build the ideal layout. Kindly assign me this issue so that it looks more attractive

**Comment by anoopgangwar4** [comment]
I would like to work on this issue ,I have some creative ideas about this. please assign me.

**Comment by MonalikaPatnaik** [comment]
Okay..so you want to change the bg img right..
Could you attach a ss of new image which you are going to replace?

**Comment by Abhiramjampani** [comment]
![p](https://github.com/MonalikaPatnaik/UMatter/assets/126624416/dd881f3e-3f4b-4126-a80b-f8a3aa53fb3f)
@MonalikaPatnaik 
i an add this image to background for blogs page

**Comment by Abhiramjampani** [comment]
can you assign it to me? @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
> First of all, when someone opens a website, the home page and background image are the first things they see. It must be intriguing and visually pleasing. I can build the ideal layout. Kindly assign me this issue so that it looks more attractive

Heyy are u working on this??

**Comment by Abhiramjampani** [comment]
> > ![p](https://user-images.githubusercontent.com/126624416/240040027-dd881f3e-3f4b-4126-a80b-f8a3aa53fb3f.jpg) @MonalikaPatnaik i an add this image to background for blogs page
> 
> Check my comment on #269

ya okay consider my comment

**Comment by Heena31** [comment]
@MonalikaPatnaik  I was busy with different project so i will give you all information by the end of the day
