### ISSUE TITLE
Correcting Readme

### ISSUE THREAD

**Issue by gmmkmtgk** [MonalikaPatnaik/UMatter#13]
the click here link is having https two times 

https://https//monalikapatnaik.github.io/UMatter/

**Comment by gmmkmtgk** [comment]
@MonalikaPatnaik Please provide me edit access to make a new branch and then raise a pr

C:\Users\gmmke\Desktop\Gssoc\UMatter>git add . && git commit -m "Correct website link"             
[Correcting-Readme 70c1b53] Correct website link
 1 file changed, 1 insertion(+), 1 deletion(-)

C:\Users\gmmke\Desktop\Gssoc\UMatter>git push
fatal: The current branch Correcting-Readme has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin Correcting-Readme

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.


C:\Users\gmmke\Desktop\Gssoc\UMatter> git push --set-upstream origin Correcting-Readme
remote: Permission to MonalikaPatnaik/UMatter.git denied to gmmkmtgk.
fatal: unable to access 'https://github.com/MonalikaPatnaik/UMatter.git/': The requested URL returned error: 403

C:\Users\gmmke\Desktop\Gssoc\UMatter>git push
fatal: The current branch Correcting-Readme has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin Correcting-Readme

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.


C:\Users\gmmke\Desktop\Gssoc\UMatter>git push --set-upstream origin Correcting-Readme
remote: Permission to MonalikaPatnaik/UMatter.git denied to gmmkmtgk.
fatal: unable to access 'https://github.com/MonalikaPatnaik/UMatter.git/': The requested URL returned error: 403

**Comment by MonalikaPatnaik** [comment]
Hey Thanks @gmmkmtgk, the issue of link in the readme has been solved..
Also, you cannot directly edit the readme ..for that you have to create the branch in your fork and push the changes in you fork only!
Let me know of any issue!
