### ISSUE TITLE
Adding a Sign up form page interface 

### ISSUE THREAD

**Issue by yugank01** [MonalikaPatnaik/UMatter#131]
I noticed that the current website didn't had a sign up page. So I would like to add a Sign up page using HTML & CSS. So please assign me the issue.

**Comment by Adi-21** [comment]
I just love to solve this issue as I had done these things during my internship period and now I want to contribute to solve this issue under GSSoC'23

**Comment by Adi-21** [comment]
can You please assign it to me

**Comment by iluckyvirani** [comment]
Kindly assign this issue to me under the 
GSSOC'23 tag

**Comment by MonalikaPatnaik** [comment]
Hey sign upp page is already been assigned: #12 
Thanks!

**Comment by yugank01** [comment]
Okay
