### ISSUE TITLE
Footer is not neat, padding is required 

### ISSUE THREAD

**Issue by parthksingh1** [MonalikaPatnaik/UMatter#132]
I will Make a Better Footer wit good padding and will align them neatly which will Enhance User Experience ,please assign me this issue under @GSSOC'23 to make it better.

**Comment by anoopgangwar4** [comment]
I would like to work on this issue ,I have some creative ideas about this. please assign me.

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
