### ISSUE TITLE
[Signup Page] Bad design and usability

### ISSUE THREAD

**Issue by sabhisharma-ise** [MonalikaPatnaik/UMatter#135]
The current login page for our cloud storage website is poorly designed and difficult to use. The colors are jarring, the layout is cluttered, and the text is difficult to read. 

Changes that could be made to the signup page:
- Use a more modern and stylish design.
- Use a simpler layout with less clutter.
- Use larger fonts and easier-to-read text.
- Make the login process faster and more responsive.

By making these changes to the signup page, we can make it more user-friendly and inviting.

![image](https://github.com/MonalikaPatnaik/UMatter/assets/100849696/8abab65a-e555-4889-bd06-8ac95f7f0a40)
| *An Example for a better looking signup page is:* |

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by Abhiramjampani** [comment]
i can make sign -in page and sign-up page more attractive by using tailwindcss please assign me for this issue @MonalikaPatnaik @i-am-SnehaChauhan
