### ISSUE TITLE
Card Alligment Correction

### ISSUE THREAD

**Issue by gmmkmtgk** [MonalikaPatnaik/UMatter#14]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/51493190/4b41e498-ba34-4fbc-9c42-d83f722b2e5f)

**Comment by AmanMittal-3305** [comment]
hii
please assign me this issue

**Comment by gmmkmtgk** [comment]
@Mansi168 Could you please add the GSSOC label to all my issues otherwise it will not be considered for leaderboard
I saw someone writing that
![image](https://github.com/MonalikaPatnaik/UMatter/assets/51493190/239dd5fe-370f-4013-b94c-8e087088b269)

**Comment by gmmkmtgk** [comment]
@Mansi168 
Thanks 
I have solved the issue but now how do I link this pr to this issue https://github.com/MonalikaPatnaik/UMatter/pull/49
