### ISSUE TITLE
On Hover over a button cursor pointer is not set.

### ISSUE THREAD

**Issue by Ankush-Ladani** [MonalikaPatnaik/UMatter#140]
![BUG](https://github.com/MonalikaPatnaik/UMatter/assets/72239310/d1f90a6c-27a1-4933-8a04-e86b6490cab3)

And There are many places where this is not implemented. So I would like to contribute towards this.
I am in GSSOC 2023.

**Comment by MonalikaPatnaik** [comment]
Hey..it's already been done!
Closing the issue..
Thanks..
