### ISSUE TITLE
Improvement in the Sign in page

### ISSUE THREAD

**Issue by PoorvaU** [MonalikaPatnaik/UMatter#146]
The sign in box is not completely visible so it needs to be aligned properly .In the password section the icon needs to be placed correctly. Kindly assign me this issue under GSSOC'23
<img width="960" alt="issue" src="https://github.com/MonalikaPatnaik/UMatter/assets/114599293/c4b22d78-6d57-4761-9cc7-3086ee5cf998">

**Comment by AishwaryVishwa** [comment]
I think we can make sign in and sign up page in a single page with toggle effect just like the image given below but color theme will be same as green and black . I think it will look great. @MonalikaPatnaik please assign this issue to me I would like to work on it.

Gssoc'23 contributor
![image](https://github.com/MonalikaPatnaik/UMatter/assets/97339324/29ec6127-8620-4618-9892-b2895756028e)

**Comment by PoorvaU** [comment]
@Mansi168, mam  kindly go through this once and let me know if i can work on this.
