### ISSUE TITLE
Some content is not displaying perfectly in mobile view

### ISSUE THREAD

**Issue by Iamdivyak** [MonalikaPatnaik/UMatter#147]
<img width="169" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/102896170/69240542-1a7f-4c1b-a5f7-76590cd2c6cb">

I can work with this issue
please assign it to me under Gssoc contributor

**Comment by MonalikaPatnaik** [comment]
I think it's been resolved and someone is already working on the responsiveness.
