### ISSUE TITLE
Making a new chatbot for the page

### ISSUE THREAD

**Issue by dishal35** [MonalikaPatnaik/UMatter#148]
The chatbot could render more information about the website, downsides of drinking and smoking, it should also be able to provide the details of local therapists and helpline numbers in case of dire situations. It will be made to have a empathic and non-judgmental tone. It can also have a short quiz that the users can answer to know the severity of their addiction.

**Comment by MonalikaPatnaik** [comment]
Sounds Good..are u creating a separate page for chatbot or the pop-up like as it is now?

**Comment by dishal35** [comment]
I was thinking pop-up

**Comment by MonalikaPatnaik** [comment]
Okay..then remove the current chatbot and add yours with a good design and all...will merge it if it is looks good!
Thanks!

**Comment by MonalikaPatnaik** [comment]
Heyy @dishal35 are u done with your changes? take your time.. I recommend you to submit your PR soon so that we can merge it without conflicts!
Thanks!

**Comment by dishal35** [comment]
I am really sorry, I had some other work to look after, I will be submitting the PR soon

**Comment by MonalikaPatnaik** [comment]
Hey pls so it soon!

**Comment by dishal35** [comment]
Hi, I didn't realise how much backend chatbot would need. I tried working on it but its taking time. I would like some more time or would be happy to have a more qualified person work on the issue.
