### ISSUE TITLE
Proper DataBase Integration 

### ISSUE THREAD

**Issue by gmmkmtgk** [MonalikaPatnaik/UMatter#15]
No proper database is there

**Comment by MonalikaPatnaik** [comment]
Hey..how would you do that..Could you tell me the approach?
Thanks for contributing!

**Comment by gmmkmtgk** [comment]
@MonalikaPatnaik we need to connect for that
as the project is hosted we need to host the database also
And choose the right db for project

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik we need to connect for that as the project is hosted we need to host the database also And choose the right db for project

Okay, so backend will be added once frontend is done( i mean the sign up page)..then will assign it to you!
