### ISSUE TITLE
changing the styling of social media icons in footer section

### ISSUE THREAD

**Issue by anshikkay** [MonalikaPatnaik/UMatter#151]
![Screenshot (103)](https://github.com/MonalikaPatnaik/UMatter/assets/129502224/f1ac6b3d-dbf1-4e6f-b543-422f3e985df0)

**Comment by MonalikaPatnaik** [comment]
Hey..to which style are you going to change..could you provide a ss for ref

**Comment by anshikkay** [comment]
> Hey..to which style are you going to change..could you provide a ss for ref

![git](https://github.com/MonalikaPatnaik/UMatter/assets/129502224/594d2ee4-1eab-49d6-ad1c-dcb1ae6d7565)

**Comment by anshikkay** [comment]
i want to change the icons to like the icons of the screenshot i posted.
