### ISSUE TITLE
No signup page

### ISSUE THREAD

**Issue by TusharMinche** [MonalikaPatnaik/UMatter#154]
Description:
There is no signup page in the project. When I click on the "Sign Up" button in the navbar, nothing happens. I have checked the source code and there is no route for a signup page.

Steps to reproduce:
Go to the project website.
Click on the "Sign Up" button in the navbar.
Observe that nothing happens.

Expected behavior:
The signup page should be displayed when I click on the "Sign Up" button in the navbar.

Actual behavior:
Nothing happens when I click on the "Sign Up" button in the navbar.

Notes:
I have checked the source code and there is no route for a signup page.
I have tried refreshing the page and clearing my browser's cache.
I am using the latest version of the project's code.

Possible solutions:

Create a signup page and add a route for it to the project's code.
Fix the bug that is preventing the signup page from being displayed.

**Comment by TusharMinche** [comment]
I can reduce this problem so can you assign this to me?

**Comment by i-am-SnehaChauhan** [comment]
Hey, @TusharMinche This issue is similar to#12 
Please msg there Thanks :)

**Comment by TusharMinche** [comment]
Okey.... Thanks
