### ISSUE TITLE
modification in password text section

### ISSUE THREAD

**Issue by anshikkay** [MonalikaPatnaik/UMatter#155]
![Screenshot (104)](https://github.com/MonalikaPatnaik/UMatter/assets/129502224/c3557866-c705-4732-813c-0199922d4993)

**Comment by MonalikaPatnaik** [comment]
Could you elaborate more? What text you will change?

**Comment by anshikkay** [comment]
i want to replace the hidden icon from it's current position to right-middle

**Comment by anshikkay** [comment]
> Could you elaborate more? What text you will change?
i want to replace the hidden icon from it's current position to right-middle

**Comment by MonalikaPatnaik** [comment]
Hey, i think it's been resolved by #123
