### ISSUE TITLE
 changing hover effect on continue button of signup to make it more visible

### ISSUE THREAD

**Issue by anshikkay** [MonalikaPatnaik/UMatter#157]
![Screenshot (104)](https://github.com/MonalikaPatnaik/UMatter/assets/129502224/1b14a3ad-fa5c-4be2-911d-01bc7f20d4fa)

**Comment by nishitapande** [comment]
Please assign me this issue, thank you.

**Comment by MonalikaPatnaik** [comment]
Similar issue is already being assigned..will assign you if needed!

**Comment by nishitapande** [comment]
@MonalikaPatnaik ok no problem. please assign me any other issue related to the front-end. Thanks
