### ISSUE TITLE
making logo of UMatter attractive

### ISSUE THREAD

**Issue by anshikkay** [MonalikaPatnaik/UMatter#159]
![Screenshot (105)](https://github.com/MonalikaPatnaik/UMatter/assets/129502224/7a508e62-dc79-4ad4-bd02-e9339e562230)

**Comment by anshikkay** [comment]
i can make to style the logo of UMatter attractive as it is the main attraction of the website

**Comment by Mansi168** [comment]
okay @anshikkay you can work on logo!

**Comment by Dimple-01** [comment]
I am good in logo designing.
I want to work on this as I would create attractive logo for this.
Please assign this work to me.
