### ISSUE TITLE
give nav bar a whole new styling to make it attractive

### ISSUE THREAD

**Issue by anshikkay** [MonalikaPatnaik/UMatter#160]
![Screenshot (105)](https://github.com/MonalikaPatnaik/UMatter/assets/129502224/016d7fc6-dd2f-4d5a-b7fb-cf8b5fd90050)
As the UMatter website being a little ordinary in view of styling,i want to change nav bar styling,which help me in contributing to this project.

**Comment by MonalikaPatnaik** [comment]
It's been already assigned: #7
Thanks!
