### ISSUE TITLE
Readme updation

### ISSUE THREAD

**Issue by shraddha761** [MonalikaPatnaik/UMatter#162]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/106100728/12f741dd-c569-4ad8-85b5-58606c38dc1d)

adding this image in readme makes it more attractive please assign me this issue under GSSOC'23

**Comment by MonalikaPatnaik** [comment]
Hey..i appreciate but readme is already been assigned to someone!

**Comment by MonalikaPatnaik** [comment]
Heyy @shraddha761..I want you to add contributors in readme.md such that it keeps updated when someone contributes to the repo..as of now it's just an image! pls let me know if u can work on this!

**Comment by shraddha761** [comment]
@MonalikaPatnaik yahh assign me this issue I'll solve this

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik yahh assign me this issue I'll solve this

Thankyou so much! 
You can work on this!

**Comment by shivam-sharma7** [comment]
@shraddha761 But I would suggest to you to add badges like below because it would have small look and better look using this we can have better look of `README.md`

![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/91dac649-3037-41d4-b757-9306c2903abc)

**Comment by shivam-sharma7** [comment]
if you need any help let me know

**Comment by MonalikaPatnaik** [comment]
> @shraddha761 But I would suggest to you to add badges like below because it would have small look and better look using this we can have better look of `README.md`
> 
> ![image](https://user-images.githubusercontent.com/91419219/241127555-91dac649-3037-41d4-b757-9306c2903abc.png)

Yes yes, I already assigned this similar issue to add badges in readme!
