### ISSUE TITLE
Issue: Improve Landing Page Background Image for Enhanced Appeal and Relevance

### ISSUE THREAD

**Issue by rishitachail** [MonalikaPatnaik/UMatter#163]
Hello @MonalikaPatnaik  and @i-am-SnehaChauhan 

Description:
Upon visiting the website, I have noticed that the current background image on the landing page is of low quality and does not effectively convey the mission of the site. As the landing page serves as a crucial first impression for users, it should be visually appealing and representative of the site's purpose.

Proposed Solution:
To enhance the landing page, I suggest replacing the existing background image with a high-quality image, animation, or video that better aligns with the site's mission. The new media asset should effectively communicate the purpose of the site and engage the target audience.

Tasks:
1.Find or create a high-quality image, animation, or video that aptly represents the site's mission.
2.Resize or edit the chosen media asset, if necessary, to ensure it fits well within the landing page layout and maintains its quality.
3.Replace the current background image with the new media asset in the website's HTML code.
4.Test the modified landing page across various devices and browsers to ensure responsiveness and proper display.

Request for Assignment:
As a contributor in GSSoC'23, I would like to be assigned to this task in order to improve the landing page background image. I am confident in my ability to source or create a high-quality media asset that will better convey the site's purpose and appeal to end users.

Please assign me this task, and I will promptly begin working on it to enhance the landing page's visual impact and relevance.

Thank you for considering my contribution!

![UMatter - Google Chrome 5_21_2023 3_59_52 PM](https://github.com/MonalikaPatnaik/UMatter/assets/108628119/c3c6e22f-4a31-4db1-85fe-4f574394521f)

**Comment by MonalikaPatnaik** [comment]
Hey..I think a similar issue has already been raised: #126 
If I won't get an update there...will assign it to you!
Thanks!
