### ISSUE TITLE
Navbar improvement 

### ISSUE THREAD

**Issue by Ritu01-git** [MonalikaPatnaik/UMatter#169]
The main attraction of the user should be the front page so the navbar can be improved and when the cursor is pointing to any button it should be coloured as per the theme of the website but it's blue.

And in the mobile view nav bar is not working 

![image](https://github.com/MonalikaPatnaik/UMatter/assets/73469881/fdd9f7b0-c542-4bbe-be76-8ece87e4bd3d)
and this our services getting clipped!

**Comment by Ritu01-git** [comment]
I will fix this, please assign it to me

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by MonalikaPatnaik** [comment]
hey..similar issue is already been assigned: #7
Thanks!
