### ISSUE TITLE
Google OpenId connect for direct google login

### ISSUE THREAD

**Issue by gmmkmtgk** [MonalikaPatnaik/UMatter#17]
To enable direct Google login using OpenID Connect, you can follow these steps:

Set up a new project on the Google Developers Console:

Go to the [Google Developers Console](https://console.developers.google.com/).
Create a new project or select an existing project.
Enable the Google Identity API:

In the project dashboard, click on "Enable APIs and Services."
Search for "Google Identity" and select the "Google Identity" API.
Click on the "Enable" button to enable the API for your project.
Configure the OAuth consent screen:

In the project dashboard, go to the "OAuth consent screen" tab.
Choose an "Application type" (e.g., Internal or External) and enter the necessary details.
Add the required scopes (email and profile) for accessing user information.
Save the changes.
Create OAuth 2.0 credentials:

In the project dashboard, go to the "Credentials" tab.
Click on the "Create Credentials" button and select "OAuth client ID."
Select "Web application" as the application type.
Enter a name for the OAuth client ID.
Add the authorized JavaScript origins (e.g., http://localhost:8000/) and redirect URIs (e.g., http://localhost:8000/auth/google/callback).
Save the credentials.
Obtain the client ID and client secret:

After creating the credentials, you will receive a client ID and client secret. Take note of these values as you will need them for the implementation.
Implement the authentication in your application:

Use a server-side framework or library (such as Node.js with Passport.js or Django with python-social-auth) to handle the authentication flow.
Install the necessary dependencies and configure the framework/library to use the Google OpenID Connect strategy.
Provide a login button in your application that redirects users to the Google authorization URL, passing your client ID and requested scopes as parameters.
Once the user grants permission, Google will redirect the user back to your specified redirect URI along with an authorization code.
Exchange the authorization code for an access token and ID token by making a server-to-server request to the Google token endpoint using your client ID, client secret, redirect URI, and the authorization code.
Verify the ID token to ensure its authenticity and extract user information such as email and profile details.
Use the obtained user information to create or authenticate the user within your application.
Please note that the implementation details may vary depending on the programming language and framework you are using. Make sure to consult the relevant documentation for the specific framework or library you choose.

Remember to handle errors, implement appropriate security measures, and follow best practices to protect user data and ensure a secure authentication flow.

I hope this helps you get started with implementing direct Google login using OpenID Connect! Let me know if you have any further questions.

**Comment by MonalikaPatnaik** [comment]
Hey..you can start working...
Thanks for contributing!

**Comment by gmmkmtgk** [comment]
@Mansi168 @MonalikaPatnaik we need to connect for this
goggle credentials will be yours only

**Comment by Deepanshu0703** [comment]
Can't we do firebase Google login

**Comment by Mansi168** [comment]
hey @gmmkmtgk are u still working on this issue?

**Comment by Deepanshu0703** [comment]
I wanna contribute, If this issue is still there
