### ISSUE TITLE
fixing UMatter hover on sign in page 

### ISSUE THREAD

**Issue by laibaahsan27** [MonalikaPatnaik/UMatter#170]
On the contact page the hover on the website name UMatter is coming when i scroll on the whole line. let me fix it so the hover only comes when you scroll over the word "UMatter". Please assign it to me under the label GSSOC 2023.

**Comment by laibaahsan27** [comment]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/123810454/10cfc8b5-2847-45cb-b921-01fe5c7cb7c8)
as you can see the hover got activated when my cursor was far away but in the same vertical line of the page. also i noticed that the link is also working on that whole vertical line. if you assign me this i will fix bith the issues that is the hover animation and link will only work when you scroll over "UMatter".

**Comment by MonalikaPatnaik** [comment]
Heyy..this will remove and the navbar is to be added in this page which is already been assigned!
Thanks!
