### ISSUE TITLE
the tilted chat box logo

### ISSUE THREAD

**Issue by laibaahsan27** [MonalikaPatnaik/UMatter#172]
the chat box message logo is not vertically aligned. Assign the project to me and i will correct its allignment. please assign it to me under the label of GSSOC 2023.

**Comment by laibaahsan27** [comment]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/123810454/0bec8bcf-c242-436e-b8ef-1fc0da032a3a)
As you can see the message logo is tilted. Allow me to fix it.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by MonalikaPatnaik** [comment]
The chatbot is completely being redesigned by someone else!
