### ISSUE TITLE
Adding responsiveness to footer section for  tablet / mobile view. 

### ISSUE THREAD

**Issue by abhi03ruchi** [MonalikaPatnaik/UMatter#173]
<img width="574" alt="Screenshot 2023-05-21 at 5 34 30 PM" src="https://github.com/MonalikaPatnaik/UMatter/assets/105661636/6375a2c1-5504-4b89-8f3e-5220a31445cd">

I would like to add responsiveness to the footer section of this page. So that it looks perfect in mobile/ tablet view also. I would also like to enhance the footer style and make it more visually appealing.

**Comment by MonalikaPatnaik** [comment]
hey..similar issue is already been assigned!
