### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by bhaskarkumar1** [MonalikaPatnaik/UMatter#176]
Please assign me the task to update readme.md as ther is process written to setup and run react project on local system.

**Comment by i-am-SnehaChauhan** [comment]
Hey, @bhaskarkumar1 Readme is already updated I don't think anything is remaining.
can u elaborate more on what do u want to include?

**Comment by bhaskarkumar1** [comment]
> 

how to start this react project 
by using npm i and doing npm start

**Comment by MonalikaPatnaik** [comment]
hey..similar issue is already been assigned!
will assign you if we need improvemnts!

**Comment by bhaskarkumar1** [comment]
ok I am closing it @shivam-sharma7
