### ISSUE TITLE
Get Started in the Home page is not sending to Other page 

### ISSUE THREAD

**Issue by Skaronite** [MonalikaPatnaik/UMatter#177]
The Get started home page has to scroll down to the About us page

**Comment by Parsanta** [comment]
i want to contribute on this as a part of gssoc23

**Comment by MonalikaPatnaik** [comment]
hey..similar issue is already been assigned!
Thanks!

**Comment by shivam-sharma7** [comment]
close this @Skaronite

**Comment by Skaronite** [comment]
closed
