### ISSUE TITLE
The Footer Umatter is Not Clickable

### ISSUE THREAD

**Issue by Skaronite** [MonalikaPatnaik/UMatter#178]

**Comment by akshaysoni10** [comment]
Please assign this task to me under GSSOC' 23.

**Comment by MonalikaPatnaik** [comment]
Hey @Skaronite you can start working on this! pls submit your pR soon!

**Comment by MonalikaPatnaik** [comment]
Hey @Skaronite are u working on this??pls lmk if u cann't will assign it to someone else!

**Comment by Skaronite** [comment]
Yes I am working on it

**Comment by MonalikaPatnaik** [comment]
> Yes I am working on it

Then make a PR soon so that we can merge it without conflicts!

**Comment by MonalikaPatnaik** [comment]
Heyy pls do it soon!

**Comment by MonalikaPatnaik** [comment]
Hey @akshaysoni10..you are assigned! pls make a Pr by today itself!

**Comment by akshaysoni10** [comment]
Ok, I will submit PR by today itself.
