### ISSUE TITLE
What is the plan after clicking get started and clicking services?

### ISSUE THREAD

**Issue by gmmkmtgk** [MonalikaPatnaik/UMatter#18]
I see the website as completely dead as of now 
@MonalikaPatnaik what are the plans?

**Comment by MonalikaPatnaik** [comment]
Heyy...currently working on the services page!

**Comment by gmmkmtgk** [comment]
@MonalikaPatnaik you can give these pages to me but then you need to provide me figma design.

And the idea of what we are trying to achieve

**Comment by saiwali** [comment]
Hello @gmmkmtgk  I want to make a valuable contribution to this issue. Can you assign it to me ??

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik you can give these pages to me but then you need to provide me figma design.
> 
> And the idea of what we are trying to achieve

Hey you are free to make any page for services section..pick any one services page and start working on it..It's not mandatory that you create the page as a whole in one go..you can even create separate issues !
for eg--let's suppose you are creating connect with friends page, then at first you just create a dummy page having basic functionalities, then after the PR is merged, you will raise a separate issue for enchancing it's features...for eg--adding dark theme to that page..hover effect, animations etc..
Hope it clears!

**Comment by i-am-SnehaChauhan** [comment]
Hey Everyone now It's been done so I'm closing it.
