### ISSUE TITLE
Add Dropdown navigation menu

### ISSUE THREAD

**Issue by Guli93** [MonalikaPatnaik/UMatter#181]
I want to add a responsive dropdown menubar.

please assign this task to me

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
Are u talking about hamburger menu in mobile view?
If yes, then it's been already assigned!
Thanks!

**Comment by shivam-sharma7** [comment]
@Guli93 close this
