### ISSUE TITLE
about section

### ISSUE THREAD

**Issue by BTANISHA11** [MonalikaPatnaik/UMatter#182]
I want to add some more data in about section.
can you pls assign this to me.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by BTANISHA11** [comment]
Sorry but i am working.

**Comment by BTANISHA11** [comment]
> I want to work on this Project. Plzz assign it to me.

Sorry but i am working on this already.

**Comment by MonalikaPatnaik** [comment]
Hey.. I think it's already been assigned!
Will let u know if improvemnt is needed
Thanks!

**Comment by BTANISHA11** [comment]
ok sure

**Comment by MonalikaPatnaik** [comment]
Hey @BTANISHA11 you can start working on the content of about section but don't change the current one..Add some more content or images to make it look more better..
Thanks!

**Comment by BTANISHA11** [comment]
Thank you mam for giving me this opportunity.
