### ISSUE TITLE
Padding Issue

### ISSUE THREAD

**Issue by piyushkhurana2019** [MonalikaPatnaik/UMatter#184]
Website is having padding issues when seen in mobile view, i  have resolved them.
before:
<img width="1440" alt="Screenshot 2023-05-21 at 7 13 11 PM" src="https://github.com/MonalikaPatnaik/UMatter/assets/96003210/a0d684eb-7134-486a-9d23-e766bc720648">

After:
<img width="1440" alt="Screenshot 2023-05-21 at 7 13 03 PM" src="https://github.com/MonalikaPatnaik/UMatter/assets/96003210/beeead77-0bf1-40b4-be23-f30be1b9e201">

**Comment by Mansi168** [comment]
okay let me assign you...then make a pr :)
