### ISSUE TITLE
Adding pointer cursor to "get started" button

### ISSUE THREAD

**Issue by dhritiluthra** [MonalikaPatnaik/UMatter#187]
Hi!
Adding cursor to both the get started button!
Can you please assign this issue to me under GSSOC :)

**Comment by Mansi168** [comment]
hey @dhritiluthra it is already done :'( 
please look for another issue!
happy contributing!

**Comment by dhritiluthra** [comment]
> hey @dhritiluthra it is already done :'( please look for another issue! happy contributing!

okay:)

**Comment by Naincy04** [comment]
Hello, I'm a contributor to GSSoc'23 and I want to work on this issue. Can u please assign this issue to me?

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
hey..it's been resolved now!
Thanks!
