### ISSUE TITLE
The website logo link do not take to the homepage

### ISSUE THREAD

**Issue by ritik48** [MonalikaPatnaik/UMatter#188]
The link provided to the website logo is incorrect, it does not take us to the homepage.

I would like to solve this , please assign this issue to me under GSSoC'23.

**Comment by SALONI-AGGARWAL0304** [comment]
I have worked upon website development and build 2 websites , so this would be easy task for me , please assign this to me

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by Naincy04** [comment]
Hello, I'm a contributor to GSSoc'23 and I want to work on this issue. Can u please assign this issue to me?

**Comment by MonalikaPatnaik** [comment]
Hey i think you are talking about link in Navbar..but the navbar is already been assigned to #7
Thanks!
