### ISSUE TITLE
Add issue Templates

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#189]
This issue is about adding issue template for contributors

@Mansi168 @MonalikaPatnaik

**Comment by shivam-sharma7** [comment]
may you assign me @MonalikaPatnaik?

**Comment by MonalikaPatnaik** [comment]
Hey...sure..you are assigned..
Thanks for contributing!

**Comment by MonalikaPatnaik** [comment]
Hey..are u done with it?

**Comment by shivam-sharma7** [comment]
@MonalikaPatnaik No, will do it today after 5:00 PM
