### ISSUE TITLE
Create a Signup Components and add it to the NavBar

### ISSUE THREAD

**Issue by KrownWealth** [MonalikaPatnaik/UMatter#192]
Currently, the Signup menu on the navigation bar onclick didn't link to any page. I'd love to work on this by creating a Singup components and link it to the Signup menu.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by MonalikaPatnaik** [comment]
hey..similar issue is already been assigned: #12
