### ISSUE TITLE
Improve the Sign-in page UI by placing the navigation bar on the top of the page to enhance easy navigation.

### ISSUE THREAD

**Issue by KrownWealth** [MonalikaPatnaik/UMatter#193]
** I noticed the sign-in page onclick open on a new page and the page did not have a navigation menu. This might slow down or decrease seamless user navigation from one page to another. I would like to place the naviagtion menu on the page.**

![UMatter](https://github.com/MonalikaPatnaik/UMatter/assets/100444940/28316483-c389-4e96-bab3-500f7b111b9b)

**Comment by SALONI-AGGARWAL0304** [comment]
I want top work upon the above issue , as I have made some projects

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by MonalikaPatnaik** [comment]
Hey...similar issue has already been assigned..
Thanks!
