### ISSUE TITLE
Improve the sign-in page password input field icon

### ISSUE THREAD

**Issue by KrownWealth** [MonalikaPatnaik/UMatter#194]
**The icon on the password input field is not well align to the right. I would love to work on this issue**

![UMatter](https://github.com/MonalikaPatnaik/UMatter/assets/100444940/f37c2b5e-9020-4bfb-825e-7cd2dcb169e5)

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
Already been assigned: #123
Thanks!
