### ISSUE TITLE
Navbar is not aligned for both devices

### ISSUE THREAD

**Issue by Soyeb01** [MonalikaPatnaik/UMatter#197]
## Description
Navbar for both mobile and computer screen are not aligned center.

## Link to the component
Navbar -> Index
https://github.com/MonalikaPatnaik/UMatter/blob/main/src/Components/Navbar/index.js

### Mobile screen
![monalikapatnaik github io_UMatter_(iPhone SE)](https://github.com/MonalikaPatnaik/UMatter/assets/98175646/bbecd7c6-57c3-45bd-b7ac-f0f3c99323c5)

### Computer screen
![monalikapatnaik github io_UMatter_](https://github.com/MonalikaPatnaik/UMatter/assets/98175646/c1466a4f-a174-40c0-bc11-5567e6bb1be3)

**Comment by Soyeb01** [comment]
I would like to work in this issue under GSSOC'23, please assign me this issue.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
hey..similar issue is already been assigned!

**Comment by Soyeb01** [comment]
I will close this issue as it is duplicate.
