### ISSUE TITLE
Adding certificates on successful quitting of bad habits

### ISSUE THREAD

**Issue by anan262** [MonalikaPatnaik/UMatter#198]
Hey! I'm a GSSOC contributor and I'm suoer thrilled to contribute to this repo! Its amazing to work on a repo that has a real life implication and the idea is wonderful! I would like to add on this idea to motivate the people to quit their bad habits! I'm a sophomore amd would like to contribute to this one

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by anan262** [comment]
I have deep experience on the same and would highly appreciate if I were asssigned this one!

**Comment by Naincy04** [comment]
Hello, I'm a contributor to GSSoc'23 and I want to work on this issue. Can u please assign this issue to me?

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
> Hey! I'm a GSSOC contributor and I'm suoer thrilled to contribute to this repo! Its amazing to work on a repo that has a real life implication and the idea is wonderful! I would like to add on this idea to motivate the people to quit their bad habits! I'm a sophomore amd would like to contribute to this one

Hey..Could you elaborate your approach and explain where you would incorporate the changes?
