### ISSUE TITLE
Links/Buttons not working

### ISSUE THREAD

**Issue by anunayandkumar** [MonalikaPatnaik/UMatter#199]
Various social  links , contact us buttons are not working . I can fix the issue under GSSoC' 23 . Accordingly assign it to me

**Comment by Naincy04** [comment]
Hello, I'm a contributor to GSSoc'23 and I want to work on this issue. Can u please assign this issue to me?

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
Hey..Contact us and testimonials button in footer is already been assigned..Would you like to work on some other button in footer?

> Various social links , contact us buttons are not working . I can fix the issue under GSSoC' 23 . Accordingly assign it to me

**Comment by Avinash-NCEIAN** [comment]
> Hey..Contact us and testimonials button in footer is already been assigned..Would you like to work on some other button in footer?
> 
> > Various social links , contact us buttons are not working . I can fix the issue under GSSoC' 23 . Accordingly assign it to me

Yes

**Comment by anunayandkumar** [comment]
> Hey..Contact us and testimonials button in footer is already been assigned..Would you like to work on some other button in footer?
> 
> > Various social links , contact us buttons are not working . I can fix the issue under GSSoC' 23 . Accordingly assign it to me

Yes Sure. Please assign that to me

**Comment by MonalikaPatnaik** [comment]
> > Hey..Contact us and testimonials button in footer is already been assigned..Would you like to work on some other button in footer?
> > > Various social links , contact us buttons are not working . I can fix the issue under GSSoC' 23 . Accordingly assign it to me
> 
> Yes Sure. Please assign that to me

Then on what button in footer would you like to work?
