### ISSUE TITLE
Navbar not operational in mobile view 

### ISSUE THREAD

**Issue by 007aneesh** [MonalikaPatnaik/UMatter#2]
Fixing navbar to be responsive

![Screenshot_2023-05-20-00-22-17-055_com.android.chrome.jpg](https://github.com/MonalikaPatnaik/UMatter/assets/90706436/50bb4f54-bab5-4ce3-861a-80ce431a324d)

**Comment by Iron-Thunder** [comment]
I can work on this issue. Can You please assign me??
