### ISSUE TITLE
improve the footer

### ISSUE THREAD

**Issue by karthiknadar1204** [MonalikaPatnaik/UMatter#20]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
The footer links can be spread across three rows and one fourth row with the favicons for the social links and the logo for the project at the top left corner of the footer and the copyright statement at the bottom of the footer in the middle

**Comment by Mansi168** [comment]
@karthiknadar1204 you are assigned !

**Comment by karthiknadar1204** [comment]
Thank you,will start working

**Comment by karthiknadar1204** [comment]
@Mansi168 The footer social links seem to be broken,could you provide the specific links to be directed to ?

**Comment by MonalikaPatnaik** [comment]
> @Mansi168 The footer social links seem to be broken,could you provide the specific links to be directed to ?

No, currently we don't have social links as of now!
