### ISSUE TITLE
Improve indication of active link in the navbar

### ISSUE THREAD

**Issue by Kalyan-velu** [MonalikaPatnaik/UMatter#200]
### Description
Currently, the navbar in the project does not have any indication of the active link. When a link is clicked, it simply scrolls to the associated element ID. This lack of visual feedback makes it confusing for users to identify which section they are currently viewing, such as the about section or other sections.

### Goals
The main goal of this issue is to remove the confusion and improve the user experience by providing a clear indication of the active link in the navbar. Some specific improvements, functionalities, or design elements that could be considered include:

- Highlighting the active link by changing its color, background, or underline.
- Adding an indicator, such as an arrow or icon, next to the active link.
- Applying a different font weight or style to the active link.
- Using a scrollspy functionality to automatically update the active link as the user scrolls through the page.

### Proposed Solution
1. Implement a CSS class or style using Styled Components that can be dynamically applied to the active link in the navbar.
2. Use JavaScript to detect the active section on the page based on scroll position and update the active link accordingly.

### GirScript Summer of Code 2023
This issue is part of my contribution to GirScript Summer of Code 2023. I am open to fixing this issue.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
Hey..navbar is currently being resolved by #7 
If there is no indication of active link..I'll assign it to you!
Thanks..

**Comment by Avinash-NCEIAN** [comment]
> Hey..navbar is currently being resolved by #7 If there is no indication of active link..I'll assign it to you! Thanks..

OK

**Comment by Kalyan-velu** [comment]
> Hey..navbar is currently being resolved by #7 If there is no indication of active link..I'll assign it to you! Thanks..

@MonalikaPatnaik assigning me or @Avinash-NCEIAN ?

**Comment by Kalyan-velu** [comment]
@MonalikaPatnaik the issue still not resolved.
