### ISSUE TITLE
Hover effect of navbar items is not attractive to users.

### ISSUE THREAD

**Issue by akshaysoni10** [MonalikaPatnaik/UMatter#204]
**Problem** :- The hover effect of navbar items was very simple and it's not seems attractive to any users.
**Solution** :- We need a creative and attractive hover effect for better user experience.

**Comment by iamFaizanArif** [comment]
Assign me I can make it attractive!

**Comment by Avinash-NCEIAN** [comment]
I want to work on this project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
Navbar is already been assigned to issue: #7 
Thanks!

**Comment by MonalikaPatnaik** [comment]
Hey @akshaysoni10..you can improve the hover effect of Umatter in the Navbar..if u see when we hover it..it becomes blue which is not looking good..so you can change it to a good Hover effect! If u want u can add the same hover in the footer part also!

**Comment by MonalikaPatnaik** [comment]
Also, @akshaysoni10 pls submit your PR soon so that we can merge it without conflicts as so many contributors are already working on navbar..it's hard to merge each of them! I hope u understand
Thanks!

**Comment by akshaysoni10** [comment]
Thank you for assigning me this task, I will try to complete the task very soon.
