### ISSUE TITLE
Unwanted horizontal scrollbar appears below width 1185px.

### ISSUE THREAD

**Issue by Devil1205** [MonalikaPatnaik/UMatter#205]
Responsiveness issue for small devies. I would like to work to fix this issue. Please kindly assign me this issue.

![image](https://github.com/MonalikaPatnaik/UMatter/assets/103431946/38e709d0-24ab-4dbc-8af9-b11efad35d9d)

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
Hey..Responsiveness related issue is already being assigned!
