### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by ImranNawar** [MonalikaPatnaik/UMatter#208]
Hi there!
I recommend adding a **CODE_OF_CONDUCT.md** file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

I would like to work on this issue. Please assign it to me under **GSSoC'23**.

Thank you!

**Comment by KashiwalHarsh** [comment]
Hey @ImranNawar Can i contribute codeofconduct.md file to this project under GSSOC 
I would be my first contribution if this issue is assigned to me

Thanks

**Comment by MonalikaPatnaik** [comment]
Hey sure..you can work on this..
Thanks for contributing!

> Hi there! I recommend adding a **CODE_OF_CONDUCT.md** file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.
> 
> I would like to work on this issue. Please assign it to me under **GSSoC'23**.
> 
> Thank you!
