### ISSUE TITLE
Add a scroll to top navigation button

### ISSUE THREAD

**Issue by KashiwalHarsh** [MonalikaPatnaik/UMatter#209]
There is an absence of a scroll-to-top button on the website. The website's user experience would be improved by the addition of this floating button.
I have build a lot of personal projects with just few lines of code scroll to top button, I'd like to contribute this feature.

Please assign me the task under GSSoC'23.

I can also update the footer if you want with good styling for the links

**Comment by MonalikaPatnaik** [comment]
hey..I think the similar issue has been previously assigned..

**Comment by KashiwalHarsh** [comment]
Ohh I didn't notice on the first go 
What is to be done now for this issue?
