### ISSUE TITLE
NAVBAR NOT RESPONSIVE IN MOBILE VIEW

### ISSUE THREAD

**Issue by DHRUVKHANDELWAL00** [MonalikaPatnaik/UMatter#21]
PLEASE ASSIGN ME SO THAT I CAN START WORKING ON THIS ISSUE

**Comment by AmanMittal-3305** [comment]
hii
please assign me this issue

**Comment by Shrejal123** [comment]
I am interested in working on this issue. Could you please assign it to me?

**Comment by MonalikaPatnaik** [comment]
Heyy someone is working on this: #7

**Comment by purviporwal0** [comment]
pls assign this to me for GSSOC'23

**Comment by Vidhi-44** [comment]
I want to work on this issue. Please assign this to me

**Comment by Pragati-3003** [comment]
Hey @Mansi168 
I would like to work on this. 
Please assign this to me under GSSOC'23.

**Comment by bleep123** [comment]
Hi,
I would like to work on this issue. Please assign it to me.

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by MonalikaPatnaik** [comment]
> PLEASE ASSIGN ME SO THAT I CAN START WORKING ON THIS ISSUE

Heyy @DHRUVKHANDELWAL00..you can design the Mobile menu to make it look more appealing & add light/dark theme, i think sign in & sign up button is also not there..do fix it as well in accordance with the current design..
Pls submit your PR asap so that we can merge it without conflicts! and lmk if u cann't work on this?

**Comment by DHRUVKHANDELWAL00** [comment]
@MonalikaPatnaik  Would make changes and make a PR by today itself!

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik Would make changes and make a PR by today itself!

Thankss!

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik Would make changes and make a PR by today itself!

Hey what's the status? if u are unable to do just lmk??

**Comment by DHRUVKHANDELWAL00** [comment]
@MonalikaPatnaik  Just ran into a few bugs. Will lyk today if i am able to do it or not.

**Comment by vk20july** [comment]
mam i want to work on this issue under gssoc'23
