### ISSUE TITLE
want to add some smooth hover animation effect on images

### ISSUE THREAD

**Issue by Guli93** [MonalikaPatnaik/UMatter#210]
Hey!! on services page there is hover effect added but no animation used and I can make the hover effect very smooth using some nice animation.

please assign me this task.

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
Cards animation on services page is already been assigned!
Thanks!
