### ISSUE TITLE
adding logo in the navbar and footer

### ISSUE THREAD

**Issue by anuza08** [MonalikaPatnaik/UMatter#212]
This will improve the UI

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
I think similar issue has already been raised..I'll assign it to you if logo part is not being handled!
Thanks!

**Comment by anuza08** [comment]
sure !@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Heyy @anuza08..you can add logo of UMatter in the footer part only and submit your PR soon!
Thanks!

**Comment by MonalikaPatnaik** [comment]
Heyy @anuza08 are u still working on it?? if u cann't just lmk..will assign it to someone else!
submit your PR by today itself if u are working

**Comment by anuza08** [comment]
@MonalikaPatnaik I'm working on it, please give me some time.

**Comment by MonalikaPatnaik** [comment]
Pls do it soon!

**Comment by anuza08** [comment]
@MonalikaPatnaik

**Comment by anuza08** [comment]
@MonalikaPatnaik can I get time till Tuesday?

**Comment by MonalikaPatnaik** [comment]
Ok! But I need your PR on tues eod

**Comment by anuza08** [comment]
@MonalikaPatnaik Hey, I'm new to React and I'm having a problem opening the file.
will you please help me?

**Comment by MonalikaPatnaik** [comment]
Yes yes ask

**Comment by anuza08** [comment]
![Screenshot (20)](https://github.com/MonalikaPatnaik/UMatter/assets/98256478/41733b6b-0c3b-46e1-9c21-629cf14fc023)
why I'm getting these errors??

**Comment by MonalikaPatnaik** [comment]
Hey @Avinash-NCEIAN are u willing to do it???
