### ISSUE TITLE
Animate on page scroll 

### ISSUE THREAD

**Issue by Guli93** [MonalikaPatnaik/UMatter#213]
I can add some nice animations on page scroll.

please assign this project to me.

**Comment by Naincy04** [comment]
Hello, I'm a contributor to GSSoc'23 and I want to work on this issue. Can u please assign this issue to me?

**Comment by Avinash-NCEIAN** [comment]
I want to work on this Project. Plzz assign it to me.

**Comment by MonalikaPatnaik** [comment]
> I can add some nice animations on page scroll.
> 
> please assign this project to me.

Hey Could you elaborate a bit  by attaching a ss or video for refernce!

**Comment by Guli93** [comment]
> > I can add some nice animations on page scroll.
> > please assign this project to me.
> 
> Hey Could you elaborate a bit by attaching a ss or video for refernce!

yeah sure!!

As you can see  every section has some animation when you scroll down like text is coming up smoothly but on services page the carts have no animations.

if carts will have animation when you scroll down [not hover effect ] it will make the UI more attractive.

**Comment by Guli93** [comment]
> Hey this has been already assigned #83

okay thanks!!
