### ISSUE TITLE
[Bug]: Footer Not Functioning Correctly

### ISSUE THREAD

**Issue by mhdamaan79** [MonalikaPatnaik/UMatter#214]
The footer section on the website is currently not functioning as intended. When clicking on any option in the footer, it only opens the signup page instead of directing users to the relevant pages. This issue adversely affects the user experience and needs to be addressed.

I would like to work on this issue under the **GSSoC'23.** @MonalikaPatnaik

**Comment by yash8917** [comment]
I would like to work on this issue pls assign me under the GSSOC '2023
