### ISSUE TITLE
 Request to Add Issue Templates: Bug Report, Feature Request, and Styling

### ISSUE THREAD

**Issue by mhdamaan79** [MonalikaPatnaik/UMatter#215]
I propose adding three important issue templates to our project: **Bug Report, Feature Request, and Styling.** 
These templates will enhance our project management and collaboration by providing standardized formats for reporting bugs, submitting feature requests, and addressing styling-related issues. With these templates, we can streamline communication, improve issue tracking, and ensure consistency in our development and design processes.

I would like to work on this issue under the **GSSoC'23.** @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
adding issue template is already been assigned!
Thanks!

**Comment by mhdamaan79** [comment]
Can I close my issue since it has already been raised by someone else as you said?
