### ISSUE TITLE
redesigning of main logo in header and its alignment 

### ISSUE THREAD

**Issue by gaur15** [MonalikaPatnaik/UMatter#22]

**Comment by MonalikaPatnaik** [comment]
Hey...I am expecting that you will add a logo in the navbar beside Umatter..

**Comment by Abhiramjampani** [comment]
hey @i-am-SnehaChauhan i am ready to resolve this issue please assign it to me under GSSOC'23

**Comment by MonalikaPatnaik** [comment]
Heyy.. @gaur15..it's been long..are you working on this??otherwise will assign it to someone else!

**Comment by gaur15** [comment]
> Heyy.. @gaur15..it's been long..are you working on this??otherwise will assign it to someone else!

yes mam I'm working on this I even did the work only last edit and pull request is left. sorry mam for the inconvenience
