### ISSUE TITLE
Animate text

### ISSUE THREAD

**Issue by Dimple-Choudhary** [MonalikaPatnaik/UMatter#220]
I would like to animate the text on the website **[GSSOC23].**

@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
For which part of website would u animate the text?

**Comment by Dimple-Choudhary** [comment]
I will animate `H1` tags with the type effect like a **typewriter**

**Comment by MonalikaPatnaik** [comment]
Hey are u done with your changes? I recommend to submit your PR soon!

**Comment by Dimple-Choudhary** [comment]
Yes, I am done with issue I will make PR tomorrow

Thank you
