### ISSUE TITLE
Hover Effects throughout the page

### ISSUE THREAD

**Issue by anunayandkumar** [MonalikaPatnaik/UMatter#225]
I would like to add hover effects and animations in the page . Accordingly, assign this to me under GSSoC' 23 .

**Comment by MonalikaPatnaik** [comment]
I think similar issue is already been assigned..will assign you if required..
Thanks!

**Comment by anunayandkumar** [comment]
OK , 

> I think similar issue is already been assigned..will assign you if required.. Thanks!
