### ISSUE TITLE
Applying Animation throught the page 

### ISSUE THREAD

**Issue by AmanSingh6574** [MonalikaPatnaik/UMatter#228]
Issue - 
1. If you hover over any button, The button changes color abruptly 
2. In Navbar I can add a nice hover effect to the buttons

I can solve this issue 
I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23
@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Navbar and improving ui of buttons is already been assigned..
