### ISSUE TITLE
Remove underline form Get Started Button 

### ISSUE THREAD

**Issue by Prajwal0225** [MonalikaPatnaik/UMatter#23]
The underline on `Get Started` button is not looking good. If you agree with me then please assign this issue to me so that I can fix it 😇

**Comment by vikram-8290** [comment]
@MonalikaPatnaik 
The Cursor also is not Changing While Hovering Over The Get Started Button.
If Issue Is Still open I like to Contribute to it

**Comment by Prajwal0225** [comment]
### I encounter that cursor not changing on hover for the "Get Started" button

**Description**:
I have encountered an issue where the cursor does not change when hovering over the "Get Started" button on the webpage. Currently, the cursor remains in its default state, indicating that the button is not interactive.

**Observation**:
Upon investigating the issue, I noticed that the cursor does not change when hovering over the "Get Started" button. This behavior is inconsistent with user expectations and may lead to confusion or frustration.

**Proposed Solution**:
To address this issue, I suggest adding the CSS property cursor: "pointer" to the style definition of the "Get Started" button. This will change the cursor to a pointer icon, indicating that the button is clickable and interactive.

**Visual Representation**:
Here is a comparison of the button's appearance before and after implementing the suggested CSS property:


**Before** ⤵️ 
![change 1](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/da4c0e06-5ff2-499e-a782-9f585d346d0d)
 
After ⤵️ 

![change1 after](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/5f8d1345-20e4-4e76-854b-15b611bedb83)


Can you please assign this issue to me? if you think it's important so that I can resolve it?
