### ISSUE TITLE
Add a Contact Page

### ISSUE THREAD

**Issue by Samriddhi15** [MonalikaPatnaik/UMatter#232]
Hello @MonalikaPatnaik mam, I can create a different contact page. If you are agree with it , please assign me this issue under GSSoc'23.

**Comment by Abhiramjampani** [comment]
hey @MonalikaPatnaik , I can create a contact page using tailwindcss and by giving a good functioning to buttons please assign me to this issue i will resolve it under GSSoc'23

**Comment by i-am-SnehaChauhan** [comment]
Hey, @Samriddhi15 and @Abhiramjampani I don't think a contact page is needed here because there is a facility of sign up and log in you guys can find others issue Thanks ;)

**Comment by MonalikaPatnaik** [comment]
> Hello @MonalikaPatnaik mam, I can create a different contact page. If you are agree with it , please assign me this issue under GSSoc'23.

Hey hey..contact us page is already been assigned
Thanks!
