### ISSUE TITLE
making all rights reserved part hoverable

### ISSUE THREAD

**Issue by anshikkay** [MonalikaPatnaik/UMatter#235]
![git3](https://github.com/MonalikaPatnaik/UMatter/assets/129502224/27ffd913-6568-40af-a851-8cc81f1a593e)

**Comment by MonalikaPatnaik** [comment]
Hey pls submit a PR soon!

**Comment by MonalikaPatnaik** [comment]
hey @anshikkay  what's the status???

**Comment by anshikkay** [comment]
@MonalikaPatnaik Ma'am ,i need some time, i am getting lot of errors during pushing my changes, i will submit pr ,maybe in 1 day.

**Comment by anshikkay** [comment]
#494

**Comment by vk20july** [comment]
@MonalikaPatnaik can i do this task under gssoc'23
