### ISSUE TITLE
Responsive image slider

### ISSUE THREAD

**Issue by Samriddhi15** [MonalikaPatnaik/UMatter#236]
Hello @MonalikaPatnaik mam, I can make a responsive image slider for the lading page for making the website more visually appealing and engaging. please assign me this issue under GSSoc'23. I will not disappoint you.

**Comment by Akanksha038** [comment]
Hello @MonalikaPatnaik Ma'am,
I would like to add Responsive image slider. This will help to enhance the user experience.
Please assign me this issue. I would like to work on this issue under GSSOC'23. Please let me fix this issue #236.
