### ISSUE TITLE
Improving the UI of signin page

### ISSUE THREAD

**Issue by harshsingh32** [MonalikaPatnaik/UMatter#24]
I would like to improve the herosection, infosection and signin page of the project. And also adding some features in footer element of the project.

**Comment by harshsingh32** [comment]
Hi, I would like to work on this issue under GSSoC'23.

**Comment by harshsingh32** [comment]
Please assign this issue to me under GSSoC'23.

**Comment by MonalikaPatnaik** [comment]
Heyy..you can work on a single part..I think you should update the UI of signin page..
Thanks!

**Comment by MonalikaPatnaik** [comment]
Heyy @harshsingh32 are you still working on this?

**Comment by harshsingh32** [comment]
Yeah @MonalikaPatnaik I am working on this issue.

**Comment by ParthMadhvani2** [comment]
hey, I would like to improve the UI design of the signup page and improve the hero section of the project. Changing the place of the button placed as it is not perfect for the user as I am also a UX designer. So, please assign this issue to me as I am a contributor to GSSoC'23.

**Comment by MonalikaPatnaik** [comment]
> Heyy @harshsingh32 are you still working on this?

Hey..I recommend to submit your PR soon otherwise will assign to someone else!

**Comment by MonalikaPatnaik** [comment]
Hey @harshsingh32..is it done? It's been long...submit your PR by today itself otherwise will assign to someone else! lmk if u cann't work on this??

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik If this issue is up for grabs, i would like to work on it.

**Comment by i-am-SnehaChauhan** [comment]
Hey @karthiknadar1204 you can start working on this issue

**Comment by karthiknadar1204** [comment]
Thank you

**Comment by MonalikaPatnaik** [comment]
I think the sign in page is already done! We don't need any further improvements in ui there! There are other components in website as well @karthiknadar1204 look at those once!
