### ISSUE TITLE
Template for people to have a proper format for bug fix, pull requests, new feature addition etc. 

### ISSUE THREAD

**Issue by tuhinaww** [MonalikaPatnaik/UMatter#240]
| Field | Value                           |
|-------|---------------------------------|
| About | Template for people to have a proper format for bug fix, pull requests, new feature addition etc. |
| Title |       Feature request             |
| **Is your feature request related to a problem? Please describe.** | New Contributors are not able to follow a proper format to create issue for bug fixes, pull request,  new feature additions etc. |
| **Describe the solution you'd like**                               | I can provide ".github" folder with all the necessary templates required it will not only help the contributors but mentors as well |
| **Additional context**                                             | I am from GSSOC'23 you can assign this issue to me |

**Comment by shivam-sharma7** [comment]
@tuhinaww see this #189 #190 is already created by me so you need to close this.
