### ISSUE TITLE
Add logo and change the sing in and sign up button to top-right and make signup button next to sign in button

### ISSUE THREAD

**Issue by Abhiramjampani** [MonalikaPatnaik/UMatter#244]
we can change sign in and sign up buttons side by side to top-right and change the background  of about and service pages 
and moreover we should keep about image left and the text right side if you agree i can change all these changes plese assign it to me under GSSoc'23

**Comment by i-am-SnehaChauhan** [comment]
Hey @Abhiramjampani This is similar to #22 
Please msg there thanks :)
