### ISSUE TITLE
Updating Footer UI

### ISSUE THREAD

**Issue by Google-Ka-Dinosaur** [MonalikaPatnaik/UMatter#245]
hey there!!! I would like to make a few changes to the footer such as aligning the drop downs, making the icons symmentrical and improving the size and spacing. Kindly assign me this issue. Thank you.

**Comment by i-am-SnehaChauhan** [comment]
Hey, This issue is similar to#143
please msg there Thanks :)

**Comment by Google-Ka-Dinosaur** [comment]
okay
