### ISSUE TITLE
Hide and show button is displaced in the password section of login form

### ISSUE THREAD

**Issue by Aanya9693** [MonalikaPatnaik/UMatter#247]
The hide and show button in the password section of the login form is not displaying correctly. The button is displaced to the left, making it difficult to click.

I want to work on this issue, please assign this to me.

![Screenshot (136)](https://github.com/MonalikaPatnaik/UMatter/assets/101557638/04d402cd-edf6-45ad-a20c-8ba670b95df9)

**Comment by MonalikaPatnaik** [comment]
Hey..it is already resolved!
