### ISSUE TITLE
Add GitHub ReadMe Badges to the repository

### ISSUE THREAD

**Issue by singh-anushka** [MonalikaPatnaik/UMatter#256]
I want to edit the main README.d file and add GitHub badges of languages and the number of PRs, etc. to it. Kindly assign me this issue.

**Comment by MonalikaPatnaik** [comment]
Hey..you are good to go!

**Comment by MonalikaPatnaik** [comment]
Hey @singh-anushka..pls submit your Pr sson so that we can merge it without conflicts!

**Comment by singh-anushka** [comment]
I will submit it by end of the day for sure.

**Comment by singh-anushka** [comment]
Please merge this PR with GSSOC23 level 2 label to it.
