### ISSUE TITLE
Editing the Home section

### ISSUE THREAD

**Issue by Chirag-04** [MonalikaPatnaik/UMatter#26]
I have an exciting idea to enhance the home section! Let's introduce a fantastic 'Book a Table' or 'Menu' section right under it. This addition will significantly elevate the user experience and drive customer engagement. With your permission, I am eager to start implementing this captivating feature, sir.
![Screenshot (741)](https://github.com/MonalikaPatnaik/UMatter/assets/95089015/eaef6b97-0606-4221-ae81-35169264cb69)

**Comment by Mansi168** [comment]
ok @Chirag-04 you are assigned!

**Comment by Pragati-3003** [comment]
Heyy @Mansi168 
I would like to work on this. 
Please assign this task to me under GSSOC'23.

**Comment by Chirag-04** [comment]
> ok @Chirag-04 you are assigned!

Thank you  mam😇

**Comment by MonalikaPatnaik** [comment]
Hey @Chirag-04..is it done?? also pls lmk, where are u adding this?

**Comment by Chirag-04** [comment]
> Hey @Chirag-04..is it done?? also pls lmk, where are u adding this?

Yes mam it's almost completed!!
and mam I am adding the buttons on the home page itself

**Comment by Akanksha038** [comment]
Hello @MonalikaPatnaik Ma'am,
I also want to work this issue. Can you please assign me this issue. I would like to work on this issue under GSSOC'23.    
Please let me fix this issue #26.
