### ISSUE TITLE
Requesting an Issue - Cursor Pointer Missing on "Get Started" Button Hover

### ISSUE THREAD

**Issue by devasyarajguru** [MonalikaPatnaik/UMatter#260]
The issue is that when hovering over the "Get Started" button on the website, the cursor does not change to the pointer icon, indicating that it is clickable. Currently, the default cursor is displayed instead.

This bug report aims to address the missing cursor pointer on the "Get Started" button and suggests making the necessary adjustments to ensure the cursor changes to the pointer icon when hovering over the button. This will provide visual feedback to users that the button is interactive and clickable, improving the overall user experience.

The issue will worked on both Buttons - (Get Started)

![Screenshot (62)](https://github.com/MonalikaPatnaik/UMatter/assets/84851506/0e2af544-34d9-498a-a5fb-9a753e30aca9)

**Comment by MonalikaPatnaik** [comment]
Hey.. I think you clicked the here button in readme..actually the link was not updated there..
You can checkout the new link, cursor issue is already being resolved

**Comment by devasyarajguru** [comment]
Ohh! When I click here button in readme and opened the website , the cursor issue was there but anyhow no problem , Looking forward to what else I can contribute
