### ISSUE TITLE
Blog page has no margin from bottom also it needs some styling 

### ISSUE THREAD

**Issue by P766-spec** [MonalikaPatnaik/UMatter#262]
![Screenshot (582)](https://github.com/MonalikaPatnaik/UMatter/assets/90417642/cd8c2ddc-b129-458a-bd2b-b8f8ef274257)

**Comment by P766-spec** [comment]
Hello, @MonalikaPatnaik , i wolud like to work on this issue  as the GSSOC'23, could you please assign this to me

**Comment by MonalikaPatnaik** [comment]
Heyy..are you done with your changes?? I suggest you to submit your PR soon!

**Comment by P766-spec** [comment]
I have already done it , pull request also!
