### ISSUE TITLE
Adding CSS to Blog Page

### ISSUE THREAD

**Issue by bkrayaguru931** [MonalikaPatnaik/UMatter#267]
Enhance the blog page by incorporating more CSS styles to improve its visual appearance and layout, ensuring a cohesive and visually appealing design that aligns with the overall website theme.

Please assign me this issue under GSSoC'23.

**Comment by Himanshi1207** [comment]
I can make it look attractive please assign it to me @bkrayaguru931 under GSSoC'23.

**Comment by MonalikaPatnaik** [comment]
> Enhance the blog page by incorporating more CSS styles to improve its visual appearance and layout, ensuring a cohesive and visually appealing design that aligns with the overall website theme.
> 
> Please assign me this issue under GSSoC'23.

Hii, I think it's been raised by #262

**Comment by shivam-sharma7** [comment]
close this @bkrayaguru931
