### ISSUE TITLE
Adding Navbar to Forgot Password Page

### ISSUE THREAD

**Issue by Abhiramjampani** [MonalikaPatnaik/UMatter#268]
there is no logo on top-left beside UMatter so i can add logo there and give it functioning to home button

**Comment by Abhiramjampani** [comment]
@MonalikaPatnaik  if you please assign me i can start working on it

**Comment by MonalikaPatnaik** [comment]
Heyy @Abhiramjampani..you opened so many issues..You can add navbar to the forgot password page...
Are u willing to work on this??

**Comment by Abhiramjampani** [comment]
> Heyy @Abhiramjampani..you opened so many issues..You can add navbar to the forgot password page... Are u willing to work on this?? ![image](https://user-images.githubusercontent.com/99353300/241392676-81e02f2a-94f3-4fd0-9680-c0a88fd69a35.png)

yes i am

**Comment by MonalikaPatnaik** [comment]
Okay great then add navbar in Forgot Password page!

**Comment by MonalikaPatnaik** [comment]
Hey is it done?? Pls submit your PR within one day otherwise will assign it to someone else!
