### ISSUE TITLE
add some animated background to about, service and blog pages

### ISSUE THREAD

**Issue by Abhiramjampani** [MonalikaPatnaik/UMatter#269]
if you assign it to me i can start workig on it @Mansi168 @MonalikaPatnaik @i-am-SnehaChauhan

**Comment by Abhiramjampani** [comment]
please assign it to me mam @Mansi168 @MonalikaPatnaik @i-am-SnehaChauhan

**Comment by MonalikaPatnaik** [comment]
Hey if bg image is added to these components then what's the point in having dark/light mode..

**Comment by Abhiramjampani** [comment]
> Hey if bg image is added to these components then what's the point in having dark/light mode..

we can add dark/light mode as theme setter as per user convenience but by add bg we can make our wesite more attractive

**Comment by Mansi168** [comment]
sorry @Abhiramjampani but it is not required right now!
