### ISSUE TITLE
Navbar items alignment issue and also not responsive.

### ISSUE THREAD

**Issue by Niladri2003** [MonalikaPatnaik/UMatter#27]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/93518661/06286cd7-e460-4da2-8ac0-a057384e65f1)

i want to fix the navbar alignment problem and make that responsive.

**Comment by MonalikaPatnaik** [comment]
Hey..this is being resolved by: #7

**Comment by Niladri2003** [comment]
ok, then find a new issue.

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Dimple-01** [comment]
I want to work on this issue.
I will fix this within few hours.
Please this work to me.
