### ISSUE TITLE
Adding logo

### ISSUE THREAD

**Issue by Abhiramjampani** [MonalikaPatnaik/UMatter#271]
![Screenshot (140)](https://github.com/MonalikaPatnaik/UMatter/assets/126624416/8a423740-6a98-4430-a2d9-cebc946daaaa)
i can add wesite logo there and can give functioning to home page 
so please assign this issue to me @Mansi168 @MonalikaPatnaik @i-am-SnehaChauhan

**Comment by Mansi168** [comment]
hey @Abhiramjampani someone is designing logo for our website, so after that ill assign you !

**Comment by Abhiramjampani** [comment]
> hey @Abhiramjampani someone is designing logo for our website, so after that ill assign you !

ya sure is it design done for logo ? @Mansi168

**Comment by MonalikaPatnaik** [comment]
> > hey @Abhiramjampani someone is designing logo for our website, so after that ill assign you !
> 
> ya sure is it design done for logo ? @Mansi168

yess..logo has been added to the navbar
