### ISSUE TITLE
Add testimonials in homepage

### ISSUE THREAD

**Issue by rishitachail** [MonalikaPatnaik/UMatter#272]
As a user, I would like to see testimonials on the homepage to gain trust and confidence in the product/service. Testimonials provide social proof and can greatly enhance the credibility of the website. This issue aims to add a testimonials section to the homepage.
 
I believe I can solve this issue . Assign it to me under GSSOC'23.

**Comment by MonalikaPatnaik** [comment]
You can work on this..thanks! Make sure to redirect the testimonial link in the footer as well !

**Comment by MonalikaPatnaik** [comment]
Hey are u working in this???

**Comment by rishitachail** [comment]
Yes . working on it. Could you give me 2-3 days . Actually my semester exams are going on.

**Comment by MonalikaPatnaik** [comment]
Hey..yes yes..good luck with your exams!

**Comment by MonalikaPatnaik** [comment]
Hey..testimonials component have been added to the navbar..you have to design the testimonial section..
Please do it asap!

**Comment by i-am-SnehaChauhan** [comment]
Hey @rishitachail have u completed its been too late submit your PR ASAP.

**Comment by abhi03ruchi** [comment]
I would like to create the testimonial section for the website .
Right Now , it is blank.
I would add an automatic carousel in there. This would improve user experience and engagement.

**Comment by i-am-SnehaChauhan** [comment]
@rishitachail if you are unable to do let me know so that i can assign it to others.

**Comment by rishitachail** [comment]
> @rishitachail if you are unable to do let me know so that i can assign it to others.

I had exam today. Shall submit in 2 hours. Thank you for the time.

**Comment by sumitkr2000** [comment]
Hey, @i-am-SnehaChauhan Can you assign me this issue? I can make this quicky.

**Comment by sumitkr2000** [comment]
Bhai localhost ka link kon share krta hai 😂

**Comment by Sachin4219** [comment]
That's what I was saying it is localhost 😞

**Comment by sumitkr2000** [comment]
Ohh got it... Assign me this issue i can fix it.
