### ISSUE TITLE
show password buttuon

### ISSUE THREAD

**Issue by Abhiramjampani** [MonalikaPatnaik/UMatter#274]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/126624416/c6fed553-0502-4b0a-b293-61b07261c0b6)
as we see there is no show password button an by clicking enter in our keyboard the password is going to be visible so i can resolve this issue by adding the button and by clicking  enter we can redirect to our main page

**Comment by MonalikaPatnaik** [comment]
Hey..I think the show password icon is there but it is not responsive for smaller screens..have assigned this issue to #123
