### ISSUE TITLE
Non-Functional Navbar Options on Blog Page

### ISSUE THREAD

**Issue by KumariShaliniDwivedi** [MonalikaPatnaik/UMatter#275]
https://github.com/MonalikaPatnaik/UMatter/assets/132951829/650669e2-b666-4573-9828-51bf10e7b77a

When selecting the 'Blog' option in the navbar on the website, the page redirects to a blog page successfully. The problem is that the options on the navbar(the blog page retains the same nav bar as the original site) of the blog page are not functional, meaning they do not navigate to their respective pages or sections as intended.

https://github.com/MonalikaPatnaik/UMatter/assets/132951829/210e19d5-3f8b-41b8-bc1a-bd3f64d758e9

**Comment by MonalikaPatnaik** [comment]
Heyy @KumariShaliniDwivedi..thanks for the issue!

**Comment by MonalikaPatnaik** [comment]
I think it's been done!
