### ISSUE TITLE
Fixing the contents of Sign in page

### ISSUE THREAD

**Issue by surbhi400** [MonalikaPatnaik/UMatter#28]
The contents of sign in page are not properly alligned. I will fix it. Please assign it to me under GSSoC'23.
![Screenshot 2023-05-20 094829](https://github.com/MonalikaPatnaik/UMatter/assets/77582783/0dc40211-76ab-4e6e-af25-f7f089270db0)

**Comment by Shrejal123** [comment]
Yeah, the content and UI of signed in page are not looking good. I wiil fix it. Could you please assign it to me?

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by abcxyz31** [comment]
i want to conribute

**Comment by ParthMadhvani2** [comment]
Yeah, the content and UI of the signed-in page are not looking good. I will fix it. Could you please assign it to me? I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by MonalikaPatnaik** [comment]
> The contents of sign in page are not properly alligned. I will fix it. Please assign it to me under GSSoC'23. ![Screenshot 2023-05-20 094829](https://user-images.githubusercontent.com/77582783/239667187-0dc40211-76ab-4e6e-af25-f7f089270db0.png)

Hey..I think it's been resolved now!
