### ISSUE TITLE
Verify OTP button ui improvement

### ISSUE THREAD

**Issue by SubhamB2003** [MonalikaPatnaik/UMatter#285]
Hey, I want to change the forgot password button UI. 
Can please assign it to me under GSSOC23

Here is the current button UI.
![image](https://github.com/MonalikaPatnaik/UMatter/assets/94003231/16779562-2e60-4bf2-8341-b779d1532f25)

**Comment by MonalikaPatnaik** [comment]
Yes yes you can work on this!
Pls submit your PR soon!
