### ISSUE TITLE
Fix eye button of SignIn page in correct place 

### ISSUE THREAD

**Issue by Anshul02092003** [MonalikaPatnaik/UMatter#286]
<img width="960" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/96529476/d6a0a9a8-488d-4466-8b9b-c435a7a27114">

As we can see the eye button which the user uses to see the password is not in the correct place.

Where to place the eye button then ?
-Where we are taking password as an input there the button should be placed align-right

**Comment by Anshul02092003** [comment]
I would like to work on this issue under GSSoC'23. Please assign me this issue.

**Comment by MonalikaPatnaik** [comment]
It's been already resolved..
Thanks!
