### ISSUE TITLE
Redesign of Login Page

### ISSUE THREAD

**Issue by SpandanM110** [MonalikaPatnaik/UMatter#290]
I am interested in redesigning the login page for UMatter please assign this to me.
Thank You!
Regards Spandan Mukherjee | Contributor

**Comment by ParthMadhvani2** [comment]
I am interested in redesigning the login page and making it more attractive please assign this to me. GSSoC'23 contributor

**Comment by MonalikaPatnaik** [comment]
Hey..similar issue is already been assigned!
Pls assign you if needed improvemnts!
