### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by shraddha761** [MonalikaPatnaik/UMatter#291]
![Screenshot 2023-05-21 160801](https://github.com/MonalikaPatnaik/UMatter/assets/106100728/509b4697-99a4-43eb-a485-71f314c9f415)

Adding this badges to readme makes it more attractive assign me this issue under GSSOC'23 label

**Comment by ParthMadhvani2** [comment]
hey, the readme is not written in a proper way. Assign this task to me I would make it more attractive and informative. GSSoC'23 contributer
