### ISSUE TITLE
[GSSOC'23]Adding Search Bar in Blogs Section

### ISSUE THREAD

**Issue by Enhancer18** [MonalikaPatnaik/UMatter#292]
Build a comprehensive library of articles, videos, and resources related to overcoming bad habits. Categorize content by topics and provide a search function for easy navigation. Consider curating content from experts or allowing users to submit their own content.

**Comment by MonalikaPatnaik** [comment]
Hey..I think the blogs page is doing the same..You can add more resources or add a search function in the blog page maybe?
just tell me what you like to do?

**Comment by krishna062** [comment]
@MonalikaPatnaik I would like to contribute to this task. Can you assign me this issue?

**Comment by Enhancer18** [comment]
> Hey..I think the blogs page is doing the same..You can add more resources or add a search function in the blog page maybe?
> just tell me what you like to do?

I would like to align the sign up button on the navigation bar and add a search button to the blog page

**Comment by MonalikaPatnaik** [comment]
> > Hey..I think the blogs page is doing the same..You can add more resources or add a search function in the blog page maybe?
> > just tell me what you like to do?
> 
> I would like to align the sign up button with sign in button on the navigation bar and add a search button to the blog page

Umm don't do changes in navbar as of now..you can add a search bar in blogs page!
Thankyou..

**Comment by Enhancer18** [comment]
#418 i have pulled a request for this issue @MonalikaPatnaik
