### ISSUE TITLE
[GSSoC'23] Adding CSS to Signin Form

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [MonalikaPatnaik/UMatter#293]
The CSS for the form needs to be improved.
The eye button for the password input is misplaced

The design is not responsive to screen-size changes. It is made only for PC screen but the design breaks when viewed on a smaller device.

I would like to fix the page and make the onboarding easier for the user

**Comment by MonalikaPatnaik** [comment]
Okay, so the eye button is fixed now..you can add CSS to the sign in form...
Go ahead and submit your PR soon!
Thanks!

**Comment by MonalikaPatnaik** [comment]
Hey @rishabhchaudhary0210 are u working on this?

**Comment by rishabhchaudhary0210** [comment]
Good morning @MonalikaPatnaik I will be working on it today and will issue the PR today itself

**Comment by rishabhchaudhary0210** [comment]
Hi! @MonalikaPatnaik 
I've redesigned the sign-in form and also issued a PR #401. Please review it and let me know if there's anything else.
Also if you like it I could do a similar job for the sign-up page too. If yes, do tell assign me the job.
Thanx. Happy Coding!
Here's how it looks now
![image](https://github.com/MonalikaPatnaik/UMatter/assets/97378312/b0f0982f-5ebf-4da5-ae14-451b6d3460f4)

**Comment by MonalikaPatnaik** [comment]
Looks good...left a review on your PR
