### ISSUE TITLE
[GSSoC'23] Wrong redirection on the logo Link

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [MonalikaPatnaik/UMatter#294]
On clicking the logo UMatter on the Home Page redirects it to the 404 page.

I would like to fix the issue by redirecting it to the correct page.

**Comment by SALONI-AGGARWAL0304** [comment]
I would like to work upon this issue , as I had already made some websites and had done that work .Please assign this issue to me under GSSoC'23
