### ISSUE TITLE
Responsiveness of Website of small screen needed.

### ISSUE THREAD

**Issue by urz-ahmed** [MonalikaPatnaik/UMatter#295]
Hello Project Maintainer,
I hope you're well. I am impressed by your repo.
I came to know about that your site is unresponsive.
![Screenshot 2023-05-23 170033](https://github.com/MonalikaPatnaik/UMatter/assets/106316083/17bec1c6-83b8-4109-81d8-58034635d5f5)

I can correct with few lines.
Please assign me this issue under gssoc'23

**Comment by MonalikaPatnaik** [comment]
Hey..similar issue is already been assigned!
