### ISSUE TITLE
Responsive layout design

### ISSUE THREAD

**Issue by SONA-1111** [MonalikaPatnaik/UMatter#30]
I would like to work on this issue. Please assign it to me.
(OUR SERVICES is not visible
![respon](https://github.com/MonalikaPatnaik/UMatter/assets/114572821/7a5d3178-64a4-4fc5-ba09-e225a98f6411)

**Comment by Shrejal123** [comment]
I am interested in working on the issue. Could you please aasign it to me?

**Comment by abhi03ruchi** [comment]
I would like to improve the responsiveness of this section of the webpage. Please assign this task to me. I am well-versed in react js , html, css and javascript.

**Comment by Charan2437** [comment]
Can you assign me this issue??

**Comment by Dimple-01** [comment]
I want to work on this issue.
I will fix this within few hours.
Please this work to me.

**Comment by tusharv01** [comment]
HEY I WANT TO WORK ON THIS ISSUE SO PLEASE ASSIGN ME AND PROMISE TO DO THIS WORK IN ONE DAY.
