### ISSUE TITLE
SigninElement component import missing

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#302]
SigninElement component not import https://github.com/MonalikaPatnaik/UMatter/blob/74e9e64c961dcea9a4336f44b38e9e3d190e3019/src/Components/Signin/index.js#L21

Mentors:

@Mansi168 @Mansi168 @i-am-SnehaChauhan

**Comment by nimeshpareek** [comment]
> SigninElement component not import
> 
> https://github.com/MonalikaPatnaik/UMatter/blob/74e9e64c961dcea9a4336f44b38e9e3d190e3019/src/Components/Signin/index.js#L21
> 
> Mentors:
> 
> @Mansi168 @Mansi168 @i-am-SnehaChauhan

I think signin is not missing, line numbers 21,22,23 and 25 are written twice. On my local machine, there is no error after removing those lines.

**Comment by shivam-sharma7** [comment]
🙏Requesting to mentors @Mansi168 @i-am-SnehaChauhan @MonalikaPatnaik please before merge any PR we need to make sure that changes is good and working fine if it is not then suggest changes to contributors related.

**Comment by Shikhar02347893** [comment]
@MonalikaPatnaik 
There are multiple issues in [UMatter/src/Components/Signin/index.js]
1)forgotPassword component is imported twice

2)NavLink component is imported twice


3)useState is imported twice

4)SigninElement component import missing

I would like to work on these issues . Kindly assign them to me.

**Comment by shivam-sharma7** [comment]
@nimeshpareek changes exist in project then it's bug okay

**Comment by shivam-sharma7** [comment]
> @MonalikaPatnaik There are multiple issues in [UMatter/src/Components/Signin/index.js] 1)forgotPassword component is imported twice
> 
> 2)NavLink component is imported twice
> 
> 3)useState is imported twice
> 
> 4)SigninElement component import missing
> 
> I would like to work on these issues . Kindly assign them to me.

Thanks :)

**Comment by MonalikaPatnaik** [comment]
Heyy..it's been resolved!
