### ISSUE TITLE
forgotPassword component import twice

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#303]
forgotPassword component import twice we need to remove one see, here-https://github.com/MonalikaPatnaik/UMatter/blob/74e9e64c961dcea9a4336f44b38e9e3d190e3019/src/Components/Signin/index.js#L18-L23

Mentors:

@Mansi168 @MonalikaPatnaik @i-am-SnehaChauhan

**Comment by Shikhar02347893** [comment]
@MonalikaPatnaik 
i am GSSOC'23 contributor 
i am interested in doing this 
so kindly assign me this

**Comment by shivam-sharma7** [comment]
@Shikhar02347893 no please look for another issues
