### ISSUE TITLE
[GSSOC'23] Toggling between dark and light mode correctly 

### ISSUE THREAD

**Issue by sharma21deepti** [MonalikaPatnaik/UMatter#306]
When we switch for the light mode from dark mode only the color of navbar changes but footer still remains the same.

**Comment by MonalikaPatnaik** [comment]
Heyy pls submit your PR soon otherwise will assign it to someone else!

**Comment by Shalini469717** [comment]
Can I work on this?

**Comment by MonalikaPatnaik** [comment]
Yes @Shalini469717 you can..
Submit your PR soon!

**Comment by Shalini469717** [comment]
seems like the issue is fixed
