### ISSUE TITLE
Fixing The About Section Its Not Reponsive

### ISSUE THREAD

**Issue by Mudassirkhan2** [MonalikaPatnaik/UMatter#31]
Fixing The About Section Its Not Reponsive Image Added Below.
![Screenshot 2023-05-20 102330](https://github.com/MonalikaPatnaik/UMatter/assets/106579572/9de90560-154f-402a-8bc2-6a638188b2ee)
I want to work on this issue under GSSOC 2023

**Comment by Mansi168** [comment]
@Mudassirkhan2 you are assigned!

**Comment by Mudassirkhan2** [comment]
@Mansi168  Label Of GS0C 2023 ?
