### ISSUE TITLE
Organize navbar spacing and adding functionality to signup and signin page

### ISSUE THREAD

**Issue by splusb** [MonalikaPatnaik/UMatter#311]
Hi, the navbar has too much spacing between signup and signin button, so it will be better if we fix that and also I would like to make the signup button with more styling like signin button. And clicking on signup and signin button it is not opening any page, I would like to make a change on that.
So please assign this issue to me under GSSOC'23

**Comment by splusb** [comment]
@MonalikaPatnaik Please let me know if you are interested in this issue

**Comment by MonalikaPatnaik** [comment]
Hiii.. lmk u would improve the navbar spacing in dekstop view or mobile view?

**Comment by MonalikaPatnaik** [comment]
I think in dekstop it is looking fine..but in mobile view there is no spacing in sign in, sign up buttons!

**Comment by splusb** [comment]
Ok, I will then try for mobile view
