### ISSUE TITLE
Can add more content to blogs page!

### ISSUE THREAD

**Issue by Shr-reny** [MonalikaPatnaik/UMatter#318]
We can add more useful articles and youtube links to the blogs page and make it more resourceful.

**Comment by MonalikaPatnaik** [comment]
What u will add?

**Comment by Shr-reny** [comment]
There are a few topics that can be added:
-Distraction techniques to avoid cravings
-Support groups can help you quit smoking
-The 5D's that would help with smoking cessation
-Few natural remedies to cope with nicotine withdrawal

**Comment by MonalikaPatnaik** [comment]
Sounds good...You can add it in the blogs page..
Thankyou!
I

**Comment by Shr-reny** [comment]
Thank you for assigning. I've added the blogs. Please check  PR #474.
