### ISSUE TITLE
Enhancing the Mobile Menu

### ISSUE THREAD

**Issue by shuddhi-jain** [MonalikaPatnaik/UMatter#32]
When the screen ratio is changed there is a navbar icon without functionality and the last dib also display settings are not auto-corrected when changed, I want to assign the footer elements into the nav bar with the auto-closing feature when the screen slides up or down. Can you assign me this issue to work on??

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by abhi03ruchi** [comment]
Hi @Mansi168, I would like to work on this issue and add responsiveness feature. I know HTML, CSS and javascript. And currently am working on react js. Plz, assign it to me.

**Comment by ritik48** [comment]
Hey @Mansi168 ,
Please let me do this work if it has not been assigned yet.

**Comment by Abhiramjampani** [comment]
Hi @Mansi168, I would like to work on this issue and add responsiveness feature. I know HTML, CSS ,javascript and react js. . Plz, assign it to me.

**Comment by shuddhi-jain** [comment]
Hi @Mansi168  to @shuddhi-jain , Please assign me this issue , so i can start working on it

**Comment by Mansi168** [comment]
hey @shuddhi-jain @lalitkumawat1m @ritik48 @abhi03ruchi @Abhiramjampani navbar related issues are already assigned..plz look for other issues.....if i need this in future, i will assign @shuddhi-jain as assigning is based on first come only :')

**Comment by shuddhi-jain** [comment]
Hey @Mansi168 but I raised this issue first and I think this issue should be assigned to me.
