### ISSUE TITLE
Footer section is not responsive according to mobile device!

### ISSUE THREAD

**Issue by Sonikm** [MonalikaPatnaik/UMatter#322]
![UMatter (1)](https://github.com/MonalikaPatnaik/UMatter/assets/117334722/078982ac-2121-4a83-8336-5741d824a3d0)

Please assign this issue to me. I would like to work on it.

**Comment by rahoolonly** [comment]
hey, kindly assign me this issue. I'm beginner to open source. I would to make footer responsive.
