### ISSUE TITLE
IMPROVE THE BLOG PAGE

### ISSUE THREAD

**Issue by karthiknadar1204** [MonalikaPatnaik/UMatter#324]
right now the blogs are just displayed and the videos are in a straight line which reduce the user engagement.
Proposed solution:
For the blogs, i was thinking of adding an animation effect to the blogs like only the heading of a particular blog will be visible, but when the user hovers over the blog, we could make the rest of the blog content visible to the user.
For the youtube videos, we can separate the videos into 2 sections, one for how to quit smoking and second is why quit smoking smoking. I propose these 2 separate sections because your 6 videos have 3 videos each contributing to these 2 topics.
Now for these 2 sections, I was thinking of Making the three videos of each section into a carousel like one carousel for the section of how to quit smoking and a second carousel for why quit smoking.
We can have these 2 sets of carousels contained in a separate div with a color that matches the tone of the website and add arrow buttons for the user to control them.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by shivam-sharma7** [comment]
see this #310 so close this for now

**Comment by MonalikaPatnaik** [comment]
Heyy @karthiknadar1204..sounds good to me..do one part..you can add animation to the blog cards as mentioned and submit your PR soon so that we can merge it without conflicts!

**Comment by karthiknadar1204** [comment]
Ok ,what about the videos,like after the blog,I'll submit a pr and following that should I continue working on the yt videos?

**Comment by karthiknadar1204** [comment]
Will try to submit pr for one part by day end @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
> Ok ,what about the videos,like after the blog,I'll submit a pr and following that should I continue working on the yt videos?

I guess someone is already working on that..as of now just do the blogs part..

**Comment by karthiknadar1204** [comment]
ok will do

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik I am done with the feature, sharing the preview in a few mins

**Comment by karthiknadar1204** [comment]
https://github.com/MonalikaPatnaik/UMatter/assets/95973644/a778dedb-4926-483b-ab7f-da857fda7472

**Comment by karthiknadar1204** [comment]
How does it look, should i submit a pr for the same

**Comment by MonalikaPatnaik** [comment]
> How does it look, should i submit a pr for the same @MonalikaPatnaik

Umm not looking good to me..Look at this once-- https://www.loom.com/share/989860c2f0e84169aeeab97e0b71b73b
Also, I see the navbar has not been changed..sync your branch then make a PR..remember to make a separate branch

**Comment by karthiknadar1204** [comment]
I have added a small margin as the blog content was getting hidden behind the navbar

**Comment by karthiknadar1204** [comment]
I'll try to implement the hover animation shown in the link @MonalikaPatnaik

**Comment by karthiknadar1204** [comment]
I am unable to increase the size of the images, dues to their uneven height originally, increasing their height makes it look miserable.
This is the hover animation i have narrowed down 

https://github.com/MonalikaPatnaik/UMatter/assets/95973644/e7605182-c7a3-4742-899d-0c7f8d3c3e20





, I am assuming we have another link we will be redirected to on clicking the blog card, so we could add a read more button, so like in the previous animation i had sent, i can add the button which will appear when hovering the card along with the paragraph and after the user reads the context of the blog, he can choose to click the button or not, something like this:


https://github.com/MonalikaPatnaik/UMatter/assets/95973644/d662403c-1c13-4e9f-9b31-c6dbb26f5d3b

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik Please share your opinion

**Comment by MonalikaPatnaik** [comment]
> I am unable to increase the size of the images, dues to their uneven height originally, increasing their height makes it look miserable. This is the hover animation i have narrowed down
> 
>  monalika.mp4 
> , I am assuming we have another link we will be redirected to on clicking the blog card, so we could add a read more button, so like in the previous animation i had sent, i can add the button which will appear when hovering the card along with the paragraph and after the user reads the context of the blog, he can choose to click the button or not, something like this:
> 
>  240043176-727d8fa0-1311-4f73-9370-587b97b93223.mp4

Yes..looks fine..you can add a button like "Read more" along with the text!

**Comment by karthiknadar1204** [comment]
i'll submit a pr, is that fine for the second layout @Mansi168

**Comment by MonalikaPatnaik** [comment]
> i'll submit a pr, is that fine for the second layout @Mansi168

Okay!

**Comment by Piyusharora2003** [comment]
Wouldn't it be better in layout 2 if instead of having all the rows displaced due to the effect, we ensure that only one row is affected? 
and would give some effects like this 
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_image_grid

**Comment by karthiknadar1204** [comment]
please asssign a label as in a level to this issue under gssoc
Just a reminder in case missed it @MonalikaPatnaik
