### ISSUE TITLE
Improve Website Appearance: Pop-up for welcoming, Add more text, Font color, and Background Updates

### ISSUE THREAD

**Issue by kalyan123s** [MonalikaPatnaik/UMatter#326]

**Comment by kalyan123s** [comment]
Hii, could you please assaign me this issue to beautify your website for better user experience?

**Comment by MonalikaPatnaik** [comment]
Do you want to add more text to the homepage..if yes then what r u adding? I think homepage text should be minimal..isn't it?
do u think pop up for welcoming is a good user exp?

**Comment by kalyan123s** [comment]
Yes, the home page should be simple but must be attractive for better UX.
If I am a user of this website, then I might not want to use it as it doesn't look attractive that much, because after all websites are all about attractiveness and how good is user experience.
and also the services and contact section can be improved style-wise.
In the phone size screen "About us" image goes down and the text remains above, that should be interchanged.
This "About us"  image should contain a link that redirects to text
Yes, you are right, pop-ups might be an irritating thing. So, I will...
Update fonts and text across the website for improved readability and consistency for better UX.

**Comment by MonalikaPatnaik** [comment]
Okay..you can fix the alignment of about us page in mobile view..
I think font is looking good..Do u have any better font style in your mind? If yes, share ss!
someone is already working on services & contact us page..you can raise separate issues reg that!
