### ISSUE TITLE
Dark Mode, Link Colors, Active Link, and Sign-In Button Improvements

### ISSUE THREAD

**Issue by manaver** [MonalikaPatnaik/UMatter#328]
The website requires several enhancements to improve the overall user experience and visual aesthetics. The following issues have been identified:

1. Dark Mode Inconsistency:
The dark mode feature is only functioning properly in the navbar, but it should be extended to other sections of the website as well. Ensure that the dark mode theme is applied consistently throughout all pages.

2. Link Colors and Animation:
The current link colors lack visual appeal and may not provide enough contrast against the background. Consider improving the link colors to enhance readability. Additionally, introduce a subtle animation effect, such as color transition or underline, to indicate interactivity when hovering over the links.

3. Active Link Highlight:
When navigating through the website, it's important to visually highlight the active link to provide clear feedback to the user. Implement a distinct visual cue, such as a different color or underline, to indicate the currently active page or section.

4. Sign-In Button Improvement:
The design of the sign-in button needs enhancement. It should be visually appealing and easily noticeable. Consider using a different color, style, or placement to make it stand out and encourage users to sign in.

### Proposed Solution:
To address these issues and improve the website:

1. Extend the dark mode feature to all sections of the website, ensuring consistency across pages.

2. Improve the link colors to enhance readability and introduce a subtle animation effect to indicate interactivity.

3. Implement a visual cue to highlight the active link, such as a different color or underline, to provide clear feedback to users.

4. Enhance the design of the sign-in button to make it visually appealing and encourage user engagement.

**Comment by manaver** [comment]
Please Assign this issue to me

**Comment by MonalikaPatnaik** [comment]
Hey @manaver, you can work on the Active Link Highlight in the Navbar!

**Comment by manaver** [comment]
Thanks @MonalikaPatnaik for assigning me this issue.  I will start working on this issue 😀

**Comment by manaver** [comment]
Hi @MonalikaPatnaik , u haven't assign this issue to me yet

**Comment by manaver** [comment]
hi @MonalikaPatnaik  i have a question do i have to work only on Active Link Highlight in the Navbar? or I can work on other issues as well?

**Comment by MonalikaPatnaik** [comment]
Heyy for now just work on the active link highlight bcoz it's not been fixed yet..rest is already assigned to someone else!
