### ISSUE TITLE
Arrange the social media icons in footer to center.

### ISSUE THREAD

**Issue by vikasjain2003** [MonalikaPatnaik/UMatter#329]
### About issue 
The social media icons in the footer are not centered align

### Solution
I will align the icons to the center. 

# Please assign this issue to me under GSSOC 23.

**Comment by MonalikaPatnaik** [comment]
Sure @vikasjain2003 ..go ahead..pls submit your PR by today itself so that we can merge it without conflicts!

**Comment by vikasjain2003** [comment]
Sure Monalika, I will do it by today itself.
Thanks & Regards

**Comment by MonalikaPatnaik** [comment]
Hey..what's the status?

**Comment by nehabulakhe** [comment]
@MonalikaPatnaik I want to contribute in this could you please assign this issue to me

**Comment by MonalikaPatnaik** [comment]
Hey @vikasjain2003 let me know do u want to work on this issue?

**Comment by vikasjain2003** [comment]
Hey @MonalikaPatnaik/UMatter
***@***.***> please
assign this issue to someone else as I am having facing some problems
regarding the solution of this issue.

**Comment by MonalikaPatnaik** [comment]
@nehabulakhe would u like to work on this?
