### ISSUE TITLE
"Check the Website link" in Readme is not working 

### ISSUE THREAD

**Issue by KashiwalHarsh** [MonalikaPatnaik/UMatter#33]
I want to fix the readme file under GSSoC'23 please assign it to me

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Akanksha038** [comment]
Hello @MonalikaPatnaik Ma'am,
I would like to add working website link. Please assign me this issue. I would like to work on this issue under GSSOC'23. Please let me fix this issue #33.
