### ISSUE TITLE
Images are not related to Smoking and Alcohol

### ISSUE THREAD

**Issue by vikasjain2003** [MonalikaPatnaik/UMatter#331]
# Issue
The images used in the website are not related to alcohol and smoking which makes UI a little out performing

# Solution
I will add new images related to quitting smoking habits and awareness.

# Please assign this issue to me under GSSOC 23

**Comment by khushiminda** [comment]
I CAN ADD NEWW AETHETICS TO YOUR PAGE AS A CONTENT CREATOR!

**Comment by MonalikaPatnaik** [comment]
> # Issue
> The images used in the website are not related to alcohol and smoking which makes UI a little out performing
> 
> # Solution
> I will add new images related to quitting smoking habits and awareness.
> 
> # Please assign this issue to me under GSSOC 23

May i know where would you add these images?

**Comment by MonalikaPatnaik** [comment]
Hey @vikasjain2003...you can add different images in the blog page related to the topic!
lmk if u can work on this??..
