### ISSUE TITLE
[issue] The navigation bar of the site is not proper align with the website 

### ISSUE THREAD

**Issue by chetankhandait** [MonalikaPatnaik/UMatter#332]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/121539090/07fb4fcc-cb84-433a-a57c-b15bf1126ce3)
please assign me this work and work under the GSSOC23

**Comment by utkarshgupta04092003** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.
Kindly provide me the opportunity to work on the issue.
