### ISSUE TITLE
Add jump to top button 

### ISSUE THREAD

**Issue by heyhimansh** [MonalikaPatnaik/UMatter#333]
Hey @MonalikaPatnaik , I want to add jump to top button to your web application .
![Issues · MonalikaPatnaik_UMatter - Brave 24-05-2023 19_31_16 (2)](https://github.com/MonalikaPatnaik/UMatter/assets/72097380/9c4b5a3d-11b5-48c7-ae39-88444d1d0a26)

I add this above the chat button at the bottom. with similar design.
I hope these suggestions help you in your web design improvements. Assign this issue to me under gssoc2023.

**Comment by MonalikaPatnaik** [comment]
Hey..similar issue is already been assigned!
