### ISSUE TITLE
Animation of cards in "Our Service Section" . [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [MonalikaPatnaik/UMatter#336]
animation is not properly done , it looks very simple.
I would like to add some animations to it to make it impressive, If this is required do assign it to me under GSSOC 2023,
changes will be done in no time !
:)

**Comment by MonalikaPatnaik** [comment]
Hey @ManishaSwain8 can u add hover effects in services cards?

**Comment by MonalikaPatnaik** [comment]
@ManishaSwain8 ?

**Comment by ManishaSwain8** [comment]
yeah sure no problem !

**Comment by MonalikaPatnaik** [comment]
I think framer motion is already added to the services section..you can add a smooth hover effect on services cards!
Thankyou..

**Comment by ManishaSwain8** [comment]
ohhk ...!

**Comment by ManishaSwain8** [comment]
hello @MonalikaPatnaik  there are some existing error in code base...ss below
![Screenshot (62)](https://github.com/MonalikaPatnaik/UMatter/assets/96622693/6f8a067d-4864-4935-b6d1-00c7bce6bca2)

**Comment by MonalikaPatnaik** [comment]
Hey could u do git pull origin main

**Comment by ManishaSwain8** [comment]
i just forked it this is the recent one

**Comment by ManishaSwain8** [comment]
![Screenshot (63)](https://github.com/MonalikaPatnaik/UMatter/assets/96622693/b5fff44d-d3e1-4ab6-a2cb-e205f74a7ff3)
![Screenshot (61)](https://github.com/MonalikaPatnaik/UMatter/assets/96622693/b96b9483-5b6f-45f3-a2bc-9c1b95e5fcda)
![Screenshot (62)](https://github.com/MonalikaPatnaik/UMatter/assets/96622693/5343ca06-f616-45d1-a6c6-343472ce58a5)

**Comment by MonalikaPatnaik** [comment]
Okay lemme check!

**Comment by ManishaSwain8** [comment]
Yup !

**Comment by MonalikaPatnaik** [comment]
Hey pull now and check!

**Comment by ManishaSwain8** [comment]
okk

**Comment by ManishaSwain8** [comment]
https://github.com/MonalikaPatnaik/UMatter/assets/96622693/4b74abc2-8aa1-48ef-bd88-3c2ebb7f7406

how about this @MonalikaPatnaik

**Comment by ManishaSwain8** [comment]
@MonalikaPatnaik  there are some existing error in recent pull ,do check it out .  : |)
