### ISSUE TITLE
Add: horizontal line in footer title

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#339]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/5bf5344e-6669-4d77-8921-10c62b5271d7)

**Comment by shivam-sharma7** [comment]
@Manice18 @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
I think green hr line will look good!
You are good to go!

**Comment by shivam-sharma7** [comment]
someone is also workis for this @Kalyan-velu okay If he has done then will see what should we can change
