### ISSUE TITLE
Changes Required in Footer Section

### ISSUE THREAD

**Issue by Gaurang1602** [MonalikaPatnaik/UMatter#34]
Your Footer Section doesn't show difference between Heading and links (both have same Text Size ) and also your social media handles are not connected to social links if you want to link it , I can link them other I will remove Hyperlink

![Footer_improved](https://github.com/MonalikaPatnaik/UMatter/assets/99584477/4ad29b94-ba4d-4e49-93cc-b80a5522507b)

I can Improve footer like the image below

![Footer_After _changes](https://github.com/MonalikaPatnaik/UMatter/assets/99584477/017d4dc3-1960-49ef-8aa2-2ec5c28ff3d5)

**Comment by Gaurang1602** [comment]
Please Assign This issue to me

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by ShifaKhan-24** [comment]
@MonalikaPatnaik  I want to contribute to this issue. The changes I will make are as follows:-

1. Improve alignments of footer components (eg. social media handles and copyright section are in the same line)
2. Improve the design (something like this 👉)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/94692552/91b646be-61db-464e-a126-58e2868f122f)
3. Add respective links to social icons.
4. Responsive footer section ( apart from the above three, I can also try working on this)

Request you to assign me this issue!

**Comment by Gaurang1602** [comment]
This issue is opened by me , so please let me work on it , please open your own issues.

**Comment by MonalikaPatnaik** [comment]
Hey @Gaurang1602 i think the footer has been fixed..and we are not having social links as of now!
