### ISSUE TITLE
Change the style of the card used in the blog page 

### ISSUE THREAD

**Issue by SaiyamTuteja** [MonalikaPatnaik/UMatter#340]
As the card in the blog page is not that much eye catches instead of normal card i can give the appealing effect to the card portion in the blog page by hovering on the image the text will be displayed which will give the better response as this website is based on awareness of people if the user interface is eye catches then it will gather more crowd .
I want to work on this issue as the **GSSOC23** contributor  
[recording-2023-05-24-20-18-00.webm](https://github.com/MonalikaPatnaik/UMatter/assets/119167105/42b41d84-02e8-4f26-bacc-15f8be15e163)
**This video and image reflects the change in the blog page or some other card design** 
![Screenshot (107)](https://github.com/MonalikaPatnaik/UMatter/assets/119167105/1a1c189b-eab9-4d56-9c63-75a046a38cfe)

**Comment by MonalikaPatnaik** [comment]
Umm..Could you change it something like this.. Tell me if u are able to do this??
https://www.loom.com/share/989860c2f0e84169aeeab97e0b71b73b

**Comment by SaiyamTuteja** [comment]
**YES** I can make this for you

**Comment by MonalikaPatnaik** [comment]
Okay....then pls do it!
Thanks for Contributing!
