### ISSUE TITLE
Adding website's icon to the navbar and a feedback section for users to share their growth .

### ISSUE THREAD

**Issue by Akanksha-202** [MonalikaPatnaik/UMatter#341]
1. For styling the website, add the icons of Umatter to the navbar along the name "Umatter".
2. Adding another section in navbar ass feedback, for users to connect more and share their growth in the process of quitting bad habits.

Please assign this issue to me under GSSoC'23 label :)

**Comment by MonalikaPatnaik** [comment]
Hey @Akanksha-202 the logo has been added to the navbar..you can add the feedback Section in Navbar and make a separate component for it!
Will add level label in accordance to your work!

**Comment by Akanksha-202** [comment]
Hey @MonalikaPatnaik I have done the work but have some doubts about the dark theme, can we connect over discord or any platform to resolve that?
The coding part is done, from taking feedbacks to displaying it as testimonials on homepage. 
I'm having problem regarding styles.
