### ISSUE TITLE
Want to create the signup form for the website 

### ISSUE THREAD

**Issue by SaiyamTuteja** [MonalikaPatnaik/UMatter#342]
**Signup page plays a vital role in the website** 
As i have seen that there is the signup button in nav bar but there is no signup page only the sign in button is working .If new user want to signup in the website where he /she can signup to further access to the website i can make the signup page for the website which is user friendly as well as attractive design 
I want to contribute on this project on this issue as i am the **GSSOC23** contributor 
![Screenshot (108)](https://github.com/MonalikaPatnaik/UMatter/assets/119167105/c8d99a79-fffd-4427-b685-86d35d8364c0)

**Comment by MonalikaPatnaik** [comment]
It's been done!
