### ISSUE TITLE
Started UMatter Github Discussions!

### ISSUE THREAD

**Issue by MonalikaPatnaik** [MonalikaPatnaik/UMatter#344]
Head over to [discussions ](https://github.com/MonalikaPatnaik/UMatter/discussions)to connect with other fellow contributors, ask any questions or doubts you may have, and have some open-source tech talks!

**Comment by KumariShaliniDwivedi** [comment]
I create many of the issues but why are you not assign me ...

**Comment by Vidip-Ghosh** [comment]
Issues have not yet been assigned.

**Comment by MonalikaPatnaik** [comment]
Please have some patience!

**Comment by KumariShaliniDwivedi** [comment]
okk

**Comment by Piyusharora2003** [comment]
can you help me . i could not understand that my changes were rejected or not and if not how would i came to know of it . what are checks in vercel ..

**Comment by MonalikaPatnaik** [comment]
> can you help me . i could not understand that my changes were rejected or not and if not how would i came to know of it . what are checks in vercel ..

Don't worry! Ignore that!
