### ISSUE TITLE
want to add sign up or registration page

### ISSUE THREAD

**Issue by Abhiramjampani** [MonalikaPatnaik/UMatter#348]
hey @Mansi168 @MonalikaPatnaik @i-am-SnehaChauhan i want to add sign up or registration page beside sign in page
please assign this issue to me

**Comment by aniketnimkar** [comment]
Please assign me this issue under GSSoC-2023 i love to contribute to this issue.

**Comment by MonalikaPatnaik** [comment]
Hey it's been done!
