### ISSUE TITLE
Improve Footer Headings and Padding

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [MonalikaPatnaik/UMatter#35]
@MonalikaPatnaik, As I am a gssoc'2023 contributor please assign this issue to me
![umatter](https://github.com/MonalikaPatnaik/UMatter/assets/125626654/6a229f9f-e08b-4b99-8158-a8117323f025)
Above the Screenshot, you can see that the( About Us, Contact Us, Videos and Social Media) fonts are the same as the other texts which is bad UX as it also looks like a redirecting link and the bottom padding is not good.

**Comment by Aditi323** [comment]
I would like to work on this project. Please assign it to me.

**Comment by purviporwal0** [comment]
can you pls assign this to me

**Comment by Shrejal123** [comment]
@MonalikaPatnaik I would like to work on footer part and make responsive  please assign it to me .

**Comment by Samriddhi15** [comment]
The current footer section requires attention to improve the headings and padding. By making adjustments to the CSS styles, we can achieve a more visually appealing and balanced layout. Please assign this issue to me , I can make it more user-friendly.

**Comment by babitarit** [comment]
i would like to work on it could you please assign me

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by anupdhoble** [comment]
I know how to fix this , So would like to work on this project. Please assign it to me under GSSOC'23 @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Heyy all...pls check the current footer...I think it's been done!

**Comment by MOHDNEHALKHAN** [comment]
Ok Closing this issue 👍
