### ISSUE TITLE
Enhance: UI of blog page. 

### ISSUE THREAD

**Issue by Pragati-3003** [MonalikaPatnaik/UMatter#351]
I would like to change the UI of the blog page to make it more attractive. 
I would like to change the background color and box -shadow of the cards also I would like to rearrange all the vedios. 
So, please assign this issue to me.

**Comment by i-am-SnehaChauhan** [comment]
Hey @Pragati-3003 ,
This issue is similar to #324 
Please msg there.
Thanks:)
