### ISSUE TITLE
Need to fix the home page of application

### ISSUE THREAD

**Issue by VivekRaj212** [MonalikaPatnaik/UMatter#353]
Issue: On loading application on browser first time, it is display error page. 
Solution: Need to change in routing and actually display home page
![Screenshot (763)](https://github.com/MonalikaPatnaik/UMatter/assets/98600965/91ba4e8e-9fad-46c3-bc80-308169a0cb67)
![Screenshot (764)](https://github.com/MonalikaPatnaik/UMatter/assets/98600965/f7a09544-5799-4e07-98cb-5cc0bc3f9056)

@MonalikaPatnaik assign this issue to me, I will fix it under gssoc23

**Comment by MonalikaPatnaik** [comment]
It's been done!
