### ISSUE TITLE
Responsiveness issue in smaller devices

### ISSUE THREAD

**Issue by Vidip-Ghosh** [MonalikaPatnaik/UMatter#357]
In blog page, I found that the heading (Immerse Yourself in a Comprehensive........) disappears when the size of the screen shrinks. Also some overflow issues also. I would like to enhance the blog page for smaller devices. 

Please assign this to be under GSSOC'23.

Laptop Screen
<img width="1680" alt="Screenshot 2023-05-25 at 18 06 41" src="https://github.com/MonalikaPatnaik/UMatter/assets/91741581/05de5b54-e768-4abd-be69-13eb5612bd29">

Mobile Screen
<img width="200" alt="Screenshot 2023-05-25 at 18 07 14" src="https://github.com/MonalikaPatnaik/UMatter/assets/91741581/c657ec02-6cd7-4c1e-9a03-082e3a0b88e8">

<img width="202" alt="Screenshot 2023-05-25 at 18 23 35" src="https://github.com/MonalikaPatnaik/UMatter/assets/91741581/3b4d60f3-d563-4467-bd6f-ba6590f418d0">

**Comment by Vidip-Ghosh** [comment]
@MonalikaPatnaik @Mansi168 please assign this issue.

**Comment by MonalikaPatnaik** [comment]
Hey..do it and pls submit your Pr soon so that we can merge it without conflicts!

**Comment by nehabulakhe** [comment]
@MonalikaPatnaik assign this issue to me

**Comment by MonalikaPatnaik** [comment]
Hey hey are u working on it??

**Comment by Vidip-Ghosh** [comment]
Actually, while I was resolving merge conflicts, I've lost the changes I made. 
So, I couldn't work.

**Comment by MonalikaPatnaik** [comment]
Heyy..it's okay..
