### ISSUE TITLE
SignUp page to Home Page Routing

### ISSUE THREAD

**Issue by Vidip-Ghosh** [MonalikaPatnaik/UMatter#359]
I found that Whenever Sign Up to Home Page Routing is not proper. It redirects to Error 404 page. 
Please assign this issue under GSSoC'23 Contributor. 

https://github.com/MonalikaPatnaik/UMatter/assets/91741581/63210e1a-754f-44fe-b04d-707aad4e6bbe

**Comment by Vidip-Ghosh** [comment]
@MonalikaPatnaik @Mansi168 Please assign this issue

**Comment by MonalikaPatnaik** [comment]
Hey..navbar will be added to the sign up page..and it is already assigned to someone else!
