### ISSUE TITLE
Add Correct Link to Footer Logo [GSSOC'23]

### ISSUE THREAD

**Issue by vishnu9865** [MonalikaPatnaik/UMatter#36]
# Incorrect Link in Footer Logo

 - The Footer logo incorrectly redirect to 'https://monalikapatnaik.github.io/' which has a blank page. 
 - I would like to correct and style the bottom logo at the same time. 
 - Further details are given as pics below.

@MonalikaPatnaik , please do assign this issue to me so I can solve it.
Thank you in advance !!

## Corect Link
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91585213/f24761d0-a499-4b00-8b42-18d2d6ff653b)
## Incorrect Link
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91585213/c1e139a7-0518-4621-b819-5eabf5dad1b3)
## Footer Logo
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91585213/642148ce-6c98-49e3-bfc4-ca93dede9f69)

**Comment by vishnu9865** [comment]
@MonalikaPatnaik Please assign this issue to me. Thanks 👍🏽😊

**Comment by vishnu9865** [comment]
@Mansi168 Ma'am, Can you this issue to me so I can put a PR? Thanks in Advance. 👍🏽

**Comment by Mansi168** [comment]
you are assigned!
