### ISSUE TITLE
Fix: Sign Up Page layout 

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#361]
We need to fix Sign Up page layout like Sign In you can see current behaviour of Sign Up page

![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/19245b51-3774-45a1-931b-168ad2e3a450)

**Comment by Atharvasharma12** [comment]
Please assign this task to me.
I am a contributer of GSSoC'23.

**Comment by shivam-sharma7** [comment]
@Atharvasharma12 look for another

**Comment by MonalikaPatnaik** [comment]
Okay @shivam-sharma7 just fix the layout and alignment!

**Comment by MonalikaPatnaik** [comment]
Heyy @shivam-sharma7 is it done?
