### ISSUE TITLE
Adding hover effect to chat with us button 

### ISSUE THREAD

**Issue by Prajwal0225** [MonalikaPatnaik/UMatter#366]
**Feature idea.**

I would like to request the addition of a hover effect to the "Chat with us" button to enhance its interactivity. Currently, when the user hovers over the button, there is no visual feedback to indicate that it can be interacted with. By adding a hover effect, such as change or animation, we can provide a clear visual cue to the user that the button is interactive and encourage engagement.

**Expected Behavior**:
When the user hovers over the "Chat with us" button, it should exhibit a visually distinct effect
![chat bot](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/b3b0ddaf-422a-44f3-8036-c25a9222fe70)

I would like to work on this issue as the GSSOC'23, could you please assign this to me.

**Comment by Atharvasharma12** [comment]
Please assign this task to me i can include this enhancement.
I am a contributer of GSSoC'23.
