### ISSUE TITLE
Adding Footer to Signup Page

### ISSUE THREAD

**Issue by Prajwal0225** [MonalikaPatnaik/UMatter#367]
**Describe the bug**

Currently, the navigation bar is displaying two "Sign Up" buttons, which can potentially confuse the user. This duplication of the button creates an unnecessary redundancy and may lead to user confusion or frustration.

**Expected Behavior:**
The navigation bar should display only one "Sign Up" button to avoid confusion and provide a clear call-to-action for the user.

**Screenshort**
![nvbar](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/90f7a990-5e8a-471c-9aec-7cda414470c5)

 

I would love to contribute to this wonderful project, so could you please assign this issue to me?

**Comment by MonalikaPatnaik** [comment]
Heyy @Prajwal0225 Can you add footer to signup page?

**Comment by Prajwal0225** [comment]
Yaa! I can do that.

**Comment by MonalikaPatnaik** [comment]
Okay, then pls do it!
Thankyou!

**Comment by MonalikaPatnaik** [comment]
heyy pls do it sooon!

**Comment by Prajwal0225** [comment]
I will try to done it by tomorrow ...
