### ISSUE TITLE
To adjust the sign up button [GSsoc'23]

### ISSUE THREAD

**Issue by Yashika-Agrawal** [MonalikaPatnaik/UMatter#368]
**Describe the bug**
I want to adjust the sign up button in the middle of the navbar and also sign up button side by side to the sign in button.

**Screenshot**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/97408966/ca604285-e68d-4273-a8f5-18e3a7095061)

**Comment by Yashika-Agrawal** [comment]
Hey @MonalikaPatnaik , i would like to work on this issue under GSsoc'23 contribution , please assign me this issue to adjust it.

**Comment by Atharvasharma12** [comment]
Please assign me under GSSOC..
