### ISSUE TITLE
visitor counter

### ISSUE THREAD

**Issue by singh-anushka** [MonalikaPatnaik/UMatter#371]
**Feature idea.**

By using PHP I want to create a visitor counter for the repository. @MonalikaPatnaik can you please assign me this issue under GSSOC23, with a level 3 badge; this involves coding in PHP, so it takes time to do so. Thank you

**Comment by singh-anushka** [comment]
@MonalikaPatnaik please assign me this issue.

**Comment by MonalikaPatnaik** [comment]
Hey..you can work on this!
Will add level labels soon according to the work! so, just don't worry
Thanks!

**Comment by MonalikaPatnaik** [comment]
Also, suggesting you to submit your PRs soon as multiple issues has been assigned to you so that we can merge it without having conflicts!

**Comment by singh-anushka** [comment]
@MonalikaPatnaik I don't think I can make a google analytics dashboard for the website. Because I didn't create it. So I guess so I can't do this. Sorry for the inconvenience. : (
