### ISSUE TITLE
Sign Up button is displaced 

### ISSUE THREAD

**Issue by Aanya9693** [MonalikaPatnaik/UMatter#374]
**Describe the bug**
I have noticed that the Sign Up button is displaced in full-screen size, and it looks very bad, I want to make it good by fixing the issue.

**Screenshort**
![Screenshot (141)](https://github.com/MonalikaPatnaik/UMatter/assets/101557638/f04fddda-d9f6-41ab-9014-5e2f7cf49fd8)

**Comment by BikramNarayan** [comment]
I want to work on this issue , please assign it to me @MonalikaPatnaik

**Comment by vishnubansal001** [comment]
i wan to work on it please allow me to work on this issue please allow me to work on it @MonalikaPatnaik @i-am-SnehaChauhan

**Comment by MonalikaPatnaik** [comment]
Hey it's been resolved!
