### ISSUE TITLE
Navbar element conflict

### ISSUE THREAD

**Issue by SubhamB2003** [MonalikaPatnaik/UMatter#376]
**Describe the bug**
The navbar element is not properly placed.

**Screenshort**

The signup button is not placed properly

![image](https://github.com/MonalikaPatnaik/UMatter/assets/94003231/d352fe4c-6fb2-46e5-9343-8a9125d8f711)

Also, the Mobile view is the same thing

![image](https://github.com/MonalikaPatnaik/UMatter/assets/94003231/ab245c46-9672-42ca-9b91-ec56d1d773c6)

 
I want to work on it can assign it to me?

**Comment by MonalikaPatnaik** [comment]
It's been resolved i think..
