### ISSUE TITLE
error in sign up page

### ISSUE THREAD

**Issue by Shikha954** [MonalikaPatnaik/UMatter#377]
In "full name" area as u can see in the image there is a bug .i want to work on that issue @MonalikaPatnaik ma'am please assign me this issue

<img width="451" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/84771860/809a5353-c26e-4735-aaa4-451065437d14">

**Comment by vishnubansal001** [comment]
i want to work on this issue please allow me to work on this issue @MonalikaPatnaik  @i-am-SnehaChauhan

**Comment by i-am-SnehaChauhan** [comment]
Hey @Shikha954, u can start working on this.

**Comment by Shikha954** [comment]
@i-am-SnehaChauhan ok ma'am thank u for this opportunity
