### ISSUE TITLE
position of sign up in home page

### ISSUE THREAD

**Issue by Shikha954** [MonalikaPatnaik/UMatter#378]
as u can see the position of sign up in not correct so i want to work in this issue @MonalikaPatnaik ma'am please assign me this issue
<img width="723" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/84771860/28fc1eb5-45a6-4c8f-929c-8e9b6140a3d9">

**Comment by MonalikaPatnaik** [comment]
It's been done!
