### ISSUE TITLE
[ 🪲 ] Handling the disappearance of Navbar in blogs Page

### ISSUE THREAD

**Issue by Kalyan-velu** [MonalikaPatnaik/UMatter#379]
## Navbar not optimized for smaller and medium screens

**Description:**
On the UMatter project's navbar, there is an issue when viewing the website on smaller screens. Currently, when the navbar is opened and an option is clicked, it does not automatically close. The user has to manually click the navbar button again to close it. Additionally, when the "home" button is clicked, the navbar still overlays the hero section, causing a visual overlap.

This issue affects the usability and user experience of the website on smaller and medium screens. To provide a better user experience, it would be ideal for the navbar to automatically close after selecting an option. Furthermore, the navbar should not overlay the hero section when the "home" button is clicked.

**Labels:** bug, enhancement

**Comment by Kalyan-velu** [comment]
I am available to fix this issue as part of my contribution to the GirlScript Summer of Code 2023 program. Kindly assign this issue to me so that I can start working on it.

Please let me know if there are any other specific considerations or requirements for this issue.

**Comment by MonalikaPatnaik** [comment]
Navbar for the smaller screens is currently being handled by someone else! what u can do is..if u see the navbar in blog page...it seems disapperaed in the dark mode..You can fix it!
![image](https://github.com/MonalikaPatnaik/UMatter/assets/99353300/693213af-8972-46c2-aa56-c4d0f734c9a5)
You can try fixing the color..
let me know if u are willing to work on this?

**Comment by Kalyan-velu** [comment]
@MonalikaPatnaik Yes, I would love to work on it.

**Comment by MonalikaPatnaik** [comment]
Thanks..you are assigned!
Pls submit your PR soon so that we can merge it without conflicts!
