### ISSUE TITLE
Updating the About Page and Signup Page

### ISSUE THREAD

**Issue by Uma-95** [MonalikaPatnaik/UMatter#38]
The Get Started button in the About Page isn't working.
The Signup option when clicked isn't working.
When the Get Started button is clicked this could be redirected to the signup page.

This will help the user to find a starting point on the website by signing up and will eventually get to know about the next steps.

**Comment by Uma-95** [comment]
@MonalikaPatnaik I'm a GSSOC'23 contributor, could you please assign this issue to me as a part of GSSOC '23.

**Comment by Mansi168** [comment]
hey you can start working on About page but signup page is already assigned.
you are assigned, go ahead!

**Comment by MonalikaPatnaik** [comment]
> The Get Started button in the About Page isn't working. The Signup option when clicked isn't working. When the Get Started button is clicked this could be redirected to the signup page.
> 
> This will help the user to find a starting point on the website by signing up and will eventually get to know about the next steps.

Hey u are redirecting the get started button in the about us page  to the sign up page right? It's been long..I recommend to submit your PR soon!

**Comment by Uma-95** [comment]
yes sure...I apologize for the delay@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
> yes sure...I apologize for the delay@MonalikaPatnaik

Hey @Uma-95 Pls do it soon..otherwise will assign it to someone else!

**Comment by Deepanshu0703** [comment]
Is this issue is available now
