### ISSUE TITLE
new feature for 'watch helpful videos' section!!

### ISSUE THREAD

**Issue by laibaahsan27** [MonalikaPatnaik/UMatter#380]
**Feature idea.**

INFINITE SCROLL
I would like display your youtube  links in a better way by adding infinite scroll feature. which will enhance the look of this section and increase the user experience. 
here is an example of how infinite scroll works

https://github.com/OSCode-Community/OSCodeCommunitySite/assets/123810454/f02b3f23-0ba2-4806-bbc2-d0b38a57ad63

currently the section looks like this
![image](https://github.com/MonalikaPatnaik/UMatter/assets/123810454/073a01ac-f424-404d-9ef6-fdb106bbb0a5)
it is a bit clustered and not very appealing 

I believe in a crowded online landscape, this feature will make your website stand out and provide a better user experience and engagement.
If you like my idea then @MonalikaPatnaik please assign it to me under the label GSSOC 2023.
Thank you

**Comment by laibaahsan27** [comment]
Hey @MonalikaPatnaik if you like my idea then please assign it to me under the label GSSOC 2023.

**Comment by MonalikaPatnaik** [comment]
Hey yes yes...i loved your idea..you can start working on this!
Sorry for the delay!

**Comment by laibaahsan27** [comment]
no problem , also could you please add level tag

**Comment by MonalikaPatnaik** [comment]
Hey level labels are added to the issues once their related PR is merged! I have mentioned it in the GitHub discussion too..

**Comment by MonalikaPatnaik** [comment]
Will add level label to this once your PR gets approved and merged

**Comment by vk20july** [comment]
@MonalikaPatnaik can i do this task under gssoc'23

**Comment by MonalikaPatnaik** [comment]
Hey i think no further changes are req in this section
