### ISSUE TITLE
improve: Contact form layout

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#382]
**Describe the bug**
Currently contact form has not better layout so we need to fix that

**Screenshort**

 
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/126fe6ea-27b4-48b1-a8d8-2c81d3c7dd70)

**Comment by shivam-sharma7** [comment]
assign me @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Hey..you can work on this! submit your PR soon so that we can merge it without conflicts!
