### ISSUE TITLE
For large screen, Signup button is not designed well

### ISSUE THREAD

**Issue by bhaskarkumar1** [MonalikaPatnaik/UMatter#385]
**Describe the bug**

For large screen, Signup button is not designed well.  Please see  the screenshot attached below.
Please assign this task to me, So that I can work on it.
 
![navbutton](https://github.com/MonalikaPatnaik/UMatter/assets/84345649/327be921-f186-4361-98a2-343c4b8b4851)

**Comment by shivam-sharma7** [comment]
it is dublicate of #382 so need to close
