### ISSUE TITLE
Shift all the social icons to the center positions

### ISSUE THREAD

**Issue by vk20july** [MonalikaPatnaik/UMatter#388]
![Screenshot (199)](https://github.com/MonalikaPatnaik/UMatter/assets/71543332/1e651f1b-8826-4843-a1bb-f15d4f482ff4)

**Comment by vk20july** [comment]
mam @MonalikaPatnaik please assign this issue to me

**Comment by MonalikaPatnaik** [comment]
It's been already assigned to someone else!

**Comment by MonalikaPatnaik** [comment]
Hey @vk20july you can work on this!
Pls submit your PR soon!

**Comment by vk20july** [comment]
Ok mam
