### ISSUE TITLE
Sign Form is not responsive 

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#391]
**Feature idea.**
The sign form is not responsive the form looks very weird on a big device

**Describe the solution you'd like**
I want to make the sign form responsive, to improve the user experience as well as the UI of the website
![13](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/81234e29-b3f3-430b-af9e-136f01ce706a)
![14](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/6833a209-6e60-4415-8687-cffd43a89965)

**Comment by utkarshgupta04092003** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.
Kindly provide me the opportunity to work on the issue.

**Comment by Visbhavesh** [comment]
please assign me this issue.
