### ISSUE TITLE
Bug in sign in  page

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#392]
**Describe the bug**
Bug in sign in  page, it not showing the email section while login

**Screenshort**

 
![15](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/f6092505-a99a-46fa-9c89-dca6322cd46c)

**Comment by prabhatsingh985** [comment]
Can you please provide the link of this web page.

**Comment by MonalikaPatnaik** [comment]
it's been resolved now!

**Comment by prabhatsingh985** [comment]
ohkay .
