### ISSUE TITLE
Margin required between navbar and blog page content

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#393]
**Feature idea.**

Margin required between navbar and blog page content

**Describe the solution you'd like**

No margin between the navbar and blog page content, and the navbar is decreasing the readability of the website, i want to add some margin between navbar and blog page content, to improve the readability of the website
Screenshot
![16](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/ecc76ef4-36be-4b61-80e5-6cd8522f97d7)

**Comment by MonalikaPatnaik** [comment]
It's been fixed!
