### ISSUE TITLE
Blog page issue in navbar & cards

### ISSUE THREAD

**Issue by Atharvasharma12** [MonalikaPatnaik/UMatter#394]
![blog navbar issue](https://github.com/MonalikaPatnaik/UMatter/assets/89251910/611aa148-ab5d-4cd1-bf80-9d74cd77f74d)

Navbar visibility -
The navbar goes trasperent in the blog page and all the posts are below the transparent navbar which make it conjusted and not proper styled.

Cards layout - 

so let me fix this issue.

Please assigne this to me.

**Comment by MonalikaPatnaik** [comment]
It's been resolved now!

**Comment by Atharvasharma12** [comment]
Ohh,
It seems I got late.I have to figure out something else then.
Thank you.
