### ISSUE TITLE
Improvement of Sign In and Sign Up UI

### ISSUE THREAD

**Issue by Ujwal19k** [MonalikaPatnaik/UMatter#397]
**Feature idea.**

The Sign In and Sign Up page is not proper in terms of UI and looks complex in big screen

**Describe the solution you'd like**

I would like to improve Sign In and Sign Up page. I can provide a figma design initially for demo
<img width="713" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/106575224/91bc2cc6-9344-412a-b659-4ceeba992775">
<img width="883" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/106575224/08816c2e-b272-4db6-9400-3930869a3a93">

**Comment by Sahil21dev** [comment]
@Ujwal19k @MonalikaPatnaik  Please assign this issue to me . I want to work on it i'm a contributer under GSSOC'23.

**Comment by utkarshgupta04092003** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.
Kindly provide me the opportunity to work on the issue.
