### ISSUE TITLE
Fixing alignment

### ISSUE THREAD

**Issue by Bharadwajshivam28** [MonalikaPatnaik/UMatter#4]
It is not aligned properly we must fix it

![Screenshot from 2023-05-20 00-45-30](https://github.com/MonalikaPatnaik/UMatter/assets/108119109/5478b808-0acc-49c8-82ff-aaae62d6df08)

ABOUT US is cut from up

Please assign me under GSSOC23

**Comment by AmanMittal-3305** [comment]
hii
please assign me this issue

**Comment by MonalikaPatnaik** [comment]
> It is not aligned properly we must fix it
> 
> ![Screenshot from 2023-05-20 00-45-30](https://user-images.githubusercontent.com/108119109/239617700-5478b808-0acc-49c8-82ff-aaae62d6df08.png)
> 
> ABOUT US is cut from up
> 
> Please assign me under GSSOC23

I think it's been resolved!
