### ISSUE TITLE
Add scroll to top button 

### ISSUE THREAD

**Issue by singh-anushka** [MonalikaPatnaik/UMatter#400]
**Feature idea.**

Add scroll to top button.
**Describe the solution you'd like**

Using javascript add a button which automatically scrolls a person to top.

I'm a GSSOC23 contributor, please assign me this issue with the label of GSSOC23 and level 3 labels.

**Comment by singh-anushka** [comment]
@MonalikaPatnaik please assign me this issue.

**Comment by MonalikaPatnaik** [comment]
Hey similar issue has already been assigned

**Comment by singh-anushka** [comment]
That is finding visitor analytics for a website. While this is UI improvement.

**Comment by singh-anushka** [comment]
[Adding features to the sign-up page](https://github.com/MonalikaPatnaik/UMatter/issues/399) 

All the 3 issues are different.
