### ISSUE TITLE
Improving sign up section along with validation

### ISSUE THREAD

**Issue by lakshmiprasannakusumanchi** [MonalikaPatnaik/UMatter#405]
**Feature idea.**

I would like to improve the ui part of signup page .

**Describe the solution you'd like**

By formating the sign up form adding validation to it .

 I would like work on this issue please assign this to me under gssoc'23

**Comment by lakshmiprasannakusumanchi** [comment]
Can I go with the issue.

**Comment by MonalikaPatnaik** [comment]
hey..you can improve the UI of Sign up page in accordance to the current sign in page ui..don't change the layout of sign-up page as someone is already fixing the layout..
Go ahead and pls submit your PR soon so that we can merge it without conflicts!

**Comment by MonalikaPatnaik** [comment]
Hey @lakshmiprasannakusumanchi..don't change the layout or ui...just add the validation part only!
Are u working on this?

**Comment by lakshmiprasannakusumanchi** [comment]
@MonalikaPatnaik Iam working on this.

**Comment by anonymgit** [comment]
@lakshmiprasannakusumanchi are you working on this? do you need any help?

**Comment by anonymgit** [comment]
> @anonymgit yeah I am unaware of backend I am facing difficulty in this .

there is no need of backend in this,validation can be done in front end part,use react states ,just google/chatgpt how to add validation in form,you will get the proper guidance with source code.

**Comment by AlfiyaSiddique** [comment]
@MonalikaPatnaik  I am waiting in the queue to work on this issue.
I would like to add inline validation where the user gets a validation message in the real-time , that is when the user enters the input and the input does not match the constraint the validation message will appear below the respective fields, and as soon as the valid input is given the messages will disappear.

Waiting to be assigned to this issue under the gssoc'23 label.

**Comment by TechSpiritSS** [comment]
Hey @AlfiyaSiddique this issue was completed and a PR was merged last week as well.

**Comment by AlfiyaSiddique** [comment]
Hello! @TechSpiritSS 
 Okay, I got it, But I am asking to implement a real-time validation message functionality in the sign-up form.
 Currently, While typing on form fields there is no validation message appearing to guide the users. The validation Message appears after clicking on the **Continue** button. I want to make those messages appear below the respective fields as the user types into that field. And as soon as the user enters the valid input the message disappears. You can see a sample below:


https://github.com/MonalikaPatnaik/UMatter/assets/86224794/69a89e0e-ffbd-4e1e-80ac-74d2866fd8da

I want to implement functionality similar to the above video If you allow it!
Should I create a new issue for this feature?
