### ISSUE TITLE
Sign In form username field missing

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#406]
**Describe the bug**
Sign In form username field missing currently show only paasword field

**Screenshort**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/3b020a69-9464-456c-b3f7-ffdb084273fc)

**Comment by N03Nilay** [comment]
I can fix this bug by adding a field for this and authenticating it .

**Comment by Kapileswar-Moharana** [comment]
Assign this to me I wil solve the bug,works under GSSoC'23

**Comment by MonalikaPatnaik** [comment]
It's been done!
