### ISSUE TITLE
Change of the color of navbar's element on hover

### ISSUE THREAD

**Issue by lakshmiprasannakusumanchi** [MonalikaPatnaik/UMatter#408]
**Describe the bug**

Want to change the color of the navbar because on directing to sign in/sign up page it is not clear 

**Screenshort**

![Screenshot 2023-05-26 203730](https://github.com/MonalikaPatnaik/UMatter/assets/118244809/5d45b888-ccae-47e4-9e4d-2bbf8b6a9661)

I would like to work on this issue please assign this to under gssoc'23

**Comment by Kapileswar-Moharana** [comment]
Want to change the color of the navbar because on directing to sign in/sign up page it is not clear
Also I would like to solve this Assign me under GSSoC'23

**Comment by prabhatsingh985** [comment]
Would like to work on this issue , Can simply change write a CSS to change the color of navbar on hover

**Comment by Kapileswar-Moharana** [comment]
Yes

**Comment by prabhatsingh985** [comment]
@Kapileswar-Moharana Can you please provide me the link of this web page or the link in github from where I can change the code.

**Comment by Kapileswar-Moharana** [comment]
I don't understand actually should I contribute or give the code to you. I think you are not the PA of this project, As you can see I messaged here for you to assign me under this issue I will solve this.

**Comment by prabhatsingh985** [comment]
Okay I thought You raised this issue  ;)

**Comment by MonalikaPatnaik** [comment]
Heyy @lakshmiprasannakusumanchi can you change the background of sign up page to make it changeable according to the theme just like in sign in page?
