### ISSUE TITLE
Scroll to top on pressing "Home" button on navbar

### ISSUE THREAD

**Issue by rayyan016** [MonalikaPatnaik/UMatter#41]
I would like to add a feature to scroll to top when the "Home" button on navbar is clicked. Could you please assign me this  issue under GSSOC'23?
![issue](https://github.com/MonalikaPatnaik/UMatter/assets/102043379/f8b9da0f-06b8-4440-8ea9-b0339bec9626)

**Comment by Aryan123-rgb** [comment]
@MonalikaPatnaik Hii, I can fix this issue . Please assign it to me :)

**Comment by rayyan016** [comment]
@Mansi168  Ma'am, Could you assign this issue to me so I can put a PR? Thanks in Advance.

**Comment by purviporwal0** [comment]
Can you pls assign this to me as I would love to add this feature under GSSOC'23

**Comment by Mansi168** [comment]
@rayyan016 you are assigned!
