### ISSUE TITLE
Overall look of this website is very unattractive 

### ISSUE THREAD

**Issue by Rekhathakur8** [MonalikaPatnaik/UMatter#411]
**Feature idea.**

**Describe the solution you'd like**

**Comment by shivam-sharma7** [comment]
Can you show some of changes in the form of screenshorts

**Comment by MonalikaPatnaik** [comment]
@Rekhathakur8 what exactly would u like to do?

**Comment by Rekhathakur8** [comment]
I just want to work with its css.

**Comment by Rekhathakur8** [comment]
Of course I can show. Give me some time
