### ISSUE TITLE
Sign In & Sign Up Page UI refactoring

### ISSUE THREAD

**Issue by tayyab-ilyas** [MonalikaPatnaik/UMatter#413]
I'd like to make the sign in & sign up pages more visually appealing to the users by working on the UI part.

**Comment by tayyab-ilyas** [comment]
Hi @MonalikaPatnaik can I get issue assigned under GSSoc'23? thanks!

**Comment by MonalikaPatnaik** [comment]
Heyy @tayyab-ilyas you can improve the UI of signup page in accordance to the current UI of sign-in page!
are u willing to work on this? lmk if u cann't!

**Comment by tayyab-ilyas** [comment]
thanks for assigning! I'll start working

**Comment by MonalikaPatnaik** [comment]
Heyy pls check my comment on your PR!

**Comment by tayyab-ilyas** [comment]
> Heyy pls check my comment on your PR!

I've committed the changes!
