### ISSUE TITLE
[Gssoc'23]Add a contact us section with social media icon for users to contact conveniently

### ISSUE THREAD

**Issue by prathanab** [MonalikaPatnaik/UMatter#414]
**Feature idea.**

A contact us section with social media icon for users to contact conveniently.

**Describe the solution you'd like**

Add a contact us section with social media icon for users to contact conveniently using html and css below our services.

![WhatsApp Image 2023-05-26 at 10 36 24 PM](https://github.com/MonalikaPatnaik/UMatter/assets/121685069/df36b26a-9231-4392-9e76-6b82762c77b4)

**Comment by MonalikaPatnaik** [comment]
Contact us section has already been added..Check the footer of the website!

**Comment by MonalikaPatnaik** [comment]
Could you tell me where are u adding this?

**Comment by prathanab** [comment]
Like this...

![IMG_20230527_211345_450](https://github.com/MonalikaPatnaik/UMatter/assets/121685069/4a56a938-d35f-4d5c-afc0-f81951abc76c)

**Comment by MonalikaPatnaik** [comment]
Umm..there is a separate page for contact section nd I don't think it is required!

**Comment by prathanab** [comment]
Would you like to add this in that separate page ?

**Comment by i-am-SnehaChauhan** [comment]
Hey @prathanab If you want u can add it in the contact page itself.

**Comment by i-am-SnehaChauhan** [comment]
If u are ready i can assign this to u.. LMK.

**Comment by prathanab** [comment]
Yes ! I am ready.

**Comment by MonalikaPatnaik** [comment]
In the contact page, the icons doesn't look good there...we are having these icons at footer as well..

**Comment by MonalikaPatnaik** [comment]
Hey @prathanab...you can change the background of contact page with the theme as it..is in the sign in page?
Would u like to do this?

**Comment by prathanab** [comment]
Yes I can try @MonalikaPatnaik .
Thank you for allowing me.

**Comment by MonalikaPatnaik** [comment]
> Yes I can try @MonalikaPatnaik . Thank you for allowing me.

Okay..try and lmk if u can do this or not!
