### ISSUE TITLE
Modify "About Us "section by havor effect

### ISSUE THREAD

**Issue by ShrutiSingh-1** [MonalikaPatnaik/UMatter#415]
"ABOUT US" section is simple , if we create/add havor effect then it will look great.

**Comment by MonalikaPatnaik** [comment]
Where would you add the hover effect?

**Comment by ShrutiSingh-1** [comment]
> 
![image](https://github.com/MonalikaPatnaik/UMatter/assets/98824644/fdf8afed-001d-4296-a9e6-176592e4f344)
 i want to add hovor effect to this "About Us" section ,as it is very simple now.

please assign me this work!!

**Comment by ShrutiSingh-1** [comment]
@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Hey..you are assigned!

**Comment by ShrutiSingh-1** [comment]
@MonalikaPatnaik Thankyou for assigning work!!

**Comment by ShrutiSingh-1** [comment]
currently i have exams till 2nd of june, so i'll be updating you with the PR a day or two after that. Is that fine?

**Comment by anupriyapoddar** [comment]
hey, I want to work on this issue. can you please assign it to me?

**Comment by ShrutiSingh-1** [comment]
i am too working on this issue, since i had exam so i couldn't able to complete it. But, now i will solve this issue @anupriyapoddar

**Comment by Dimple-01** [comment]
I want to work on this issue.
I will fix this within few hours.
Please this work to me.

**Comment by ShrutiSingh-1** [comment]
@MonalikaPatnaik  i have solved the issue of adding hover.json but i am facing this issue while running the application, could you suggest what the error could be?
![image](https://github.com/MonalikaPatnaik/UMatter/assets/98824644/31c10fc3-dca6-4e7e-96c6-028740eec1c3)
