### ISSUE TITLE
[GSSoC'23] Adding BackGround to Current Sign-in page to make it changeable with the theme

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [MonalikaPatnaik/UMatter#419]
**Feature idea.**
Redesigning the SignUp page to make the UX better. So more and more users are attracted to sign up on Umatter

**Describe the solution you'd like**
Hey @MonalikaPatnaik 
I would like to redesign the SignUp and add CSS to make it responsive to all device sizes.

I also redid your signin page and could do a similar redesign for the sign up page too.

If you liked the signin page please do assign me.
Thanks

**Comment by MonalikaPatnaik** [comment]
Hey..I think someone raised the issue before you..so I assigned them...will assign you if needed improvemnts!
As of now, You can change the background of sign up page and also can add some feature to change it accordingly with the theme bcoz the current sign up page is not changing according to the theme..Don't change the form..it's looking perfectly fine..I loved the design..just fix the background issue..
Would you like to work on this?

**Comment by rishabhchaudhary0210** [comment]
Currently this is the SignUp page

As per my understanding the form isn't exactly responsive to the screen size also the show password is wrongly positioned. As well as the gradient in the Sign-in is not replecated here which breaks the design. So there are plenty of things that can be fixed.
The basic structure of the overall form seems great, it is only the designing that needs a revamp.
If you could please specify more as to exactly what change do you need. I will be happy in doing it.

![image](https://github.com/MonalikaPatnaik/UMatter/assets/97378312/178690e5-aad2-4cdb-b724-88fe6bcb9b2a)

**Comment by MonalikaPatnaik** [comment]
> Hey..I think someone raised the issue before you..so I assigned them...will assign you if needed improvemnts! As of now, You can change the background of sign in page and also can add some feature to change it accordingly with the theme bcoz the current sign up page is not changing according to the theme..Don't change the form..it's looking perfectly fine..I loved the design..just fix the background issue.. Would you like to work on this?

Hey..I mean to say the bg of sign-in page..
sorry for confusion :-')

**Comment by rishabhchaudhary0210** [comment]
Ok! So you want me to remove the gradient effect from the Sign-in Form ?

**Comment by MonalikaPatnaik** [comment]
No, gradient effect is looking good(that'why I merged your PR :-)..don't change the form, just change the bg of sign-in form so that it can change according to the dark/light mode theme!

**Comment by MonalikaPatnaik** [comment]
> Hey..I think someone raised the issue before you..so I assigned them...will assign you if needed improvemnts! As of now, You can change the background of sign in page and also can add some feature to change it accordingly with the theme bcoz the current sign in page is not changing according to the theme..Don't change the form..it's looking perfectly fine..I loved the design..just fix the background issue.. Would you like to work on this?

Read it again!

**Comment by rishabhchaudhary0210** [comment]
That's what I was thinking about the merged PR !!! I'm really sorry for all the confusion.
Ans yes I would definitely like to make it changeable according to the themes.
Just one thing can i submit it till tommorrow.

**Comment by MonalikaPatnaik** [comment]
Yes sure..No problem!
Thankyou!

**Comment by rishabhchaudhary0210** [comment]
Hey @MonalikaPatnaik I have added theme toggling for the sign-in page and issue the PR #437 
Kindly review it and let me know if there's anything else I can do.
