### ISSUE TITLE
Adding Navbar to Signin Page

### ISSUE THREAD

**Issue by huzaifa9999** [MonalikaPatnaik/UMatter#42]
I would like to fix the following issues

Whenever the link is clicked from the sign-In page , only  a white screen is shown and the site is not directed to the home page even on refreshing the page. 
Also redirecting the {Get started} button to the sign-In page.
 Also adding Nav bar to the Sign in page with proper alignment.

**Comment by huzaifa9999** [comment]
@MonalikaPatnaik I'm a GSSOC'23 contributor and would like to work on these issues.

**Comment by MonalikaPatnaik** [comment]
Heyy @huzaifa9999..first & second one is currently being resolved..you can work on third issue: adding navbar to signin page..
Thanks for contributing!

> I would like to fix the following issues
> 
> Whenever the link is clicked from the sign-In page , only a white screen is shown and the site is not directed to the home page even on refreshing the page. Also redirecting the {Get started} button to the sign-In page. Also adding Nav bar to the Sign in page with proper alignment.
