### ISSUE TITLE
Enhance: Ui of the signup page. 

### ISSUE THREAD

**Issue by Pragati-3003** [MonalikaPatnaik/UMatter#420]
I would like to change the sign up form as 
It is not looking attractive. 
![IMG_20230527_104358](https://github.com/MonalikaPatnaik/UMatter/assets/132778037/fab718a2-dddb-4086-8a87-edc23a53173b)
Iso, please assign this issue to me under GSSOC'23.

**Comment by MonalikaPatnaik** [comment]
Hey it's been done by #361..will let u know if needed improvemnt!
