### ISSUE TITLE
enhancing the README file

### ISSUE THREAD

**Issue by gummitha-anushka** [MonalikaPatnaik/UMatter#421]
Current State:
The about us section is very brief and I feel it could use some description regarding the website. 
The various components of the website could use some description to give more understanding about them.

Desired State:
I would like to work on the description about what the project is. This would give provide more clarity and understanding about the project.
Since the screenshots of the components of the website are already present, a brief description could increase its effectiveness.
As a GSSOC'23 contributor, I would like to work on this so that the projects purpose is conveyed through the README file.

**Comment by MonalikaPatnaik** [comment]
Hey..you can work on this!
