### ISSUE TITLE
Hover effect on brand logo

### ISSUE THREAD

**Issue by sumitkr2000** [MonalikaPatnaik/UMatter#424]
**Feature idea.**
Hey @MonalikaPatnaik the Hover effect on the brand logo is not matching with the theme of the website. Please assign me this issue. I want to work on it. Thank you!

**Describe the solution you'd like**

The color of the brand logo after hovering should match the theme of the website.

**Comment by MonalikaPatnaik** [comment]
I think similar issue is already been assigned!

**Comment by MonalikaPatnaik** [comment]
@sumitkr2000 do you want to make the logo in the navbar hoverable??

**Comment by sumitkr2000** [comment]
Yeah sure @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
> Yeah sure @MonalikaPatnaik

Then make the logo of Umatter in navbar hoverable!
