### ISSUE TITLE
 Redundant and Confusing Redirection of "Get Started" Button on About Page

### ISSUE THREAD

**Issue by drakshi** [MonalikaPatnaik/UMatter#425]
**Describe the bug**
There is a usability issue with the "Get Started" button on the About page. Currently, when clicked, the button redirects users to the home page, which already contains a "Get Started" button that further redirects users to the sign-in page. This redundancy and confusion in the user flow need to be addressed.

**Problem Description:**
The current redirection of the "Get Started" button on the About page creates a redundant user experience. Users are directed to the home page, where they encounter another "Get Started" button that leads to the sign-in page. This unnecessary redirection adds confusion and may deter users from efficiently accessing the sign-in page.

**Proposed Solution:**
To improve the user experience and eliminate redundancy: 

1. Directly redirect users to the sign-in page: The code associated with the "Get Started" button on the About page can be modified to directly redirect users to the sign-in page. This approach eliminates the extra step of navigating to the home page and subsequently clicking the "Get Started" button again.

2. Renaming the button for clarity: If the "Get Started" button on the About page is intended to serve a different purpose than the one on the home page, consider renaming it to reflect its specific function. For example, it could be renamed to "Learn More" or "Explore Features" to provide a clearer indication of the action users will take when clicking the button.

**Screen recording of the problem**

https://github.com/MonalikaPatnaik/UMatter/assets/62384655/163e42c1-bbfa-4116-ae19-0938750c1f73

**Comment by MonalikaPatnaik** [comment]
okay then redirect it to the signin page!
