### ISSUE TITLE
Dark mode not working in blog section

### ISSUE THREAD

**Issue by AditiSingh2003** [MonalikaPatnaik/UMatter#427]
**Describe the bug**

When we click on the blog section in dark mode it does not change the mode and also the text in the navbar is not chnaging.

**Screenshort**

![image](https://github.com/MonalikaPatnaik/UMatter/assets/97729662/fb507281-fb84-4b52-9fd6-60bbbe9142ea)

**Comment by i-am-SnehaChauhan** [comment]
Hey, @AditiSingh2003 you can work on this issue.

**Comment by MonalikaPatnaik** [comment]
I think it's been assigned to #264
