### ISSUE TITLE
[GSSoC'23] Add redirection link to Socials icons

### ISSUE THREAD

**Issue by Rishav1707** [MonalikaPatnaik/UMatter#429]
**Describe the bug**

In the footer section, the social link is not redirecting to any external links.

**Screenshort**

 
![image](https://github.com/MonalikaPatnaik/UMatter/assets/97666287/d09c6400-8cf8-4471-8b04-a7fd215c77a2)

**Comment by MonalikaPatnaik** [comment]
Hey we are not having social links as of now!

**Comment by Rishav1707** [comment]
> Hey we are not having social links as of now!

Ok
