### ISSUE TITLE
Some of the contents of navabar in blog section are not visible due to white background

### ISSUE THREAD

**Issue by Shreyans2004** [MonalikaPatnaik/UMatter#433]
**Describe the bug**

Some of the contents of navabar in blog section are not visible due to white background.
I can change the color of the contents so that they would be visible.Can you assign this issue to me?
**Screenshort**
![WhatsApp Image 2023-05-27 at 15 33 09](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/54fa1326-36ce-4763-9dcb-0f2df601475a)

**Comment by kunjal293** [comment]
I would like to work on this issue. Can you please assign me this project

**Comment by priyapahwaa** [comment]
i request you to assign me this task, would like to solve this issue.
