### ISSUE TITLE
[GSSoC'23] Overlapping navbar in Contact us section

### ISSUE THREAD

**Issue by Rishav1707** [MonalikaPatnaik/UMatter#434]
**Describe the bug**

The navbar overlaps with the contact us section, which is bad for the user interface and user experience.

**Steps to reproduce**

1. Go to `https://umatter-git-main-monalikapatnaik.vercel.app/`
2. Scroll down to `bottom` section
3. Click on the `contact` option under the Contact Us section
4. See the error.

**Actual Behaviour**

![Contact_Before](https://github.com/MonalikaPatnaik/UMatter/assets/97666287/7e6d1d3f-2b23-4f32-baaf-272eb6447cef)

**Expected Behaviour**

![Contact_after](https://github.com/MonalikaPatnaik/UMatter/assets/97666287/3ce3dbc8-e017-444c-a481-e8245bf62144)

**Comment by Rishav1707** [comment]
I would like to work on this issue. Please assign this issue to me under `GSSoC'23`.

**Comment by shivam-sharma7** [comment]
close, this is duplicate of #382
