### ISSUE TITLE
Can make an interface for consult with a doctor 

### ISSUE THREAD

**Issue by Shashwat0227** [MonalikaPatnaik/UMatter#44]
As it is just the main interface ready i can add interface for the consulting a doctor

**Comment by Mansi168** [comment]
go ahead @Shashwat0227 you are assigned!

**Comment by Suchitra-Sahoo** [comment]
@Mansi168 may I work on this issue as GSoC'23 contributor too?

**Comment by Shashwat0227** [comment]
thanks , let me complete it by day after tomorrow 
and let me know your socials on linkedin and twitter 
looking forward for more projects

**Comment by MonalikaPatnaik** [comment]
Heyy @Shashwat0227..is it done?

**Comment by Shashwat0227** [comment]
> Heyy @Shashwat0227..is it done?

hey sorry was busy with other prs , its almost done , till tomorrow evening i will upload my PR , thanks for the wait :)

**Comment by MonalikaPatnaik** [comment]
> > Heyy @Shashwat0227..is it done?
> 
> hey sorry was busy with other prs , its almost done , till tomorrow evening i will upload my PR , thanks for the wait :)

No problem..it's completely fine..take your time!

**Comment by Shashwat0227** [comment]
sure thanks , its a full interface so it is taking time :)

**Comment by MonalikaPatnaik** [comment]
Hey see..you can make a simple page in one PR then raise issues related to the improvemnent of that page..You can work in fragments too! 
If you want level 3 label then you need to do that in an one go like adding all functionalities & all..
If you wish you can make a simple page( level 2) & raise issues related to it ( both level 1 & 2)
I hope u understand!
Thankss

**Comment by Shashwat0227** [comment]
@MonalikaPatnaik okay thanks i will then PR a simple site and then will add the enhancements to that  > :) thanks for letting me do this

**Comment by Shashwat0227** [comment]
@MonalikaPatnaik so sorry , you can assign it to other , i just messed my full code base and the copied version is also gone i dont know how , just to increase PRs i was editing it and it messed full :(
sorry to take your this much time :(
