### ISSUE TITLE
Create submit button for contact page

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#440]
**Feature idea.**

Create submit button for contact page. Currently it have not. And add placeholder

![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/4e79000f-cd3a-4241-a78c-c4363f2b68ac)

**Comment by shivam-sharma7** [comment]
@MonalikaPatnaik

**Comment by mohitcs46** [comment]
Hi @shivam-sharma7  Please assign me this issue under GSSoC'23, thank you.
