### ISSUE TITLE
enhancing card UI in blog page

### ISSUE THREAD

**Issue by Piyusharora2003** [MonalikaPatnaik/UMatter#442]
- currently the blog card is uncertain about the size of image , title , description
- giving a fixed height to cover image 
- specifying max-length to description to prevent overflow , if still overflow a scroll bar 

![image](https://github.com/MonalikaPatnaik/UMatter/assets/74443858/7e3f4475-a1de-4179-80fa-bcae4660fc61)

Please do assign me this issue !

**Comment by i-am-SnehaChauhan** [comment]
Hey @Piyusharora2003, This issue is similar to #324 
Please msg there 
Thanks:)
