### ISSUE TITLE
Adding responsiveness in watch helpful section.

### ISSUE THREAD

**Issue by Shashank2104125** [MonalikaPatnaik/UMatter#444]
**Describe the bug**
"Watch helpful section" on blogs page not properly aligned according to the devices.

**Screenshort**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/97789487/ba76c862-f81e-48fe-b302-660f0ddcf599)

**Comment by Shashank2104125** [comment]
@MonalikaPatnaik please assign it to me.

**Comment by MonalikaPatnaik** [comment]
Okayy do it!

**Comment by MonalikaPatnaik** [comment]
Hey is it done?? pls submit your PR by eod!
