### ISSUE TITLE
Adding dark mode to blogs tab

### ISSUE THREAD

**Issue by Devil1205** [MonalikaPatnaik/UMatter#448]
**Feature idea.**

Currently dark mode only works for navbar in blogs tab. It would be great to apply it on its body section.

**Describe the solution you'd like**

Making colors of whole body secttion of blogs tab adapt according to the light/dark theme currently used.

Current situation:
![image](https://github.com/MonalikaPatnaik/UMatter/assets/103431946/c1ecd571-7421-48eb-b3d9-3e59166f7a7f)

**Comment by Devil1205** [comment]
I would like to add this feature. Kindly assign me.
@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
It's been assigned to #264
