### ISSUE TITLE
No dark mode for mobile dimensions

### ISSUE THREAD

**Issue by Shreyans2004** [MonalikaPatnaik/UMatter#451]
**Describe the bug**

There is no dark mode for mobile dimensions.I  can add  dark mode in the Navbar in the mobile dimensions. Can you assign this task to me?GSSOC23
**Screenshort**
![WhatsApp Image 2023-05-27 at 19 28 52](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/16ff1caf-736c-431e-b5b5-8484badbe22d)

**Comment by MonalikaPatnaik** [comment]
Do it!
Submit your Pr soon so that we can merge it without conflicts!
