### ISSUE TITLE
Improving the blog section with its code and better responsiveness

### ISSUE THREAD

**Issue by rohanmittal1163** [MonalikaPatnaik/UMatter#457]
**Feature idea.**
hey @MonalikaPatnaik I saw the website. it was amazing experience. I think the blog section could be more attractive.

**Describe the solution you'd like**
1. Making the blog section more attractive with the best cards.
2. Make the code sustainable and short (css is written in the form of js | scalability issues)
3. Make the blog/youtube section more user friendly and with the less code.
4. Make the blog section mre responsive and removing the horizontal scrollbar

**not responsive with a horizontal scrollbar**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/97821844/a1036d2e-b3be-4718-a1bf-dfa41877442b)

**Comment by MonalikaPatnaik** [comment]
Hey @rohanmittal1163 responsiveness related issue for the watch helpful section is already been assigned!
You can make this section look more attractive! As of now, it is looking clumsy, you can improve this section!
Thanks!
