### ISSUE TITLE
[GSSOC'23] Responsiveness and password toggle in signup and signin page

### ISSUE THREAD

**Issue by rohanmittal1163** [MonalikaPatnaik/UMatter#458]
**Describe the bug**
hey @MonalikaPatnaik , I saw the website. I found a bug about the responsiveness and and password toggle button in the signup and signin page. I am well versed with reactjs.pls assign me with this issue under GSSOC'23 conrtibution.

**Screenshort**

![image](https://github.com/MonalikaPatnaik/UMatter/assets/97821844/ce920ae5-6efa-420d-a81a-65825da01143)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/97821844/eb6ebff9-a20b-4256-9fce-58a10046b9e6)
thank you for reading.

**Comment by MonalikaPatnaik** [comment]
Hey can u check now...i think it's been resolved!

**Comment by rohanmittal1163** [comment]
@MonalikaPatnaik 
![image](https://github.com/MonalikaPatnaik/UMatter/assets/97821844/cd5ab496-e66d-4ce1-b961-ddabb25d8133)
the passoword toggle button is not in its correct place. can you assign this to me

**Comment by MonalikaPatnaik** [comment]
Okay then fix it in the signin page!

**Comment by rohanmittal1163** [comment]
Yes working on it by the end of day you will get it

**Comment by MonalikaPatnaik** [comment]
Hey..submit your PR!

**Comment by rohanmittal1163** [comment]
Hi @MonalikaPatnaik
![Screenshot_2023-06-01-08-26-29-020_com.github.android.jpg](https://github.com/MonalikaPatnaik/UMatter/assets/97821844/a4db2d9e-261c-455c-b5ed-4a9281b4a80f)

It seems you have merged the request
I once again send you the PR about this

**Comment by MonalikaPatnaik** [comment]
hey yes your PR is merged but the eye button in sign in page is still not yet fixed...could you submit a PR again?
