### ISSUE TITLE
The sign up page window has a very narrow and touches the navbar [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [MonalikaPatnaik/UMatter#461]
**Describe the bug**

![kkk](https://github.com/MonalikaPatnaik/UMatter/assets/116020663/522d31ec-188d-4f45-a2a4-efadb0a57206)

The sign up page can be improved a lot. This sing up window is too narrow and touches the navbar, which does not look very professional. I can Improve this, Please assign me this issue under GSSoC'23

**Screenshort**

**Comment by VijayalakshmiGanesh** [comment]
Hi, I would like to work on this issue. Could you please assign me this issue under GSSoC'23  label

**Comment by 1Shubham7** [comment]
I would also want to work on this issue. Please assign me this issue. I am ok with this issue being assign to me as well as @VijayalakshmiGanesh

**Comment by i-am-SnehaChauhan** [comment]
Hey @1Shubham7 we can't do that if u unable to complete it then only we will assign to someone else.
Now you can start working on this coz u raised this issue.

> I would also want to work on this issue. Please assign me this issue. I am ok with this issue being assign to me as well as @VijayalakshmiGanes

**Comment by 1Shubham7** [comment]
@i-am-SnehaChauhan 
I got it. Thanks a lot for assigning me the issue. I will surely not disappoint you.

**Comment by 1Shubham7** [comment]
@i-am-SnehaChauhan  This issue has been solved, Shall I close it?

**Comment by 1Shubham7** [comment]
I am closing it. @i-am-SnehaChauhan please reply if I should change it.
