### ISSUE TITLE
Blog page has horizontal scrollbar

### ISSUE THREAD

**Issue by Guli93** [MonalikaPatnaik/UMatter#463]
**Describe the bug**

Blog page is not responsive there is horizontal scrollbar which needs to be fixed.

please assign me this issue under Gssoc'23.

**Screenshort**
![Screenshot (137)](https://github.com/MonalikaPatnaik/UMatter/assets/102940836/832b036f-e6dd-4bb4-b4fa-1eee1290f608)

**Comment by MonalikaPatnaik** [comment]
Okay...do it then!
Submit your Pr soon!

**Comment by Guli93** [comment]
> Okay...do it then! Submit your Pr soon!

i actually did the changes in my first PR which has been merged.
