### ISSUE TITLE
Social media icons have no hover effect

### ISSUE THREAD

**Issue by Guli93** [MonalikaPatnaik/UMatter#464]
**Feature idea.**

In footer section, social media icons should have some hover effect it makes the page more dynamic and also redirection links need to be added.

pleas allow me to make these minor changes under Gssoc'23.

**Comment by i-am-SnehaChauhan** [comment]
Hey @Guli93 you can work on this issue.

**Comment by Guli93** [comment]
> Hey @Guli93 you can work on this issue.

Thanks for assigning me this issue
