### ISSUE TITLE
Sign In page text

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#469]
**Describe the bug**

increase the `font-size` of Email and password text and change the `color` as well. for top heading apply same

**Screenshort**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/80d0d9a5-c9cc-4922-a144-1429fb3f4c43)

**Comment by shivam-sharma7** [comment]
@MonalikaPatnaik

**Comment by anupdhoble** [comment]
I know how to fix this , So would like to work on this project. Please assign it to me under GSSOC'23 @shivam-sharma7

**Comment by shivam-sharma7** [comment]
I will do my own, so look for another

**Comment by shivam-sharma7** [comment]
@i-am-SnehaChauhan

**Comment by MonalikaPatnaik** [comment]
Heyy @shivam-sharma7 could you pls make a PR on #361 then will assign this issue to you!

**Comment by shivam-sharma7** [comment]
@MonalikaPatnaik #479

**Comment by IT-0824** [comment]
Sir, I would like to work on this issue, looking forward for your response.
