### ISSUE TITLE
Sign Up Page Issue

### ISSUE THREAD

**Issue by vikram-8290** [MonalikaPatnaik/UMatter#47]
Not Sign up Page Forgot Password Not Working
And Sign Up Link On Nav is Not Working

**Comment by vikram-8290** [comment]
I want to Fix This Issue Under GSSOC '23 . Could you please assign me this issue?

**Comment by Samriddhi15** [comment]
I want to fix this issue, could you please assign this issue to me?

**Comment by Mansi168** [comment]
Similar issue is already being assigned!
