### ISSUE TITLE
Blog section is unresponsive

### ISSUE THREAD

**Issue by raghavawasthi24** [MonalikaPatnaik/UMatter#473]
**Describe the bug**

The blog section is not responsive at all

**Screenshort**

![Screenshot (105)](https://github.com/MonalikaPatnaik/UMatter/assets/113261155/16b20f6c-e378-4063-9dad-9ffb5356b767)

**Comment by raghavawasthi24** [comment]
I request you to assign me this issue under GSSoC'23

**Comment by Piyusharora2003** [comment]
![Screenshot_2023-05-28-14-12-12-72_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/MonalikaPatnaik/UMatter/assets/74443858/80d11600-f6dc-4394-8ce7-03381ceaa8d3)

![Screenshot_2023-05-28-14-11-58-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/MonalikaPatnaik/UMatter/assets/74443858/14470902-7f93-420f-ac1d-aed6f92433f0)


Can i also work on this but on a separate field.
