### ISSUE TITLE
Our services section in mobile view is not visible properly.

### ISSUE THREAD

**Issue by Tusharjoshi1703** [MonalikaPatnaik/UMatter#48]
As the services section is not looking properly I will add some features to improve UI .
![Screenshot_2023-05-20-12-48-28-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/MonalikaPatnaik/UMatter/assets/103979298/3f1cbb9e-a834-4ea0-b7cc-a9175f40c32e)

**Comment by Mansi168** [comment]
go ahead @Tusharjoshi1703 you are assigned!

**Comment by Pragati-3003** [comment]
Heyy @Mansi168 
I would like to resolve this issue. 
Please assign this issue to me under GSSOC'23.

**Comment by Mansi168** [comment]
hey @Pragati-3003 this issue is already assigned as of now :(

**Comment by Pragati-3003** [comment]
> hey @Pragati-3003 this issue is already assigned as of now :(

Okay

**Comment by vk20july** [comment]
I want to work on this issue under gssoc'23 @MonalikaPatnaik mam

**Comment by MonalikaPatnaik** [comment]
It's been already done!
