### ISSUE TITLE
improve alignment of Blog search clear button

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#480]
**Describe the bug**
improve alignment of Blog search clear button

**Screenshort**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/f1584683-66d1-458b-824f-60c0d9090f56)

**Comment by i-am-SnehaChauhan** [comment]
Hey @shivam-sharma7 you can work in this.

**Comment by IT-0824** [comment]
I would like to work on this issue, looking forward for your response.

**Comment by ashutoshrana8118** [comment]
I would like to work on this issue pls assign this to me
