### ISSUE TITLE
Setup SMTP server for Contact Form Info exchange

### ISSUE THREAD

**Issue by pooranjoyb** [MonalikaPatnaik/UMatter#484]
### Description

I would like to add an `SMTP` endpoint to the `Contact Us` section.

## Outcomes : 
- The information will be diverted to the user's email address directly upon Button Click.
- Removing the Database complexities like storing the Contact Form Data in a database.
- **This will result a safe and secure information exchange without involvement of any third part software or a database**

## Implementation : 
- I will be creating an SMTP server using NodeJs and connect user requests to the backend. This will send mails to the owner of the repository.
- `SMTP` server of `GMAIL` will be used for safe and secure information exchange.

### Screenshots
![image](https://github.com/MonalikaPatnaik/UMatter/assets/90945182/94399fa3-c009-460d-aca0-95eed1ecc71d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by MonalikaPatnaik** [comment]
Okay so are u adding the backend to this right?

**Comment by pooranjoyb** [comment]
Yup, so that the Contact section could be a working form. @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Okay...you can work on this!
Thanks for Contributing!

**Comment by pooranjoyb** [comment]
> Okay...you can work on this! Thanks for Contributing!

You're welcome, will be up with the PR in a day. Thanks @MonalikaPatnaik
