### ISSUE TITLE
Eye in signin page not on his place it is out of passward box

### ISSUE THREAD

**Issue by 2020B1531074** [MonalikaPatnaik/UMatter#485]
![Screenshot (144)](https://github.com/MonalikaPatnaik/UMatter/assets/98419710/144fdc0f-53a5-42bf-a016-8fbd0b1fe257)
**Describe the bug**

**Screenshort**

**Comment by 2020B1531074** [comment]
Please assigned me

**Comment by 2020B1531074** [comment]
#485 assigned me please

**Comment by MonalikaPatnaik** [comment]
Hey it is already assigned to someone else!
