### ISSUE TITLE
Sign Up Page UI is  Looking  Bad

### ISSUE THREAD

**Issue by GleanCoder** [MonalikaPatnaik/UMatter#490]
Hello @MonalikaPatnaik  I'm a Contributor of  **[GSSoC'23]** .

 You can see  the pic how your Sign Up Page  UI is looking Bad

I would Like To Fix It  if You Assign me this , Thank You

![2023-05-28 (6)](https://github.com/MonalikaPatnaik/UMatter/assets/121458753/50aafe9a-dda9-4b0f-8827-e66a9f39f756)

**Comment by priyapahwaa** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by aniketnimkar** [comment]
even I noticed that the login form ui looks bad I have created several login forms before so 
Please assign me this issue under GSSoC-2023 i love to contribute to this issue.
