### ISSUE TITLE
Dark mode not working for Contact Us Section

### ISSUE THREAD

**Issue by AlabhyaG** [MonalikaPatnaik/UMatter#493]
**Describe the bug**
Dark mode in Contact Us section is not working, nothing is getting changed
**Screenshort**
At light mode:
![image](https://github.com/MonalikaPatnaik/UMatter/assets/98676224/e75d4d9e-438e-4445-9fce-f94e125ac462)

At dark mode:
![image](https://github.com/MonalikaPatnaik/UMatter/assets/98676224/c6912de5-fc4b-486b-94bd-72f32ddbd978)

**Comment by Abhisharmika** [comment]
@MonalikaPatnaik 
Iam a GSSoc participant.
i want to contribute to this issue ., so please assign me on this.
I'll try to make it simpler and easier.

**Comment by Mansi168** [comment]
hey @AlabhyaG thanks for raising this issue!
u can start working on it :)

**Comment by MonalikaPatnaik** [comment]
Hey @AlabhyaG is it done?? pls submit your PR by eod!

**Comment by mudrikachawla** [comment]
Hey, I am a GSSoC participant.
I want to contribute to this issue. If it's not done please assign it to me @MonalikaPatnaik.

**Comment by TechSpiritSS** [comment]
> Hey, I am a GSSoC participant. I want to contribute to this issue. If it's not done please assign it to me @MonalikaPatnaik.

hey @mudrikachawla if we don't get PR by EOD then this issue will be closed and a new issue will be assigned to add dark mode to whole site at once instead of creating issue for every individual component.
