### ISSUE TITLE
Add github social  in footer

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#497]
**Feature idea.**

Add github social  in footer and link with repo

![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/fe0aca42-5f5a-40f2-9974-4587fe088141)

**Describe the solution you'd like**

**Comment by shivam-sharma7** [comment]
@MonalikaPatnaik

**Comment by Kanchan253** [comment]
Hi @MonalikaPatnaik , I would like to work on this, kindly assign this to me.

**Comment by shivam-sharma7** [comment]
@Kanchan253 look for another issue

**Comment by aniketnimkar** [comment]
Please assign me this issue under GSSoC-2023 I love to contribute to this issue.
