### ISSUE TITLE
Want to correct spelling of “Service”

### ISSUE THREAD

**Issue by Pooja417** [MonalikaPatnaik/UMatter#503]
Want to correct spelling of “Service”, here spelling should be “Services” instead of “Service”.

https://github.com/MonalikaPatnaik/UMatter/assets/84315495/44b61de0-3508-430b-8dc6-c0cbb84d1866

Please allow me to fix this bug under GSSoC’23
@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Okay change it to..services!

**Comment by kinshuk8** [comment]
Is anyone working on this issue?

**Comment by Pooja417** [comment]
> Is anyone working on this issue?

Yes … I’m working

**Comment by MonalikaPatnaik** [comment]
Hey pls submit your PR by today itself!

**Comment by Abhishek9229** [comment]
please assign it to me
