### ISSUE TITLE
Search Section in blog page is not good

### ISSUE THREAD

**Issue by SaiyamTuteja** [MonalikaPatnaik/UMatter#505]
**Search Section is not good**

As In the blog page of your website search section UI is not good. Which creates difficulty to user for using the search in blog page given below is the screenshot of the bug.   

**![Screenshot 2023-05-28 194216](https://github.com/MonalikaPatnaik/UMatter/assets/119167105/635d4401-d74f-4bdd-bf95-bb7f3fac923d)**

As I can create a better search section which creates ease to the user. I am the Contributor **GSSOC23** if you like the bellow design then assign it to me so that i can start working on it. 

![Screenshot 2023-05-28 194700](https://github.com/MonalikaPatnaik/UMatter/assets/119167105/d0710c97-94da-4484-9dac-8c437ec90cf5)

**Comment by MonalikaPatnaik** [comment]
Hey..I liked this design..pls improve the search bar in blogs page!

**Comment by MonalikaPatnaik** [comment]
Hey is it done?? Pls submit your PR within two days !!

**Comment by SaiyamTuteja** [comment]
I will submit this.today positively
