### ISSUE TITLE
Same image in every section

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#506]
**Feature idea.**

blog section box content same title image which not looking very attractive

**Describe the solution you'd like**
I want to add different images related to a blog post,it improves the user experience and readability of the website 
Assign me this issue 
##screenshot

![84](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/147fe094-a1db-4132-aaf8-369ea9a02a5a)

**Comment by Mansi168** [comment]
@HimanshuNarware thanks for this issue!
you can start working on it!
