### ISSUE TITLE
Blog section clear button need some styling

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#507]
**Describe the bug**
The blog section button is affecting the UI of the website  the size of the button is unfixed

##solution
I want to give some basic styling to improve the properties of the button 

**Screenshort**

![83](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/fe6a946f-e3d4-4fe6-abea-9c9143a7dd87)

**Comment by MonalikaPatnaik** [comment]
Hey...it's been assigned! will assign if needed improvement!
