### ISSUE TITLE
nav bar cancel button is not visible in light mode

### ISSUE THREAD

**Issue by mrgulrez** [MonalikaPatnaik/UMatter#510]
**Describe the bug**

In light mode it is not visible
<img width="402" alt="1" src="https://github.com/MonalikaPatnaik/UMatter/assets/97864586/681fa21f-35c7-4459-bfb9-5d13832e0255">

dark mode it is visible
<img width="294" alt="2" src="https://github.com/MonalikaPatnaik/UMatter/assets/97864586/64d1dc56-9906-496c-b256-d6754b1ba467">

**Comment by mrgulrez** [comment]
Assign me to fix this issue

**Comment by Ajay-308** [comment]
please assign me this issue

**Comment by vinay-nb** [comment]
I would like to fix this issue, can you assign it to me @MonalikaPatnaik
