### ISSUE TITLE
Improve page area below the hero section

### ISSUE THREAD

**Issue by karthiknadar1204** [MonalikaPatnaik/UMatter#519]
**Feature idea.**

Ok so right now the area below the area section look good but it feels like it is not occupying enough space like it is too small for the area it is meant to occupy.
Like the about us section has a good animation but we could improve upon that.

My proposed solution:
For the about section, we put it in a white container in the dark mode and make the container along with the about us texts appear from the left with a transitioned motion instead of appearing out of thin air like right now.

Same for the our services part but it will appear in transition motion from the right instead of the present animation. Will implement the same in light mode as well.

Why:
Right now there is no proper demarkation for the about us section and the our services section, so the container transition along with the increased size might make it look more alluring and user engaging.

Please share your views on the same , would like to work out the design.

Ps: Also make the navbar sticky 

**Describe the solution you'd like**

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik @Mansi168 Your opinion on the proposed changes or something new that could be implemented

**Comment by Mansi168** [comment]
okay @karthiknadar1204 u can start working on it..but plz make sure...there would be no conflicts :')

**Comment by karthiknadar1204** [comment]
Haha sure,will try my best

**Comment by karthiknadar1204** [comment]
@Mansi168 I was terribly with an hackathon, will get working again.

**Comment by karthiknadar1204** [comment]
@Mansi168 @MonalikaPatnaik  I am trying to setup the project but running npm i is giving a lot of errors
<img width="1456" alt="Screenshot 2023-06-05 at 4 33 20 PM" src="https://github.com/MonalikaPatnaik/UMatter/assets/95973644/7bbd05a8-f9c3-4c46-9008-481c8786afb3">

How to address

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik @Mansi168 @i-am-SnehaChauhan

**Comment by karthiknadar1204** [comment]
<img width="1789" alt="Screenshot 2023-06-10 at 2 43 28 PM" src="https://github.com/MonalikaPatnaik/UMatter/assets/95973644/22e423b9-9822-40c6-a01b-294ee20235ea">
<img width="1788" alt="Screenshot 2023-06-10 at 2 43 54 PM" src="https://github.com/MonalikaPatnaik/UMatter/assets/95973644/2e72c8af-70af-4912-bbee-c4ad4c4248fa">

@Mansi168 I put the about us and the our services in a separate container as proposed, will be changing the color of the container as well, this just a demo of the changes, is this fine?

**Comment by TechSpiritSS** [comment]
Fix the color scheme, rest is good.

**Comment by karthiknadar1204** [comment]
fine will do and submit pr for review tomorrow
thank you

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik As the boxes in the services section ins increasing, should I make them into a carousel when I put them in a container? I think that would look good, opinion?

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik will share preview today evening, Thank you

**Comment by karthiknadar1204** [comment]
@MonalikaPatnaik I am done with the issue facing the issue with dynamic rendering, as for responsiveness, I have fixed the issue that was appearing with the appearance of the scrollbar, for dynamic rendering, we could open another issue and have someone else fix it, how does that sound

**Comment by karthiknadar1204** [comment]
Thank you so much,i am literally crying 🥹♥️♥️🥳🤣🤣
