### ISSUE TITLE
Social links are not working in the footer section

### ISSUE THREAD

**Issue by Aditya240302** [MonalikaPatnaik/UMatter#521]
**Describe the bug**
social links like instagram , facebook and other are not working.

**Screenshort**

**Comment by Aditya240302** [comment]
Assign me this issue under gssoc and please provide the social links , so that I can add them.
Thank You,

**Comment by MonalikaPatnaik** [comment]
Hey @Aditya240302 we are not having social links as of now..but u could add the github link in the footer github icon!

**Comment by MonalikaPatnaik** [comment]
Hey @Aditya240302 is it done?? Pls submit your PR within one day otherwise will assign it to someone else!

**Comment by MonalikaPatnaik** [comment]
Hey @karananu are u willing to add github link in the footer icon?

**Comment by MohammadBinAftab** [comment]
Sir i would like to do that, please assign me this issue and tell a little brief about the issue

**Comment by Sandeep77942** [comment]
Would like to work on the issue if it is still open.

**Comment by RitiChandak** [comment]
Hi, I have already worked on this particular issue and would like to express my interest in contributing further. If the issue is still open, I kindly request to be assigned to it under GSSOC'23.

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it

**Comment by shawwahweng** [comment]
Do you know how to write python code?
