### ISSUE TITLE
Improve Feedback form text 

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#524]
**Describe the bug**

Feedback form text not looks good so we need to increase and feedback type input should be `<textarea></textarea>` 

**Screenshort**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/ceed0ea5-78d5-4495-a814-d810c6771143)

**Comment by Ironspider42** [comment]
Hi, I can work on this issue, can you assign it to me under   GSSOC'23.

**Comment by shivam-sharma7** [comment]
look for another

**Comment by karananu** [comment]
Please assign me this under GSSoC 23. I have the knowledge and experience of required tech stack.

**Comment by Mansi168** [comment]
hey @shivam-sharma7 it is looking good to me :')
we dont require any changes here!
