### ISSUE TITLE
Making navbar sticky

### ISSUE THREAD

**Issue by trisharaj06** [MonalikaPatnaik/UMatter#525]
**Feature idea.**
Position of navbar should be fixed to the top even after scrolling, could you assign me to fix this under gssoc'23

**Comment by MonalikaPatnaik** [comment]
Hey @trisharaj06 you can start working on this!

**Comment by MonalikaPatnaik** [comment]
Hey is it done?? Pls submit your PR within one day otherwise will assign it to someone else!

**Comment by trisharaj06** [comment]
Sorry for late, due to my sem exam I was unable to give it time could you give me just two days more ?

**Comment by khushbumaheshwarii** [comment]
> Hey is it done?? Pls submit your PR within one day otherwise will assign it to someone else!

please assign me for this issue

**Comment by MonalikaPatnaik** [comment]
Okay you can do @khushbumaheshwarii

**Comment by MonalikaPatnaik** [comment]
Do it soon pls!

**Comment by khushbumaheshwarii** [comment]
> Do it soon pls!



> Do it soon pls!

sure
