### ISSUE TITLE
Adding responsiveness to the sign up page.

### ISSUE THREAD

**Issue by NightFury742** [MonalikaPatnaik/UMatter#526]
The text fields in the sign up page are overflowing  in mobile view.

I want to contribute to this issue, can you please assign it to me?

![Screenshot from 2023-05-29 16-16-27](https://github.com/MonalikaPatnaik/UMatter/assets/119070798/ce480f57-7b3b-4679-ae7c-d9639cf46395)

**Comment by karananu** [comment]
Please assign me this under GSSoC 23. I have the knowledge and experience of required tech stack.

**Comment by MonalikaPatnaik** [comment]
Okay @NightFury742 you can start working on this!

**Comment by MonalikaPatnaik** [comment]
It is done now!
