### ISSUE TITLE
No space between Search bar and clear button [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [MonalikaPatnaik/UMatter#527]
**Describe the bug**
There is No space between Search bar and clear button.

**Screenshot**
![myissue](https://github.com/MonalikaPatnaik/UMatter/assets/116020663/e0d4f7f5-6e5e-49de-b955-57a83f2c215b)

I have solved this issue and the output looks like : 
![muissuesolved](https://github.com/MonalikaPatnaik/UMatter/assets/116020663/0d7e8f3a-f501-425e-b1ae-e107fa3da4fc)

I have already solved it, Please assign me this issue so that I can commit my changes and get points in GSSoC.

**Comment by 1Shubham7** [comment]
Please assign me this issue.

**Comment by Mansi168** [comment]
hey @1Shubham7 plzz dont make pr until u r being assigned :')

**Comment by 1Shubham7** [comment]
OK, I didn't knew, I am sorry for that. Will this PR still count on the GSSoC leaderboard?
