### ISSUE TITLE
Misspell in "Screenshot" CAN ONLY BE CORRECTED BY PROJECT ADMINS.

### ISSUE THREAD

**Issue by 1Shubham7** [MonalikaPatnaik/UMatter#533]
**Describe the bug**
The template mentors give us for writing an issue. There is a small misspell in it. Its a small error so I don't think I deserve to write GSSoC in it, Also I can't solve it, only the mentors can.

**Screenshort**   <- This is the error
![misspellisuue](https://github.com/MonalikaPatnaik/UMatter/assets/116020663/a7ca225a-a0aa-498e-af31-062cd35ad741)

**Comment by MonalikaPatnaik** [comment]
Okay we will fix it!
Thanks for letting us know!

**Comment by 1Shubham7** [comment]
Thank you @MonalikaPatnaik for acknowledge.
