### ISSUE TITLE
No length on password

### ISSUE THREAD

**Issue by RushiShelke** [MonalikaPatnaik/UMatter#534]
**Describe the bug**

Hey when I try to set the password while creating account I noticed that you haven't kept any password limit.
You need to decrease password length :There are two reasons for limiting the password size. For one, hashing a large amount of data can cause significant resource consumption on behalf of the server and would be an easy target for Denial Of Service attack.
Normally all sites have a password minimum to maximum length like 72 characters limit or 48 limit to prevent Denial Of Service attack. in my sql but in weblate registration page there are no limitation. Let me know if you need any more details.
This is typically not DoS, but a vulnerability which may lead to DoS attack.

**Screenshort**
![Screenshot 2023-05-29 191422](https://github.com/MonalikaPatnaik/UMatter/assets/114470198/5309da21-47fa-40f7-8a2c-49fac8b1de14)

Assign this issue to me under GSSoC'23!

**Comment by imharshitg07** [comment]
I can work on this issue. Please assign this to me

**Comment by MonalikaPatnaik** [comment]
So, what u will do? add any kind of validation to it ? I think someone is already working on this!

**Comment by imharshitg07** [comment]
Dear Monalika Patnaik,

I hope this email finds you well. As per your request regarding the password length limitation issue on the registration page, I have conducted an analysis and formulated a proposed solution. Here are the steps that I suggest to address this concern:

Conduct a thorough analysis: Review the current system architecture, password handling mechanisms, and potential impact of implementing a password length limit. This will help us understand the existing infrastructure and any limitations that need to be considered.

Determine an appropriate password length limit: Based on industry best practices and standards, I recommend enforcing a minimum and maximum password length that strikes a balance between security and usability. For example, setting a minimum length of 8 characters and a maximum length of 72 characters is commonly recommended.

Implement server-side validation: Modify the backend code of the registration page to enforce the desired password length limit. This validation should occur on the server side to ensure consistency and prevent any bypassing attempts by manipulating client-side scripts.

Update user interface and error handling: Enhance the user experience by updating the registration page's interface to reflect the password length requirements. Clear instructions and error messages indicating the password length limit should be provided during the registration process.

Communicate changes to users: If we have existing users, it is crucial to notify them about the updated password length limit and encourage them to update their passwords accordingly. Educating users on the importance of creating strong and secure passwords will help strengthen overall account security.

Perform testing and monitoring: Thoroughly test the updated registration process to ensure that the password length validation works as intended. Additionally, we should monitor the system for any potential performance issues or vulnerabilities, addressing them promptly.

Consider additional security measures: While addressing the password length limitation, it would be beneficial to explore other security measures, such as enforcing password complexity requirements and implementing multi-factor authentication (MFA). These measures will enhance the overall security of user accounts.

I believe implementing these steps will help us mitigate the password length limitation issue and enhance the security of the registration page. However, I recommend discussing these proposed changes with the development team to assess the feasibility and align them with our technical capabilities and priorities.

Please let me know if you have any further questions or if you require additional information. I'm available to discuss this solution further and work towards its implementation.

Thank you for your attention to this matter. Kindly consider assigning this issue to me.

Best regards,

Harshit Kumar Girdhar

**Comment by MonalikaPatnaik** [comment]
Hey pls check i think it's been already resolved by adding validation to the sign up page..lmk if it doesn't!
