### ISSUE TITLE
Redesign Contact Us Page

### ISSUE THREAD

**Issue by prjailani** [MonalikaPatnaik/UMatter#536]
**Feature idea.**
Our site's current contact us page doesn't look good. I'll redesign it beautifully. I am a GSSOC Contributor. Kindly assign this issue to me.

**Comment by MonalikaPatnaik** [comment]
Okay..you can start working on this!

**Comment by prjailani** [comment]
![Untitled](https://github.com/MonalikaPatnaik/UMatter/assets/76675034/e4a22453-d833-4436-8b89-0448da5b34fd)
Hi mam, Is this UI ok, or any improvement needed. 
Here is the Figma URL - https://www.figma.com/file/NH2ajOG6oih63Tf5IguVfT/Untitled?type=design&t=FWiQdXyIOyctE76H-0 .
Thanks!!

**Comment by i-am-SnehaChauhan** [comment]
Hey @prjailani it's looking good you can make it
