### ISSUE TITLE
Improve the UI of the search bar

### ISSUE THREAD

**Issue by Prakriti2003** [MonalikaPatnaik/UMatter#537]
**Describe the bug**
The current design of the search bar is not aesthetically pleasing.  I can help to improve the design of the search bar.

Please assign me this issue under GSSOC'23.
**Screenshort**
![2023-05-29 (7)](https://github.com/MonalikaPatnaik/UMatter/assets/96686092/e20e4711-cd26-4b43-a9be-49d6593c1d9d)

**Comment by MonalikaPatnaik** [comment]
Hey..this is already been assigned to someone else!
