### ISSUE TITLE
Sign in is not working

### ISSUE THREAD

**Issue by Prakriti2003** [MonalikaPatnaik/UMatter#538]
**Describe the bug**

After signing in it should redirect to home page page nothing is happening after clicking on continue. Also when forgot password is clicked no OTP is received on email.

**Screenshort**

![2023-05-29 (9)](https://github.com/MonalikaPatnaik/UMatter/assets/96686092/332250f9-358e-4880-8754-24dc00de700c)
![2023-05-29 (10)](https://github.com/MonalikaPatnaik/UMatter/assets/96686092/efed8eb9-3a5f-4e5e-9d87-a5b2cb1ae443)

**Comment by imharshitg07** [comment]
I can fix this issue.
Please assign this to me

**Comment by MonalikaPatnaik** [comment]
hey it's been working!
