### ISSUE TITLE
Multiple sign up for already existing users

### ISSUE THREAD

**Issue by Prakriti2003** [MonalikaPatnaik/UMatter#539]
**Describe the bug**
There is no provision to avoid multiple times sign up from the same email id.
Please assign me this issue under GSSOC'23. I can help to resolve this problem.

**Comment by MonalikaPatnaik** [comment]
Okay..you can start working on this!

**Comment by vk20july** [comment]
@MonalikaPatnaik can i do this task under gssoc'23

**Comment by MonalikaPatnaik** [comment]
Okay @vk20july you can work on this..
Thanks
