### ISSUE TITLE
Connect with friends

### ISSUE THREAD

**Issue by vikram-8290** [MonalikaPatnaik/UMatter#54]
hey, @Mansi168  I want to contribute under GSSOC 23 and Complete the Connect with friends please Assign this to me.

**Comment by Mansi168** [comment]
ok @vikram-8290 u r assigned!

**Comment by PayalPadmalyaPrusty** [comment]
@Mansi168 I want to contribute.Please provide some description about this issue and please assign me

**Comment by PayalPadmalyaPrusty** [comment]
@Mansi168 I want to contribute.Please provide some description about this issue and kindly assign me

**Comment by i-am-SnehaChauhan** [comment]
Hey, @vikram-8290 are u working on this else I have to assign it to someone else.

**Comment by vikram-8290** [comment]
Hii @i-am-SnehaChauhan ,
Yes I am working on this I have designed the layout
,Give me some more time as my college internals are currently going on.

**Comment by i-am-SnehaChauhan** [comment]
@vikram-8290 okay no problem do it ASAP.

**Comment by vikram-8290** [comment]
Hiii @Mansi168 ,
I want some help regarding the code base, i am able to understand its working. It will greatful if you help me so i can finish my task.
Thank you

**Comment by MonalikaPatnaik** [comment]
Hey @vikram-8290..how can I help just lmk?
Also, it's not mandatory to complete the whole page in one go..you can make a simple page and add further improvemnts to it in further issues..
