### ISSUE TITLE
Improve UI of Watch Videos Section

### ISSUE THREAD

**Issue by Prakriti2003** [MonalikaPatnaik/UMatter#540]
**Feature idea.**

I can improve the Ui of the watch videos section 

**Describe the solution you'd like**

Improvement can be done by adding carousel and cool animations to make it more attractive.

Please assign me this issue under GSSOC'23.

**Comment by Prakriti2003** [comment]
Please add GSSOC'23 label to this issue.

**Comment by ePSA-eJya** [comment]
I would want to work on this issue @TechSpiritSS @MonalikaPatnaik .i am a gssoc contributor. please assign this to me.
