### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by bhaskarkumar1** [MonalikaPatnaik/UMatter#541]
**Describe the bug**
In your Readme.md section there is no any guidance for how to start and  run this on local System and How to create a pull request.  So I want to update the Readme.md

So, Please assign me this task, So that I can work on it.

**Comment by MonalikaPatnaik** [comment]
Hey for this we have separate Contributing guide for this-- Contributing.md

**Comment by bhaskarkumar1** [comment]
yes I checked Contributing.md and want to add npm i and npm start to run this project on local system
