### ISSUE TITLE
country code in contact number

### ISSUE THREAD

**Issue by shruuti321** [MonalikaPatnaik/UMatter#542]
**Feature idea.**

Most of the websites asking for contact numbers also ask for the country codes to ensure the relevance of the number. This will help to widen the reach of the website globally and provide more real time user experience.

So i would request you to assign me this task of adding a column of country code before the contact number under GSSOC'23
![umatter](https://github.com/MonalikaPatnaik/UMatter/assets/114770273/081f9058-c9f4-4112-8c50-5388ca565571)

**Comment by MonalikaPatnaik** [comment]
Okay you can start working on this!
