### ISSUE TITLE
Update Testmonial Docs

### ISSUE THREAD

**Issue by kumarankit999** [MonalikaPatnaik/UMatter#543]
Testimonials Section is being Empty and no one testimonial is there.

It should be like a photo, and a floating testimonial which will be exactly bottom to his Picture which will be in circular shape

![image](https://github.com/MonalikaPatnaik/UMatter/assets/111564362/3060db2d-f82a-46b2-938e-f98002534ed5)

**Comment by sargam08** [comment]
I want to work on this issue. Please assign it to me.
