### ISSUE TITLE
Improve Blog Page Styling

### ISSUE THREAD

**Issue by kumarankit999** [MonalikaPatnaik/UMatter#544]
**Describe the bug**

In the Blogs Page, if we see below there is been a required Margin had to be done. It will be needed some 10px margin and padding, after that it will be looking good.

![image](https://github.com/MonalikaPatnaik/UMatter/assets/111564362/9e38fcc7-36e4-4260-ba88-c5270187d593)

![image](https://github.com/MonalikaPatnaik/UMatter/assets/111564362/b8f88707-92fe-4952-8fb9-d3e55ef222a0)

**Comment by manshasinghal** [comment]
In the Blogs Page, I want to add some css styling that will look good please assign this issue to me

**Comment by manshasinghal** [comment]
In the Blogs Page, I want to add some css styling that will look good please assign this issue to me

**Comment by MonalikaPatnaik** [comment]
Hey @kumarankit999..this is been already done!You can raise new issue if u want to change the UI
