### ISSUE TITLE
🐛 FIX - IMPROPER TRANSITION EFFECT

### ISSUE THREAD

**Issue by 0xabdulkhalid** [MonalikaPatnaik/UMatter#545]
**Describe the bug**

- The bug is about the improper transition which was applied on social icons on footer, the transition is not working properly.
- This affects the user experience, i can fix this issue
- I added before and after gif images for better understanding, the after part has been edited on developer console

**Screenshort**

|||
| :--: | :--: |
|**BEFORE** |![before](https://github.com/MonalikaPatnaik/UMatter/assets/92252895/c52f598f-d160-4042-bb3a-6f643b39867a) |
| **AFTER** | ![after](https://github.com/MonalikaPatnaik/UMatter/assets/92252895/7f389b8f-bf4b-4570-85d6-a31987db5048) |

**Postscript :**
- I'm a participant of `GSSoC'23` so kindly assign this issue to me for further development

**Comment by MonalikaPatnaik** [comment]
Yes..it's looking good...u can start working on this!

**Comment by 0xabdulkhalid** [comment]
Glad you to see that you have assigned me, I will make the work done within 1hr.

### For your attention ⚠️ 
- The label `GSSOC'23` is not validated label, You want to update the label as `gssoc23`.
- For more details you can contact the Gssoc'23 Discord Moderator [MR.Gurjeet](https://linkfree.eddiehub.io/gurjeetsinghvirdee)
