### ISSUE TITLE
add database using Nodejs 

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [MonalikaPatnaik/UMatter#546]
**Feature idea.**

The login credentials of the user didn't store anywhere therefore sign-in option is not working. 
**Describe the solution you'd like**
we can add a database to store user information. [GSSOC'23]

**Comment by Rishita1304** [comment]
The login credentials of the user didn't store anywhere therefore sign-in option is not working. we can add a database to store user information. Please assign me this issue. Thank you!

**Comment by shivaniyuvrajyadav** [comment]
Hey @AkankshaAI which part I have to do as you have assign this issue to both of us??
