### ISSUE TITLE
Create Testimonials Section In the main page

### ISSUE THREAD

**Issue by abhi03ruchi** [MonalikaPatnaik/UMatter#548]
**Feature idea.**
I would like to create the testimonial section for the website .

Right Now , it is blank.

https://github.com/MonalikaPatnaik/UMatter/assets/105661636/4c4e1fd3-9d2d-4513-992e-0067b933daca

**Describe the solution you'd like**
 I would add an automatic carousel in there. This would improve user experience and engagement.

**Comment by i-am-SnehaChauhan** [comment]
Hey @abhi03ruchi  this is similar issue to #272 please msg there Thanks :)
