### ISSUE TITLE
Off centre footer

### ISSUE THREAD

**Issue by ATOMworkplace** [MonalikaPatnaik/UMatter#550]
**Describe the bug**

In the footer of the homepage, icons are off-center and should be directly above the text Umatter as it is more of an even pattern that is soothing to see and engages users.

**Screenshort**
![Screenshot 2023-05-30 142158](https://github.com/MonalikaPatnaik/UMatter/assets/114564628/00b7651d-00a9-45ce-9a67-6459c576fbaa)

**Comment by ATOMworkplace** [comment]
I would like to solve this issue as a GSSOC'23 participant. Please assign me this issue

**Comment by MonalikaPatnaik** [comment]
Okay @ATOMworkplace just align the icons to the center!

**Comment by ATOMworkplace** [comment]
> Okay @ATOMworkplace just align the icons to the center!

Thanks for assigning me this issue. Can you please provide me the index.html of this website which I can access through the live server on vs code.

**Comment by MonalikaPatnaik** [comment]
Okay so this is a react site..you have to run npm start in order to see it in your localhost!
You can fix the footer in src/components/footer

**Comment by ATOMworkplace** [comment]
> Okay so this is a react site..you have to run npm start in order to see it in your localhost! You can fix the footer in src/components/footer

ok thanks for help
