### ISSUE TITLE
Improvement of Cards on the blog page

### ISSUE THREAD

**Issue by 007aneesh** [MonalikaPatnaik/UMatter#551]
So I think the animations on these cards are not soothing. So I want to improve that @MonalikaPatnaik @Mansi168 
So please assign this to me under gssoc label.
Thanks

![image](https://github.com/MonalikaPatnaik/UMatter/assets/90706436/67cf06c3-46c1-4c6b-a6dd-9b3f335bf7ac)

**Comment by 007aneesh** [comment]
Yes

**Comment by MonalikaPatnaik** [comment]
It's great..could you propose a video of cards to which u want to change?

**Comment by 007aneesh** [comment]
Will share it within two days

**Comment by MonalikaPatnaik** [comment]
hey it would be gr8 if u can improve the cards UI something similar like this?
https://www.loom.com/share/989860c2f0e84169aeeab97e0b71b73b

**Comment by 007aneesh** [comment]
Okay @MonalikaPatnaik working on it! 👍

**Comment by 007aneesh** [comment]
Please add labels on this issue also. Thanks
