### ISSUE TITLE
less visibility on Hovering over github button in footer 

### ISSUE THREAD

**Issue by Shreyans2004** [MonalikaPatnaik/UMatter#552]
**Describe the bug**
When the Github button is hovered ,it is becoming fully white and the github icon is not visible

**Screenshort**
![WhatsApp Image 2023-05-30 at 19 02 37](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/e89898e2-7048-48d5-ad28-440ccd84e0da)

 
I  can add different color on hovering so that it looks better.Can you assign this task to me?

**Comment by Dani2003** [comment]
Hi i am interested in working upon this issue can u assign this to me.

**Comment by sumitkr2000** [comment]
@MonalikaPatnaik  I can fix this issue quickly. Please assign me this issue.
