### ISSUE TITLE
[GSSoC'23] Fixing the Navbar position to stay at top while scrolling

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [MonalikaPatnaik/UMatter#553]
**Feature idea.**
On clicking the home option in navbar it doesn't redirect and the Navbar stays open which makes the site appear stuck .

Also the Navbar is not accessible on scrolling as it gets scrolled with home page it makes redirection for the user pretty tough.

**Describe the solution you'd like**
The redirection on clicking the home button can be fixed by adding the correct link redirection.

The Navbar getting scrolled can be fixed by placing it position as fixed wrt the screen.

I am a GSSoC contributor and have also previously worked on this and would love to contribute more.

![IMG_20230530_192303](https://github.com/MonalikaPatnaik/UMatter/assets/97378312/dd2fa77d-ddbb-441e-b38e-c986b1bace80)

![IMG_20230530_192328](https://github.com/MonalikaPatnaik/UMatter/assets/97378312/808cbf35-7ffa-4858-847c-cec12bc1b3a4)

**Comment by utkarshgupta04092003** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.
Kindly provide me the opportunity to work on the issue.

**Comment by MonalikaPatnaik** [comment]
Hey similar issue is already been assigned!
