### ISSUE TITLE
Blog section clear button size issue

### ISSUE THREAD

**Issue by rimi0602** [MonalikaPatnaik/UMatter#560]
**Feature idea.**

****
The Clear button in blogs section doesn't have any kind of hover effect which makes it difficult to understand whether or not the button is working. It also is bigger than the search box so the size needs to be as per requirement i.e smaller than the search box.

**Describe the solution you'd like**
I'd like to workon correcting the clear button size and adding an effect on it 
@MonalikaPatnaik

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
