### ISSUE TITLE
Read more hyperlink

### ISSUE THREAD

**Issue by rimi0602** [MonalikaPatnaik/UMatter#561]
**Describe the bug**

There are no attached hyperlinks to readmore section. To have original blogs that can actually help people with depression and anxiety would help them. 

**Screenshort**
<img width="955" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/110307938/af8014aa-569b-4228-a13b-6af917f69139">
 
Therefore I'd like to add real hyperlinks to the blog section for people to read. @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Okay then add the links to it!

**Comment by MonalikaPatnaik** [comment]
Heyy is it done?? pls submit your PR within two days!!! otherwise will assign it to someone else

**Comment by Abhishek9229** [comment]
please assign it to me

**Comment by vk20july** [comment]
@MonalikaPatnaik mam can I do this task under gssoc'23

**Comment by Dimple-01** [comment]
I want to work on this issue. 
I will fix this within a day.
Please assign this work to me.
