### ISSUE TITLE
Testimonial cards 

### ISSUE THREAD

**Issue by rimi0602** [MonalikaPatnaik/UMatter#563]
There are no testimonial cards available on the umatter site. 
sol: Here's an idea 
![image](https://github.com/MonalikaPatnaik/UMatter/assets/110307938/8e96ff38-069e-4dbd-b167-a9a5369fe2bc)
@MonalikaPatnaik

**Comment by ShubhaSwarup** [comment]
Please assign this issue to me

**Comment by MonalikaPatnaik** [comment]
hey @rimi0602 you can work on this..pls submit your PR within two days!

**Comment by MonalikaPatnaik** [comment]
Hey @ShubhaSwarup are u willing to take up this issue?
