### ISSUE TITLE
Handling duplicate lines of code & need to define Formlabel

### ISSUE THREAD

**Issue by imsoumik03** [MonalikaPatnaik/UMatter#564]
- There are too many duplicate lines of code which hit error to run the application.
- Also it need to define **Formlabel** at `SignupElement.js` .

## Solution
*I am going to make 2 commits*---
>Commit_1

- I will comment out all the duplicate codes .
-  I will define **Formlabel** at `SignupElement.js` .

>Commit_2

- I will remove all commented lines to maintain the IDE code properly with less scroll up-down . 

*If you would like I want you to assign this issue to me as a GSSOC_2023 contributor.*

**Comment by MonalikaPatnaik** [comment]
Heyy..yes ik there was issues with the code..it's fixed now!
