### ISSUE TITLE
Enhancing Content for the wesbite

### ISSUE THREAD

**Issue by tanya172** [MonalikaPatnaik/UMatter#568]
Hello, I would like to enhance the content on the website. As the vision of the website is great and efficacious, so should be the content. 
I can help in writing some catchy lines for the web page and improve the SEO of the website. 
Kindly, allow me to do the necessary changes.

**Comment by tanya172** [comment]
Thank you for your response

**Comment by tanya172** [comment]
[image: image.png]

Why is this error being there?

**Comment by tanya172** [comment]
Why did you close the issue.
Did u take it away from me?

**Comment by TechSpiritSS** [comment]
The PR was merged so the issue gets closed

**Comment by tanya172** [comment]
Ok, thanks for the update.
