### ISSUE TITLE
footer section is not responsive

### ISSUE THREAD

**Issue by Varghab** [MonalikaPatnaik/UMatter#57]
The footer is neither responsive for mobile nor for tablet. 
**I can fix this issue and make this responsive, please assign it to me under GSSoC'23 label.**
![Screenshot 2023-05-20 134128](https://github.com/MonalikaPatnaik/UMatter/assets/59419650/bbe5fa4b-2d66-4188-915d-e9299b5e1519)

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by bleep123** [comment]
Hi, 
I would like to work on this issue. Please assign it to me.

**Comment by Tathagt** [comment]
I would like to work on this issue under GSSOC'23.
Please assign me this issue
