### ISSUE TITLE
"Sign In" and "Sign Up" Buttons Border Removal

### ISSUE THREAD

**Issue by iamRabia-N** [MonalikaPatnaik/UMatter#570]
**Feature idea.**
The design of both buttons is nice but it can improved by removing black color border which is creating conflict with overall theme of the website. By removing it, the overall look of the homepage will be even better.

**Describe the solution you'd like**
Removal of black color border around both the buttons or choosing another light color border which matches with the theme of the website.

**Current Design**
![ss (2)](https://github.com/MonalikaPatnaik/UMatter/assets/115794049/4906303c-a5c4-4499-a4e5-6082d7b5ba19)

**Expected Updated Design**
![ss (1)](https://github.com/MonalikaPatnaik/UMatter/assets/115794049/6ae74f02-1fd8-4461-a489-74f4a0ee1803)

**Comment by i-am-SnehaChauhan** [comment]
Hey @iamRabia-N  I don't think its required it look nice to us u can find other issue Thanks :)

**Comment by i-am-SnehaChauhan** [comment]
OK  fix it @iamRabia-N

**Comment by Snigdha2712** [comment]
Please assign this project to me. i will fix the issue
