### ISSUE TITLE
Night mode is not working in Blogs page

### ISSUE THREAD

**Issue by PVBharadwaj** [MonalikaPatnaik/UMatter#572]
**Describe the bug**

On the blogs page, night mode is not changing the screen to a dark theme. 

**Screenshort**

 
<img width="952" alt="Screenshot " src="https://github.com/MonalikaPatnaik/UMatter/assets/117581755/0d021ecc-e075-45e8-a403-be9ec6434e1f">

**Comment by PVBharadwaj** [comment]
I would like to work on this issue. Please assign me this issue under GSSoC'23 @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
Hey it's been fixed i think!
