### ISSUE TITLE
Reorder navbar component elements

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#573]
**Feature idea.**

In the following image we can see order of navbar elements But I think it should be like `Home` `Services` `Testimonials` `About` `Blog` for now, and Feedback should be moved in footer Contact section

**Describe the solution you'd like**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/3fac6c15-3b3a-439d-b77a-58f3b4650e21)

**Comment by shivam-sharma7** [comment]
@MonalikaPatnaik

**Comment by Snigdha2712** [comment]
Please assign this project to me. i will fix the issue

**Comment by MonalikaPatnaik** [comment]
Hey sorry but I think it's not required...Also changes like typo change or small additions( changes in margin ,padding etc) are not counted under GSSOC as per instructions..
@AkankshaAI I think it is not required as of now!
