### ISSUE TITLE
[GSSOC'23] Fixing the SignUp page

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [MonalikaPatnaik/UMatter#574]
**Feature idea.**
The sign up page needs to be fixed a lot.
The input fields are not proportional and it makes the design look ugly. Also it is not responsive to screen sizes.

**Describe the solution you'd like**
All the inputs fields should be proportional to make the design look even.
Also effect can be added when an input is in focus.
The design breaks when viewed on smaller screens.

I would be willing to work on these issues and hence fixing the whole signup page and adding responsive design to it

![Screenshot_2023-05-31-12-51-28-870_com android chrome](https://github.com/MonalikaPatnaik/UMatter/assets/97378312/47c25ada-d07d-43d7-a3ea-e978d168ae23)

**Comment by Siddhant422** [comment]
hey, I wanted to contribute to this issue under GSsoc'23, can you please assign this issue to me.
I have made login and sign-up page in other issue. The webpages are responsive. I am attaching the screenshot of the page for examples.
![image](https://github.com/MonalikaPatnaik/UMatter/assets/98004129/209c77ca-bdb4-41f0-9571-1b01cac88af2)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/98004129/1763054f-a8f1-4c6f-9f83-f53b2fb75398)

**Comment by MonalikaPatnaik** [comment]
Hey hey i think only single person needs to be assigned for an issue

**Comment by MonalikaPatnaik** [comment]
@rishabhchaudhary0210 you can fix the responsiveness of signin sign up page!
@Siddhant422 i suggest you to open a new feature request for this!
Thankyou!

**Comment by Siddhant422** [comment]
Since rishabh has not responded, @MonalikaPatnaik Can you assign this project to me.

**Comment by rishabhchaudhary0210** [comment]
Hey @MonalikaPatnaik I have started working on this and would issue the PR till tomorrow Thanks for assigning me!!!
