### ISSUE TITLE
Minor issue in Sign in page

### ISSUE THREAD

**Issue by saijahnavir** [MonalikaPatnaik/UMatter#575]
**Describe the bug**

The password visibility toggle in the sign in page is aligned with email rather than password. Can you assign this to me under GSSOC'23?

**Screenshot**

 

![Screenshot (12)](https://github.com/MonalikaPatnaik/UMatter/assets/105307350/0432221d-88a7-4e33-a16c-ac91e3ca6a06)

**Comment by abhiraj-ku** [comment]
Hey is anyone working on this issue . I want to fix this issue

**Comment by MonalikaPatnaik** [comment]
It's been fixed now!
