### ISSUE TITLE
Inconsistency in the Home Screen

### ISSUE THREAD

**Issue by Prajwal0225** [MonalikaPatnaik/UMatter#58]
### The text is not properly centered, and there is an issue with the alignment at the lower part of the image.

**Current Home Screen**⤵️ 

![change require](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/92148114-993b-4a11-9652-9919b42247e1)

**Proposed Modification** ⤵️  

![new Home page](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/952dd8e7-060b-4e8a-b13a-88e47cca7916)

I'm interested in working on this issue. Could you please assign it to me?

**Comment by MonalikaPatnaik** [comment]
Hey sure..You can work on this!
Thanks!
