### ISSUE TITLE
Contact us page not looking attractive

### ISSUE THREAD

**Issue by Shreyans2004** [MonalikaPatnaik/UMatter#583]
**Feature idea.**

**Describe the solution you'd like**
The contact us page is not looking so much attractive due to its white background.
![WhatsApp Image 2023-05-31 at 21 42 17](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/9c9b786c-cefe-4175-a34c-711b0239b1e9)
Can you assign this task to me?

I can change its background so that is looks better

**Comment by i-am-SnehaChauhan** [comment]
Hey @Shreyans2004, Can u share ur design with us, like what u want to change in it?

**Comment by Shreyans2004** [comment]
Yes ,Sure.
![WhatsApp Image 2023-06-02 at 00 11 10](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/ca69b16d-227f-4136-91ac-f8f9063dd081)
On hovering above the submit button
![WhatsApp Image 2023-06-02 at 00 11 17](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/012925d2-f623-43ec-a590-8cca5548895e)
Now can you assign this task to me ?
