### ISSUE TITLE
Clear button on feedback page is not properly aligned

### ISSUE THREAD

**Issue by sumitkr2000** [MonalikaPatnaik/UMatter#584]
**Describe the bug**

Hey, @MonalikaPatnaik The clear button is not properly aligned on the feedback page as you can see on the website. I wan to work on this issue. Please assign me this issue. Thank you!

**Screenshort**

![Screenshot (822)](https://github.com/MonalikaPatnaik/UMatter/assets/100675296/a7929e68-ef97-48f0-9439-a3af169f118a)

**Comment by MonalikaPatnaik** [comment]
It's been aligned now!

**Comment by sumitkr2000** [comment]
okay i am closing this issue.
