### ISSUE TITLE
Social icons links now working

### ISSUE THREAD

**Issue by sumitkr2000** [MonalikaPatnaik/UMatter#585]
**Describe the bug**

Hey, @MonalikaPatnaik it seems that the links of the social icons are not working. Please assign me this issue. I want to add links to it. Thank you!

**Screenshort**

**Comment by i-am-SnehaChauhan** [comment]
Hey @sumitkr2000, We haven't created any social media accounts yet.
You can find other other issue Thanks :)

**Comment by sumitkr2000** [comment]
Atleast add the repo kf github in GitHub icon.

**Comment by MonalikaPatnaik** [comment]
> Atleast add the repo of github in GitHub icon.

Hey yess ..but it's been already assigned!

**Comment by sumitkr2000** [comment]
Okay cool ...i have raised other issues also...pleas assign me those
