### ISSUE TITLE
Add testimonial section

### ISSUE THREAD

**Issue by sumitkr2000** [MonalikaPatnaik/UMatter#586]
**Feature idea.**

Hey @MonalikaPatnaik I want to add a testimonial section to the home page. Please assign me this issue. Thank you!

**Describe the solution you'd like**

**Comment by Rishita1304** [comment]
I want to add a testimonial section to the home page. Please assign me this issue.

**Comment by i-am-SnehaChauhan** [comment]
Hey @sumitkr2000, This issue is similar to #272 
Please msg there. Thanks :)
