### ISSUE TITLE
GitHub Icon visibility in Footer

### ISSUE THREAD

**Issue by 9520prashant** [MonalikaPatnaik/UMatter#588]
**Describe the bug**

when you hover at github icon in footer then it is not visible Hey @MonalikaPatnaik kindly assign me this issue under gssoc.

**Screenshort**

![Screenshot (282)](https://github.com/MonalikaPatnaik/UMatter/assets/99237795/7cc038ec-a3ef-45e7-8a8b-dd9c5de24c05)

**Comment by i-am-SnehaChauhan** [comment]
Hey @9520prashant, u can start working on this.
