### ISSUE TITLE
Unwanted Dark/Light button on Blogs page

### ISSUE THREAD

**Issue by sumitkr2000** [MonalikaPatnaik/UMatter#596]
**Describe the bug**

Hey, @MonalikaPatnaik There is an unwanted dark/light button on the blogs page. I have attached a screenshot. Please assign me this issue to fix it. Thank you!

**Screenshot**

![Screenshot (828)](https://github.com/MonalikaPatnaik/UMatter/assets/100675296/7143b7b8-4b57-45a3-b289-bc43d0bf6e1c)

**Comment by MonalikaPatnaik** [comment]
Okay remove it!
