### ISSUE TITLE
Improving Links of social handles

### ISSUE THREAD

**Issue by Bharadwajshivam28** [MonalikaPatnaik/UMatter#6]
![Screenshot from 2023-05-20 00-47-56](https://github.com/MonalikaPatnaik/UMatter/assets/108119109/2f31aa66-c95e-426f-8d96-bdd28f07a673)

All the social media links are broken . If there is no link then we must remove the hyperlink from it.

Please assign it to me under GSSOC23

**Comment by Thrillseekr** [comment]
Hey @MonalikaPatnaik ,
I'm Darshan Jain, and I'm thrilled to be a part of this GSSOC'23. I bring along my expertise in HTML5, CSS, PHP, Bootstrap, and creativity too. I'm passionate about open source projects and eager to contribute and collaborate with fellow enthusiasts.

Can you please assign this to me.

**Comment by AmanMittal-3305** [comment]
hii
please assign me this issue

**Comment by Bharadwajshivam28** [comment]
@Mansi168 can i work on it as I have opened this issue

**Comment by i-am-SnehaChauhan** [comment]
@Bharadwajshivam28 you can start working on this issue

**Comment by MonalikaPatnaik** [comment]
hey @Bharadwajshivam28..are u done with your changes?

**Comment by Thrillseekr** [comment]
> hey @Bharadwajshivam28..are u done with your changes?

If not done, please assign this to me.

**Comment by i-am-SnehaChauhan** [comment]
Hey @Bharadwajshivam28, are you done with your changes otherwise we will assign this to someone else.

**Comment by samSoumyajitD** [comment]
Hi! I m a GSSOC'23 contributor. Want to help resolve this issue and contribute. If the links aren't improved yet, please assign it to me. Thanks!

**Comment by MonalikaPatnaik** [comment]
I think we don't need this!
