### ISSUE TITLE
Homepage Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [MonalikaPatnaik/UMatter#60]
The homepage interface is nice, but it can be improved by making some design adjustments. Working on the design of the homepage, I would like to make it even better.

**Comment by iamRabia-N** [comment]
I would like to work on this issue as a part of GSSOC-23.

**Comment by ashutoshgithubs** [comment]
Hello @MonalikaPatnaik, @Mansi168 The home page will be more attractive and user-friendly if I add the Parallax effect to it. So I can help to improve this page. So please assign this task to me.

**Comment by Mansi168** [comment]
home page is already assigned :(...will assign you if i need more improvements :)
