### ISSUE TITLE
improve the positioning of contact us 

### ISSUE THREAD

**Issue by SurbhiMotwani23** [MonalikaPatnaik/UMatter#609]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91596996/f719abe8-1967-4d22-a35d-1c1bcfa3f31b)
the about us ,contact us and videos are not in line.

**Comment by SurbhiMotwani23** [comment]
please assign me this issue @MonalikaPatnaik

**Comment by Snigdha2712** [comment]
Please assign this project to me. i will fix the issue

**Comment by MonalikaPatnaik** [comment]
@SurbhiMotwani23 where would u position it?

**Comment by SurbhiMotwani23** [comment]
the allignment of the three is not on the same plane

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
