### ISSUE TITLE
Improve the header footer and buttons

### ISSUE THREAD

**Issue by sumitkr2000** [MonalikaPatnaik/UMatter#61]
Hey @MonalikaPatnaik I want to improve the header footer and button of the website. Please assign me this issue. Thank you!

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by sumitkr2000** [comment]
@SamridhiNancy i have raised this issue and once approved I'll start working on it. Please raise another pr to add some additional features. Thank you.

**Comment by MonalikaPatnaik** [comment]
I think someone is working on the buttons already..will let u know if need improvemnt
Thanks!
