### ISSUE TITLE
Hamburger menu of Navbar not working

### ISSUE THREAD

**Issue by Shashank2104125** [MonalikaPatnaik/UMatter#62]
**Describe the bug**
The hamburger menu of the navbar is not working when clicking action perform on it.

**To Reproduce**
1. Go to 'http://localhost:3000/[UMatter](http://localhost:3000/UMatter)'

**Expected behavior**
There should be an open a overlay page containing navbar items

**Screenshots**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/97789487/25f10a8f-c1ed-4462-8512-e9f196891758)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome

**Comment by Shashank2104125** [comment]
@Mansi168 please assign it to me. I have experience dealing with this type of issues.

**Comment by vaidehidangi23** [comment]
@Mansi168  Please assign it to me, I can fix this issue

**Comment by Mansi168** [comment]
navbar is already being assigned for this purpose...will assign you if i need any changes in future!

**Comment by shivam-sharma7** [comment]
close this for now @Shashank2104125
