### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by Shashank2104125** [MonalikaPatnaik/UMatter#63]
**Describe the issue**
Missing setup section.

**Expected behavior**
There should be a section with proper steps to setup the project on a local machine plus information regarding the required version of packages etc.

**Comment by Shashank2104125** [comment]
@Mansi168  please assign it to me.

**Comment by gSayak** [comment]
Its already done
The pr is waiting to be merged, work on some other issue

**Comment by Shashank2104125** [comment]
ok
