### ISSUE TITLE
Signup page is not responsive

### ISSUE THREAD

**Issue by sumitkr2000** [MonalikaPatnaik/UMatter#633]
**Describe the bug**

Hey, @MonalikaPatnaik The signup page is not responsive and doesn't look good on small devices like mobile. Please assign me this issue. Thank you!

**Screenshot**

![Screenshot (838)](https://github.com/MonalikaPatnaik/UMatter/assets/100675296/3184d753-7712-4370-9e29-534d854d8250)

**Comment by Akanksha038** [comment]
Hello @MonalikaPatnaik Ma'am,
I would like to make Signup page responsive. This will help to enhance the user experience.
Please assign me this issue. I would like to work on this issue under GSSOC'23. Please let me fix this issue #633.

**Comment by sumitkr2000** [comment]
@MonalikaPatnaik Please assign me this issue so that I can start working on it.
