### ISSUE TITLE
Need a fix in UI of navbar component

### ISSUE THREAD

**Issue by Anupreet1213** [MonalikaPatnaik/UMatter#64]
I have been reviewing the code for navbar section and found a lot of issues.

1.  Alignment issue in both desktop view and mobile view(Hamburgen Icon)
<img width="959" alt="prevImage" src="https://github.com/MonalikaPatnaik/UMatter/assets/93524594/4884b07f-1b59-48fe-8a0a-e7272c163b12">

2. Zombie css(unwanted css) issue.

-----------------------------------------------------------------------------------------------------------------------------------------
I have been working on this issue as well and have done this far,

https://github.com/MonalikaPatnaik/UMatter/assets/93524594/698d539c-018f-49b3-bbe4-b1e985ad755d
(Sorry for the lag :))

@MonalikaPatnaik should I sent a PR for this?

**Comment by MonalikaPatnaik** [comment]
Heyy @Anupreet1213..The navbar is currently being resolved by #7
Thanks for the issue!
I would suggest you can make a pr..would merge it if required :-)

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by MonalikaPatnaik** [comment]
Hey @Anupreet1213..left a comment in your PR..would like to merge it but it is not in sync with main branch..I suggest you to sync it or make a separate branch & incorporate your changes! #86
