### ISSUE TITLE
Delete duplicate Navbar component  

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#643]
**Describe the bug**
Delete duplicate Navbar component see - https://github.com/MonalikaPatnaik/UMatter/blob/main/src/Components/Navbar/hh.js
 

**Screenshot**

**Comment by shivam-sharma7** [comment]
@AkankshaAI

**Comment by Mansi209aps** [comment]
Could You please assign me this issue 
I want to work on this ..

**Comment by ritik2358** [comment]
Could you please assign me this issue..
I want to work on this.

**Comment by shivam-sharma7** [comment]
@Mansi168 @MonalikaPatnaik

**Comment by i-am-SnehaChauhan** [comment]
Hey @shivam-sharma7 u can start working on this
