### ISSUE TITLE
Making Contact Us Page Responsive

### ISSUE THREAD

**Issue by JAYESHBATRA** [MonalikaPatnaik/UMatter#647]
**Describe the bug**

Making the Contact Us page responsive

Kindly assign me this issue under GSSOC'23
**Screenshot**

<img width="296" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/112322302/4cd84502-d153-47ce-a249-10348e3e1b00">

**Comment by MonalikaPatnaik** [comment]
pls make the current contact us responsive.. @JAYESHBATRA are u working on this?

**Comment by JAYESHBATRA** [comment]
Yes I am working on it. But earlier I closed the pull request as an error was occuring. I will create a new pull request asap.
