### ISSUE TITLE
The last card of our services component is merged with footer in mobile view

### ISSUE THREAD

**Issue by vaidehidangi23** [MonalikaPatnaik/UMatter#65]
Hey @Mansi168 as the footer is not looking correctly I will add some features to improve UI.
![gssoc](https://github.com/MonalikaPatnaik/UMatter/assets/62616333/78e637c0-df7f-41f2-821a-ea544cee73a9)

**Comment by MonalikaPatnaik** [comment]
Heyy..you can work on this..

**Comment by vaidehidangi23** [comment]
Okay

**Comment by vaidehidangi23** [comment]
Hey, @MonalikaPatnaik  I have successfully resolved issue #65 and  I have submitted a pull request: [#133](https://github.com/MonalikaPatnaik/UMatter/pull/133) that encapsulates the changes made to address this issue. The pull request is available in the branch "fixed_services_component" of the repository. It would be greatly appreciated if you could spare some time to review the pull request and provide feedback.

**Comment by i-am-SnehaChauhan** [comment]
@vaidehidangi23 okay we'll merge it after checking Thanks :)
Happy Contributing.
