### ISSUE TITLE
Adding Diet plan 

### ISSUE THREAD

**Issue by Anamika-Ratna** [MonalikaPatnaik/UMatter#651]
**Feature idea.**

Hello , I came across your website and I would like to add a food plan.

**Describe the solution you'd like**

I would like to add a new section  after the 'service section ' where food plans for smokers and drinkers will be displayed so that they know where they should focus more. Moreover this would help them to know what they should avoid eating and drinking.

Therefore I  kindly request you to assign me this task under the tag GSSoC-23 .

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it

**Comment by Anamika-Ratna** [comment]
Update : 
I have completed 90% of the work . Finishing is the only thing left . I will complete it soon (as my end sem starts from 3rd july , I need some more time ). 
![Screenshot (398)](https://github.com/MonalikaPatnaik/UMatter/assets/122286548/a80cccfd-2fc2-4f31-92e1-1f6af3f87d40)
![Screenshot (399)](https://github.com/MonalikaPatnaik/UMatter/assets/122286548/d5251b1e-ab4e-45b9-926b-48729d45cd16)
