### ISSUE TITLE
Sign-in section content alignment issue

### ISSUE THREAD

**Issue by Devil1205** [MonalikaPatnaik/UMatter#652]
**Describe the bug**
In the sign in section, the various components are misaligned. I would like to fix that, kindly assign.

**Screenshot**
![Screenshot_2023-06-04-12-27-37-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/MonalikaPatnaik/UMatter/assets/103431946/376a8c6d-95ee-4476-a28a-bdb8568d215d)

**Comment by MonalikaPatnaik** [comment]
I think it's been done!
