### ISSUE TITLE
Adding the list of contributers

### ISSUE THREAD

**Issue by Anamika-Ratna** [MonalikaPatnaik/UMatter#653]
**Feature idea.**
Hello , I would like to add a section to display the names of contributers . 

**Describe the solution you'd like**
I would like to add a list of people who contributed to this project after the 'testimonial section' .

Therefore I kindly request you to assign me this task under the tag GSSoC-23.

**Comment by Snigdha2712** [comment]
Please assign this project to me. i will fix the issue
