### ISSUE TITLE
Adding Dark-Mode to the Blog Page

### ISSUE THREAD

**Issue by imsoumik03** [MonalikaPatnaik/UMatter#655]
## Describe the bug

I want to add dark-mode to the `Blog Page` . As in the page dark-mode only applicable for Navbar component but I want add it in its background also like other pages . 

 
So, please assign this to me . I want to work on it .

**Comment by MonalikaPatnaik** [comment]
hey @imsoumik03 pls submit your PR within one day..otherwise will assign it to someone else!
