### ISSUE TITLE
Alignment of signup page.

### ISSUE THREAD

**Issue by Titiksha2012** [MonalikaPatnaik/UMatter#656]
The alignment of input boxes in the sign up form is not proper. 
The boxes are stretched outside the container.
I would like to fix this issue.

Below is a screenshot of the above mentioned issue:
![Screenshot_2023-06-04-15-36-12-01_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/MonalikaPatnaik/UMatter/assets/112792296/9716d4fd-b16b-4360-b7a4-e26893b366f0)

Kindly assign This issue to me.
@MonalikaPatnaik 
@i-am-SnehaChauhan

**Comment by Titiksha2012** [comment]
Kindly assign this issue to me. I'm keen working on this.
@i-am-SnehaChauhan 
@MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
It's been done already!
