### ISSUE TITLE
Styling of 'Our Services' section.

### ISSUE THREAD

**Issue by Titiksha2012** [MonalikaPatnaik/UMatter#657]
The 'our services' section is all black and needs some bright colours in it to make it visually appealing. 
I'm keen to beautify it and enhance its styling.

Here's a screenshot of the above mentioned problem:
![Screenshot_2023-06-04-15-39-08-54_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/MonalikaPatnaik/UMatter/assets/112792296/8d78cea3-ebf2-481a-aaf9-ae99dad55ddb)

Kindly assign This issue to me.
@MonalikaPatnaik 
@i-am-SnehaChauhan

**Comment by Titiksha2012** [comment]
Kindly assign This issue to me.
@MonalikaPatnaik
@i-am-SnehaChauhan

**Comment by MonalikaPatnaik** [comment]
Okay u can work on this!

**Comment by Titiksha2012** [comment]
@MonalikaPatnaik Thanks a lot for the opportunity! :)

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
