### ISSUE TITLE
Background of the 'Contact us' page

### ISSUE THREAD

**Issue by Titiksha2012** [MonalikaPatnaik/UMatter#658]
The background colour of the 'contact us' page is white, unlike the other black backgrounds of other pages.
The white colour fails to match the feel of the site, which is mostly in dark mode.
I'm keen to make the background colour black and do other modifications eventually required (if any).

Here's the screenshot:
![IMG_20230604_154322.jpg](https://github.com/MonalikaPatnaik/UMatter/assets/112792296/fc90fe00-db47-49d6-91db-b63b8fd4c3a2)

 Kindly assign This issue to me.
@MonalikaPatnaik
@i-am-SnehaChauhan

**Comment by Titiksha2012** [comment]
Kindly assign This issue to me.
@MonalikaPatnaik
@i-am-SnehaChauhan

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
