### ISSUE TITLE
Fix the responsiveness of Navbar

### ISSUE THREAD

**Issue by shrutigolwalk0109** [MonalikaPatnaik/UMatter#659]
The Navbar is not fully responsive. Can I work on it..
![image](https://github.com/MonalikaPatnaik/UMatter/assets/132553685/8c73c81f-55a2-4c0e-95fe-42082ba90e5a)

**Comment by shrutigolwalk0109** [comment]
Please assign this issue to me ,I would like to work on it with label of GSSOC

**Comment by AkankshaAI** [comment]
> 👋 @shrutigolwalk0109 Thanks for opening your first issue here! Be sure to follow the issue template!

Please propose a video of the bug

**Comment by shrutigolwalk0109** [comment]
https://github.com/MonalikaPatnaik/UMatter/assets/132553685/bd3a560f-549e-4607-9b23-53415d236ce1

**Comment by Pursottam6003** [comment]
Does this issue been resolved @AkankshaAI  if not do let me know I would be happy to work on it  

Thank You

**Comment by Sachin4219** [comment]
Hello @shrutigolwalk0109  this issue is not resolved yet , are you working on it currently ?
