### ISSUE TITLE
Inspirational Content

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [MonalikaPatnaik/UMatter#66]
Curate inspiring stories, quotes and videos related to quitting habits. Feature success stories of individuals who have overcome similar challenges.

@Mansi168  kindly assign me to solve the issue as GSoC'23 Contributor.

**Comment by i-am-SnehaChauhan** [comment]
@Suchitra-Sahoo start contributing as you raised this issue.

**Comment by Suchitra-Sahoo** [comment]
> @Suchitra-Sahoo start contributing as you raised this issue.

yeah working on it

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by MonalikaPatnaik** [comment]
Hey @Suchitra-Sahoo could you tell me where you incorporate this

> Curate inspiring stories, quotes and videos related to quitting habits. Feature success stories of individuals who have overcome similar challenges.
> 
> @Mansi168 kindly assign me to solve the issue as GSoC'23 Contributor.

**Comment by vk20july** [comment]
@MonalikaPatnaik can i do this task under gssoc'23
