### ISSUE TITLE
ADD our Team Page

### ISSUE THREAD

**Issue by abhi03ruchi** [MonalikaPatnaik/UMatter#661]
**Feature idea.**
I would like to add the team's page to the website

**Describe the solution you'd like**
Add the developers and contributors section to the page with a list of all contributors and developers in it. This would improve user engagement and experience. 

Plz assign this task to me under gssoc'23.

**Comment by MonalikaPatnaik** [comment]
There are so many contributors..would you add them all in the website? I think it's been already added to the readme and in website it will not look good!
