### ISSUE TITLE
UI Need to be improved

### ISSUE THREAD

**Issue by MohamedMafaz** [MonalikaPatnaik/UMatter#663]
**Feature idea.**

Hi there! I'm a UI UX Designer. So I can help you to make UI design for some pages

Please assign me this issue. I'll work on it

**Comment by mubasharaKhan** [comment]
Assign me this issue under GSSoC'23 label

**Comment by AkankshaAI** [comment]
> **Feature idea.**
> 
> Hi there! I'm a UI UX Designer. So I can help you to make UI design for some pages
> 
> Please assign me this issue. I'll work on it

Please explain what changes you propose
