### ISSUE TITLE
Sign form 

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#67]
add margin-bottom propertie Sign form and border redius

![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/d09fd10d-56a7-4ca1-aedf-81b7cbbe2746)

**Comment by shivam-sharma7** [comment]
@Mansi168

**Comment by BTANISHA11** [comment]
hello I want to work on this issue.
Can you pls assign this to me.
The form will be with a good ui.

**Comment by shivam-sharma7** [comment]
@BTANISHA11 No because I already assigned

**Comment by Mansi168** [comment]
hey @BTANISHA11 look for unassigned issues or make ur own issue :)

**Comment by BTANISHA11** [comment]
okk
