### ISSUE TITLE
Add Footer to signIn page

### ISSUE THREAD

**Issue by Prajwal0225** [MonalikaPatnaik/UMatter#681]
**Feature idea.**
The sign-in page of the website is currently lacking a footer section. This is causing a visual inconsistency compared to other pages and may lead to a poor user experience. A footer provides important information, and links, and enhances the overall usability of the website. It is essential to have a consistent design across all pages, including the sign-in page.

**Screenshot**
![signin](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/164d2b35-dcd3-4d69-903e-4f252a98ac3f)

**Comment by Snigdha2712** [comment]
Please assign this project to me. I will fix the issue.

**Comment by MonalikaPatnaik** [comment]
Okay @Prajwal0225 you can do this!

**Comment by MonalikaPatnaik** [comment]
Hey @Prajwal0225 pls do submit your PR by eod!

**Comment by Prajwal0225** [comment]
My exam are going on. So can I to it by 13th jun ?

**Comment by MonalikaPatnaik** [comment]
Okay then do submit it by 13th EOD...it's a minor task...won't take much time.
