### ISSUE TITLE
2 dark mode buttons in sign in & sign up [GSSOC'23] 

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [MonalikaPatnaik/UMatter#686]
**Describe the bug**

duplicate of dark mode button in sign in and sign up 
please assign this issue to me . 

**Screenshot**

![image](https://github.com/MonalikaPatnaik/UMatter/assets/112896644/7db64975-8844-4f17-a2bc-05941882dafe)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/112896644/77e167e6-0028-423c-962b-abb3114c95e4)

**Comment by MonalikaPatnaik** [comment]
I think it's not in signup page..it's only in sign in page..you can remove it!
