### ISSUE TITLE
The "Sign Up" page is not responsive and misaligned.

### ISSUE THREAD

**Issue by himanshuy21** [MonalikaPatnaik/UMatter#687]
**Describe the bug**

The "Sign Up" page is not responsive and misaligned.

**Screenshot**![image](https://github.com/MonalikaPatnaik/UMatter/assets/93994213/a55a1a7b-5b93-49f4-bb1d-0c560e3e3702)

🌐 Browsers
Which browsers are you experiencing the problem on? (Select all that apply)

 ☑Chrome
  ☑Firefox
 Safari
  ☑Microsoft Edge
 Opera
 Brave
💻 OS
What is the impacted environment (operating system)? (Select all that apply)

  ☑Windows
 Linux
 Mac
 iOS
 Android
📝 Sections Completed
Check the box of the sections you have completed:

  ☑Description
  ☑Reproduction URL
 Reproduction Steps
  ☑Screenshots
 Logs
 ☑ Browsers
  ☑OS
 Additional Context
🔍 Priority
Please select the priority of the bug:

  ☑High
 Medium
 Low
📜 Code of Conduct
By submitting this issue, you agree to follow our Code of Conduct:

  ☑I follow Contributing Guidelines of this project.
  ☑I have checked the current issues for duplicate problems.
  ☑I have read the readme.

**Comment by PUJAmangale1221** [comment]
Hello Maintainers, I am interested in this issue and would appreciate the opportunity to be assigned to it.
