### ISSUE TITLE
[GSSoC'23] Habit tracker

### ISSUE THREAD

**Issue by MuzmmilKhan1** [MonalikaPatnaik/UMatter#689]
Hi,

I can suggest and Idea to improve the app. I can add a Habit tracker in which one can keep track of recode in a database of one has Improved quitting his bad habit. Please Assign this New feature to me So, I can make this Thank you.

Best Regards,
Muzamil Khan.

**Comment by MonalikaPatnaik** [comment]
Someone is already working on this...will update u soon!

**Comment by MonalikaPatnaik** [comment]
Hii  @MuzmmilKhan1 you can work on this!
Thank you so much for contributing!

**Comment by MuzmmilKhan1** [comment]
Hi @MonalikaPatnaik, Thanks for assigning this issue I will start working on this by Friday

**Comment by MonalikaPatnaik** [comment]
hii @MuzmmilKhan1 any update on this?

**Comment by Piyusharora2003** [comment]
@MonalikaPatnaik can i work on this issue , as @MuzmmilKhan1  is not responding for a long time , 

My idea regarding this is  : i would like to priorly implement a tracking mechanism where people can add their activities , can keep track of them and categorise as bad or good and can evaluate each day ,

Issues facing (if started) :
       1. the website is not connected to a decentralised db like mongo db. 
       sol : this can be temporary solved using local storage of the pc

**Comment by Piyusharora2003** [comment]
@MonalikaPatnaik @TechSpiritSS  I have created a pull request regarding this task, please verify and merge it.
