### ISSUE TITLE
404 Error page

### ISSUE THREAD

**Issue by PatilHarshh** [MonalikaPatnaik/UMatter#692]
@MonalikaPatnaik adding the error page will give good look 
![Screenshot (81)](https://github.com/MonalikaPatnaik/UMatter/assets/120102234/28aafdc4-4700-41df-b28a-32100974b682)

**Comment by PatilHarshh** [comment]
please assign me this project

**Comment by MonalikaPatnaik** [comment]
Hey 404berror page is already there?

**Comment by PatilHarshh** [comment]
Ya but not rendering

**Comment by MonalikaPatnaik** [comment]
Yea yes ik but labels on your PR is counted for final score!
