### ISSUE TITLE
start button 

### ISSUE THREAD

**Issue by SurbhiMotwani23** [MonalikaPatnaik/UMatter#698]
**Describe the bug**
will add the arrow button in start 

**Screenshot**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91596996/2a36fc5a-4ed5-45d1-a2f3-4a8b5454c6f5)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91596996/450a7c04-4d6a-4234-8f8d-97880784f612)

**Comment by Snigdha2712** [comment]
Please assign this project to me. I will fix the issue
