### ISSUE TITLE
Improving navbar design and home page 

### ISSUE THREAD

**Issue by babitarit** [MonalikaPatnaik/UMatter#70]
![Screenshot (90)](https://github.com/MonalikaPatnaik/UMatter/assets/118760765/dc55b6cd-b4b5-42ba-8b96-b693e8ea5188)

when we hover on navbar its showing blue color which doesnot match the theme of website 
and also the text written on home page should be somewhat centre so it will look nice i can improve it all please assign this to me

**Comment by MonalikaPatnaik** [comment]
Hey..navbar is being resolved by #7 
and for the home page text and alignment, it is being resolved by #58 
Thanks!

**Comment by babitarit** [comment]
ok

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
