### ISSUE TITLE
Feature: I want to add some animation to the Return to top button

### ISSUE THREAD

**Issue by bhaskarkumar1** [MonalikaPatnaik/UMatter#701]
I would like to suggest adding animation to the "Return to Top" button on the website. Currently, the button provides functionality to quickly scroll back to the top of the page, but adding an animation will enhance the user experience and make the transition smoother.
![Screenshot18](https://github.com/MonalikaPatnaik/UMatter/assets/84345649/55d2b1aa-0326-48aa-a773-a1c9b1680411)

**Comment by bhaskarkumar1** [comment]
@TechSpiritSS , Please check as I have requested for a pull request to be merged #714

**Comment by MonalikaPatnaik** [comment]
LGTM!
