### ISSUE TITLE
Sign Up form

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#706]
**Describe the bug**
Sign Up form `continue` button have not align whenever someone hover on that so we need ruduce that

**Screenshot**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91419219/77058ee1-1929-40ac-b9c9-cd6ac793d935)

 

@MonalikaPatnaik

**Comment by Abhishek9229** [comment]
please assign it to me, i want to work on it

**Comment by yash8917** [comment]
Assign this issue to me under GSSOc '2023
