### ISSUE TITLE
The Testimonial Section is empty I can add some demo Cards.

### ISSUE THREAD

**Issue by MuzmmilKhan1** [MonalikaPatnaik/UMatter#707]
Hello, I noticed that the testimonial part was empty so. I can add some demo testimonials using bootstrap cards and make a carousel of 5 to 6 cards.
![Uploading Screenshot 2023-06-07 085054.png…]()

Please assign this issue to me.
Thanks.

**Comment by TechSpiritSS** [comment]
screenshot is not visible

**Comment by MuzmmilKhan1** [comment]
<img width="956" alt="Screenshot 2023-06-07 085054" src="https://github.com/MonalikaPatnaik/UMatter/assets/77438943/921ae560-fe8b-4747-b63e-3157e1e354db">
Sorry For inconvenience

**Comment by MuzmmilKhan1** [comment]
@TechSpiritSS I can make them please give me a day.

**Comment by MuzmmilKhan1** [comment]
Hello, So I have redesigned Cards I just wanted permission to use react-multi-carousel as a library.
<img width="956" alt="Screenshot 2023-06-09 234714" src="https://github.com/MonalikaPatnaik/UMatter/assets/77438943/6f13e439-b6e6-4f1e-a366-83d53cacbf56">

**Comment by TechSpiritSS** [comment]
Yes, you can, just make sure there isn't some dependency issue.

**Comment by MuzmmilKhan1** [comment]
> Yes, you can, just make sure there isn't some dependency issue.

@TechSpiritSS I don't understand what dependency issue means I just created it in plain JSX and CSS

**Comment by MuzmmilKhan1** [comment]
> Yes, you can, just make sure there isn't some dependency issue.

Ok I will make sure that

**Comment by MonalikaPatnaik** [comment]
Heyy @MuzmmilKhan1 the testimonial card look much like the services card..it would be better if u can change the card UI to something similar mentioned in issue #563?

**Comment by MuzmmilKhan1** [comment]
hello, @MonalikaPatnaik and @TechSpiritSS I just finished working on that, So As you said to so I made a few changes in CSS to make it look different than Serviecs Cards I didn't make it exactly like  Because It was a little difficult and also It would have not been according to the theme. So Please review it. 

<img width="954" alt="Screenshot 2023-06-10 141317" src="https://github.com/MonalikaPatnaik/UMatter/assets/77438943/c2965285-8fa6-4487-b54d-4a45689b09aa">

Thanks

**Comment by MonalikaPatnaik** [comment]
LGTM👍

**Comment by MuzmmilKhan1** [comment]
> LGTM👍

I am glad you liked it I will just create a pull request
