### ISSUE TITLE
Social Links to Sign-in/Sign-up

### ISSUE THREAD

**Issue by MuzmmilKhan1** [MonalikaPatnaik/UMatter#708]
Hello, Signing in with social media accounts or other personal accounts like Google, Facebook or GitHub is a good and hassle-free way. So I recommend you to get those implemented into your site.

Please assign this task to me so I can work on this.
Thanks

**Comment by MuzmmilKhan1** [comment]
@TechSpiritSS Please recommend a method either to do it with Firebase or Use passport or by Using JWT. And if you want it with Firebase please setup and send Credentials. If by JWT please setup in consoles of required social apps and send concerning data. Thanks

**Comment by TechSpiritSS** [comment]
@MonalikaPatnaik can you provide credentials?

**Comment by MuzmmilKhan1** [comment]
@TechSpiritSS Should I start working with my own Firebase credentials and I shall paste yours whenever @MonalikaPatnaik Provides them?

**Comment by TechSpiritSS** [comment]
Let the project admin decide for this scenario.

**Comment by MuzmmilKhan1** [comment]
Ok

**Comment by MonalikaPatnaik** [comment]
Hii, thank you so much for the patience..actually some PRs are already open regarding authentication of sign-up, sign-in page..it's not been merged bcoz their branch is giving conflicts..will let u know the status soon!

**Comment by MonalikaPatnaik** [comment]
Meanwhile you can work on your habit-tracker issue!
