### ISSUE TITLE
Not scrolling to the relevant section.

### ISSUE THREAD

**Issue by MuzmmilKhan1** [MonalikaPatnaik/UMatter#709]
Hello, 
         I noticed that when we are in the route "/" and click on testimonials or service it animates us to that part but whenever we are in some other page like sign up or sign in and stuff It doesn't.

https://github.com/MonalikaPatnaik/UMatter/assets/77438943/fd230f61-39b9-49fa-812d-9a485d421568

Please assign this issue to me.
Thanks

**Comment by TechSpiritSS** [comment]
I'll assign you after completion of previous one as you are already having issues to work on

**Comment by aryan-bhokare** [comment]
Please assign this issue to me. I am a Gssoc contributor.

**Comment by MuzmmilKhan1** [comment]
> Please assign this issue to me. I am a Gssoc contributor.

**Comment by MuzmmilKhan1** [comment]
@TechSpiritSS, Please assign it now, I will make sure to complete it by this Weekend Thanks

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
