### ISSUE TITLE
Service Box Hover Effect

### ISSUE THREAD

**Issue by Samriddhi15** [MonalikaPatnaik/UMatter#719]
**A Service box hover effect**

**Describe the solution you'd like**

https://github.com/MonalikaPatnaik/UMatter/assets/106501626/4ba021f5-f400-4777-b293-33a09a83703b

**Comment by ePSA-eJya** [comment]
I would want to work on this issue @TechSpiritSS @MonalikaPatnaik .i am a gssoc contributor. please assign this to me.

**Comment by TechSpiritSS** [comment]
Since, it has been 2 weeks, I am reassigning this issue.

**Comment by ePSA-eJya** [comment]
Thanks for assignment. I would finish it in a week.
