### ISSUE TITLE
Improving readability: adjust alignment and enhance readme documentation

### ISSUE THREAD

**Issue by jfmartinz** [MonalikaPatnaik/UMatter#721]
**Describe the bug**
I would like to raise an issue regarding the alignment and readability of the documentation or README file. Currently, the text in the document is centered, which makes it difficult to read and follow the content effectively. To enhance the overall user experience and make the documentation more accessible, I propose adjusting the alignment to a more standard and readable format.

Expected:
Aligning the text to the left  would greatly improve the readability of the documentation. This adjustment will ensure that the text flows naturally from left to right, making it easier for users to skim through and locate specific information.

Assign this to me under **GSSOC**

**Screenshot**
![image](https://github.com/MonalikaPatnaik/UMatter/assets/129386460/f45ed391-786b-40d1-9f79-5b49219d2ad6)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/129386460/4c2d9eba-a7e3-43a0-8f78-68f568d9f09b)

**Comment by TechSpiritSS** [comment]
Sure, make it justify instead of center
