### ISSUE TITLE
Response Message Not Visible

### ISSUE THREAD

**Issue by mudrikachawla** [MonalikaPatnaik/UMatter#725]
**DESCRIPTION:**
The response message of the signup page is not clearly visible and is getting hidden behind the footer.

![Screenshot (111)](https://github.com/MonalikaPatnaik/UMatter/assets/115139305/15654c85-e4e1-4286-bc71-a736c852a9b1)

I am a GSSoC Contributor and would like to work on this issue.
Please, assign it to me under GSSoC @MonalikaPatnaik

**Comment by TechSpiritSS** [comment]
The SignUp component is already assigned to be fixed, if that PR doesn't cover those messages, it will be assigned to you.

**Comment by mudrikachawla** [comment]
Thanks for response, let me know once that PR has been reviewed and require my changes.
