### ISSUE TITLE
Add testimonials Cards

### ISSUE THREAD

**Issue by Abhinavcode13** [MonalikaPatnaik/UMatter#726]
**Feature idea.**

As there is no testimonial cards as of now , would like to add them.

**Describe the solution you'd like**

Basic css , html and javscript use for making the cards

**Comment by Abhinavcode13** [comment]
Please assign me this issue @Mansi168 @TechSpiritSS !!
thanks

**Comment by TechSpiritSS** [comment]
This feature has already been assigned under some other issue name last night.
