### ISSUE TITLE
Start Button is not working

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [MonalikaPatnaik/UMatter#73]
On clicking the start button nothing is showing up.
@Mansi168 @MonalikaPatnaik  I would like to resolve this issue as a GSoC'23 contributor.
![1f09faf1-06c8-4704-a8fc-39cedf304434](https://github.com/MonalikaPatnaik/UMatter/assets/123376847/5ec8cd49-3de2-4fa2-aef6-1df0b9fda316)

**Comment by MonalikaPatnaik** [comment]
So, what should be the expected behaviour u are planning to do?

**Comment by Suchitra-Sahoo** [comment]
> So, what should be the expected behaviour u are planning to do?

On click start button various options may pop up such as 
1. Motivational quotes
2. Supportive Resources ( relevant articles , videos to overcome bad habbits)
3. Progress Tracker
4. Interactive tools( mini games, quiz, puzzle to distract the user)

**Comment by MonalikaPatnaik** [comment]
Okay..so are you planning to build an entire page for these things?

**Comment by Suchitra-Sahoo** [comment]
> Okay..so are you planning to build an entire page for these things?

yes... on clicking the start button all these options will pop up and the user can choose according to the need.

**Comment by MonalikaPatnaik** [comment]
@Suchitra-Sahoo : you are assigned!
Thanks for the issue :-)
