### ISSUE TITLE
Feature: Redesign  Feedback input box of feedback page (Screenshot ATTACHED)

### ISSUE THREAD

**Issue by bhaskarkumar1** [MonalikaPatnaik/UMatter#731]
**The current Feedback box is not looking good as you can see from the !st screenshot but I want to make some changes and made it look like the second Screenshot which is looking quit nice than the previous one. So assign me this task So that I could fix  the feedback input** 

![sc10_06](https://github.com/MonalikaPatnaik/UMatter/assets/84345649/98fba59c-bdd6-486d-b700-c4a5089f2e61)

![sc10_05](https://github.com/MonalikaPatnaik/UMatter/assets/84345649/94fe6715-c5e3-420d-9936-e328c5b0aabf)

**Comment by aryan-bhokare** [comment]
I am GSSOC contributor, I would like to redesign the feedback form.

**Comment by TechSpiritSS** [comment]
@bhaskarkumar1 this UI change is too minor to add a GSSoC tag, provide some more changes to make it look a little better.
