### ISSUE TITLE
Calculator to track cost saving

### ISSUE THREAD

**Issue by kharshita590** [MonalikaPatnaik/UMatter#732]
**Feature idea.**

My feature will allow the user to calculate how much they waste on these things like smoking , that will encourage them to quit smoking.

**Describe the solution you'd like**

**Comment by TechSpiritSS** [comment]
@kharshita590 your solutions seem good but I'll need some more context regarding what you are planning to perform to assign this issue to you.

Better the solution higher will be the level in this
