### ISSUE TITLE
Blog section read more hover section need improvement

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#735]
**Feature idea.**
The blog section read more button hover state need to improve the transition  need improvement and  when we hover the button it starts overriding the paragraph

**Describe the solution you'd like**

I want to give proper transition properties to the button and also want to add some margin between the paragraph and the button,  so that when we hover over it never overrides over paragraph

##Screenshot
![186](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/f1c112d7-723d-4ca2-a73a-3c0a4e74ce37)
![187](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/5a7b7805-4e3f-4948-85c1-e5c1c7d75cc4)

**Comment by MonalikaPatnaik** [comment]
The blog cards are currently been redesigned by someone else..

**Comment by HimanshuNarware** [comment]
> The blog cards are currently been redesigned by someone else..

ok
