### ISSUE TITLE
Bug in the Signin page

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#736]
**Describe the bug**
While entering the password on the Sign in page the password is not showing. I want to work on this issue

**Screenshot**

https://github.com/MonalikaPatnaik/UMatter/assets/83147410/0ff6d874-9410-46cb-9a73-247d6a82257f

![188](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/682981c4-fb1e-44dc-9905-262cb4fade2f)
![189](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/250e2106-7f30-410b-ad19-715f8f15e01f)

**Comment by thezeeshann** [comment]
Hi, I would like to work on this issue. please assign me.
