### ISSUE TITLE
Sign form is missing required symbol.

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#737]
**Feature idea.**

The Sign form is missing the required symbol, it will improve the readability also help the user during signup
**Describe the solution you'd like**
I want to add the required property to the form, like email, phone num, and username need  required symbol

##Screenshot
![191](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/a2b82082-0cd5-47fb-a696-f696a75bfbc4)

**Comment by codegem99** [comment]
Please assign me to it

**Comment by PrathamKumar125** [comment]
I would like to work on this project. Please assign it to me.
