### ISSUE TITLE
Add hovering effect to the contact us section.

### ISSUE THREAD

**Issue by Aditi323** [MonalikaPatnaik/UMatter#738]
Hey I want to add hover effect to the contact us section and make it text look more attractive by aligning them.
![Screenshot (67)](https://github.com/MonalikaPatnaik/UMatter/assets/114893448/52c52f43-716f-42bb-b4a5-acee8f8bf172)

**Comment by Aditi323** [comment]
> 👋 @Aditi323 Thanks for opening your first issue here! Be sure to follow the issue template!

Please assign me so that I could start working on it

**Comment by yash8917** [comment]
I would like to work on this issue pls assign me under the GSSOC '2023
