### ISSUE TITLE
Gamification elements

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [MonalikaPatnaik/UMatter#74]
Integrate gamification features into the website to make the quitting process more engaging and fun. Create challenges, milestones, badges or reward system to incentivize users to stay committed and achieve their goals. 

@Mansi168 kindly assign me to add this feature as a GSoC'23 Contributor.

**Comment by MonalikaPatnaik** [comment]
Hey..I loved the idea..Could you provide more context and where would u integrate these changes in the website!

**Comment by Suchitra-Sahoo** [comment]
> Hey..I loved the idea..Could you provide more context and where would u integrate these changes in the website!

Homepage: We can add "Challenge of the Week" button prominently on the homepage of the website.

When users click on this button, they are presented with a weekly challenge related to breaking their specific bad habit. Challenges could be like to read a given article or video about negative effects of the habbit, finding a positive alternative to their bad habbit, do guided meditations and after each challenge attempt a quiz on lessons learned throughout the week.

Here's how it can work:

Each week, you can feature a new challenge that encourages users to tackle their bad habit in a different way or overcome a specific obstacle.

Provide clear instructions or guidelines for completing the challenge.

Users can choose to accept the challenge and commit to completing it within the given week.
As users complete the challenge, they can earn points, badges, or rewards specific to the challenge.
