### ISSUE TITLE
Review the branding chart and colors

### ISSUE THREAD

**Issue by geoffreylgv** [MonalikaPatnaik/UMatter#747]
- The pages login and register design are too flashy, so review the colors of the branding of the website. 
 - Remember to keep it simple, without overcomplicating the color shades.

**Comment by Deepali2003Paswan** [comment]
Please assign it to me

**Comment by geoffreylgv** [comment]
Hey @MonalikaPatnaik, can you assign this issue to both of us, under GSSOC'23

**Comment by MonalikaPatnaik** [comment]
Hii @geoffreylgv could you elaborate a bit by sharing ss maybe that what u are going to change and implement?

**Comment by geoffreylgv** [comment]
Yea @MonalikaPatnaik  
The colors on the login/register/forgot password are slightly nuanced, and I'd like to redo this without nuance colors.
