### ISSUE TITLE
Feedback form styling not looking attractive in dark mode

### ISSUE THREAD

**Issue by Shreyans2004** [MonalikaPatnaik/UMatter#755]
**Describe the bug**
The feedback page box is not looking attractive in the dark mode .It's edges are not properly seen in the dark mode.I can change the styling so that it looks better. Can you assign this issue to me?

**Screenshot**

![WhatsApp Image 2023-06-12 at 15 30 38](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/84535f9c-b319-45a9-b5f7-9c77123820c6)

**Comment by MonalikaPatnaik** [comment]
Hey, this UI change is too minor to add a GSSOC tag. Provide some more context to make it look more better.
