### ISSUE TITLE
The seach box in the blog page

### ISSUE THREAD

**Issue by Shreyans2004** [MonalikaPatnaik/UMatter#757]
**Describe the bug**

The search box in the blog page is not looking attractive as the user is enable to clearly figure out that their is a box .The color of search box is mixing up with website color.I can change the border of the box so that it looks better.
**Screenshot**
![WhatsApp Image 2023-06-12 at 16 16 54](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/90ca623a-cf53-4bb7-979d-099f6323eb43)
![WhatsApp Image 2023-06-12 at 16 16 43](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/21f25f90-c10b-4503-b9a0-891f52581e51)

**Comment by i-am-SnehaChauhan** [comment]
This issue is similar to this #505 
Message there
Thanks :)
