### ISSUE TITLE
Adding cursor pointer to the "Read More" button in a blog section

### ISSUE THREAD

**Issue by Prajwal0225** [MonalikaPatnaik/UMatter#758]
**Feature idea:**
Currently, when navigating to the "Read More" link in a blog section, the cursor remains unchanged, providing no visual indication to the user that the link is clickable. This can lead to a poor user experience and confusion about the interactivity of the link.

**Solution**:
To improve user experience and make the "Read More" link more intuitive, it would be beneficial to add a cursor pointer when hovering over the link. This visual cue will indicate to users that the link is clickable and encourage them to interact with it.

**Screenshot reference**:
![ssssss](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/69eab259-a548-4b76-81ed-d3abd0941322)

By implementing this change, users will have a clearer understanding of the link's functionality, enhancing the overall usability of the blog section.

Can you please assign this issue to me? so that I can start working on this issue...

**Comment by MonalikaPatnaik** [comment]
hey it's been done !
