### ISSUE TITLE
Improve the alignment of the Navbar

### ISSUE THREAD

**Issue by abhayy143** [MonalikaPatnaik/UMatter#76]
## Issue 
As an GSSoc Contributor I want to raise a issue about the NavBar. As we can see in the screenshot below that the NavBar is not aligned properly with the logo and the Sign In Button.

![8](https://github.com/MonalikaPatnaik/UMatter/assets/53009878/78ba6a82-520b-4030-8382-2c8aee82456e)

**Comment by MonalikaPatnaik** [comment]
Hey..navbar as a whole is currently being resolved by #7
Thanks!

**Comment by abhayy143** [comment]
Oops...! Sorry I didn't saw that the issue has been already raised.
