### ISSUE TITLE
BUG: Fixing Testimonial Section

### ISSUE THREAD

**Issue by sumitkr2000** [MonalikaPatnaik/UMatter#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey, @MonalikaPatnaik The heading and buttons of the testimonials section are not visible in light mode. Please assign me this issue. Thank you!

### Add ScreenShots

- Dark Mode:-

![image](https://github.com/MonalikaPatnaik/UMatter/assets/100675296/7f98e7bf-d65e-46a0-9d43-cd1fb00ce385)

- Light Mode:-

![image](https://github.com/MonalikaPatnaik/UMatter/assets/100675296/47aa1817-c8cf-489e-9236-569b81f7ceb1)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
adding the heading and next & prev contrls only in light mode is too minor to add a GSSOC tag. You can add animation to this section and make it look more attractive by adding slideshow?

**Comment by sumitkr2000** [comment]
> adding the heading and next & prev contrls only in light mode is too minor to add a GSSOC tag. You can add animation to this section and make it look more attractive by adding slideshow?

No, it's already added but due to some bug, it's not visible there!
Well, I can add slideshow. Please assign me this issue.

**Comment by MonalikaPatnaik** [comment]
Hey @sumitkr2000 I am expecting that u are fixing the whole testimonial section including its responsiveness, visibility and colour change in dark/light theme?

**Comment by sumitkr2000** [comment]
Ohh i have to fox that also! I was only adding slideshow as u said. If you want to fix that also i can do it.

**Comment by MonalikaPatnaik** [comment]
Yes pls complete this section in one go, will add level 2 or 3 maybe acc to your work!

**Comment by sumitkr2000** [comment]
@MonalikaPatnaik Okay thanks for clarifying. Working on it.

**Comment by sumitkr2000** [comment]
Hey @MonalikaPatnaik I am working on it and will probably complete it by today. I am traveling that's why it is taking more time.

**Comment by MonalikaPatnaik** [comment]
Yes yes it's okay
