### ISSUE TITLE
BUG: Make username and feedback fields required

### ISSUE THREAD

**Issue by Monson2002** [MonalikaPatnaik/UMatter#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I click on "Send" in the "Share your Feedback" component without filling the username and feedback fields, it is getting submitted, this should not happen, so I propose to make the above two field as "required" to not let the user submit without filling out those fields.

### Add ScreenShots

https://github.com/MonalikaPatnaik/UMatter/assets/91113152/f28df2ba-319a-4a69-91d7-cad9f700c2fd

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

@MonalikaPatnaik please review this

**Comment by Nabil-Khan-6656** [comment]
Can I work on this issue ?
