### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by huzaifa9999** [MonalikaPatnaik/UMatter#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The web application is not responsive in mobile view and in small screens , it shows extra white space .
Please assign this issue to me under GSSOC'23

### Add ScreenShots

![Screenshot (205)](https://github.com/MonalikaPatnaik/UMatter/assets/97234805/28a62fe6-762e-4d1b-ae7c-bcf2b08ac135)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Pursottam6003** [comment]
Does this issue resolved?
