### ISSUE TITLE
Improvement in SignIn SignUp Pages

### ISSUE THREAD

**Issue by yogeyyy** [MonalikaPatnaik/UMatter#773]
### Describe the feature

Hey, 
From the design point of view, There are some issues with the Sign in and Sign up pages in the current version. 
Issues: 

1. There are too many colours when you first open either page (grey, white, back, navy blue, green buttons, gradient box) and I feel they are not going too well somehow.
2. Continue button should look distinct with respect to the background (it is blending in).
3. Size of the continue button is not the same on both pages.
4. When you hover over the continue button, it changes to a muted orange colour (not in the colour palette or branding) and scales in size which is going out of the boundaries of the signup box.
5. Font size of the Headings "sign in to your account" and "create an account" are not uniform.
6. Size of sign-in/sign-up box changes when you switch between the two.
7. Input field of sign up menu is greater in height as compared to the fields of sign in menu
8. Overall look and feel is too bold.

![image](https://github.com/MonalikaPatnaik/UMatter/assets/122149755/3ce0c1fb-28fd-4c90-ad48-6680ea733412)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/122149755/535a7ec6-2502-440d-99cc-3af08a59bac3)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/122149755/d24aedf2-7106-4ea3-aa8e-838a7fe13423)

### Add ScreenShots

Improvements - 

1. Simplifying the UI of the page as shown below
2. Uniforming the headings, box size, input field size, button size, font size
3. Overall More formal, designed look in accordance with the branding and color palette.

![image](https://github.com/MonalikaPatnaik/UMatter/assets/122149755/692e5dd0-0b26-4aa4-977f-8993ace6a708)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/122149755/b85f20c0-fe42-4f52-8c49-eeb14bdc4e58)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by yogeyyy** [comment]
Hey @MonalikaPatnaik @TechSpiritSS ,
Hope, you guys are doing great. Please assign this issue to me under GSSOC'23 Label. 
Thanks.

**Comment by TechSpiritSS** [comment]
Making it level 3, but ensure to fix everything in this sign in

**Comment by MonalikaPatnaik** [comment]
Also, you could add relevant images instead of the text in green part of the form!

**Comment by yogeyyy** [comment]
> Also, you could add relevant images instead of the text in green part of the form!

Hello @MonalikaPatnaik ,

I can surely do that. I have raised a PR solving all the issues I addressed. I would request you to kindly review that first and give me feedback on the same.
I will raise more issues with fixes to more such design problems we have in this project. 

Thanks,
Yogit

**Comment by MonalikaPatnaik** [comment]
Hii, left a comment on your PR
