### ISSUE TITLE
Feat: Footer Section all Links are not working

### ISSUE THREAD

**Issue by codeburn12** [MonalikaPatnaik/UMatter#780]
### Describe the feature

1. Footer Links are not working.
2. All social icons are not provided with links.
3. Footer section looks irregular and UI is not good

### Add ScreenShots

<img width="935" alt="Screenshot 2023-06-16 181517" src="https://github.com/MonalikaPatnaik/UMatter/assets/101239757/c2f2b5b1-5d2a-401e-b22d-84f25f7e96f5">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by yeolesanskruti** [comment]
I am  a GSSOC'23 contributor. 
I would like to work on this issue. Please assign me with this.
Thank you :)
