### ISSUE TITLE
Feat: Create Terms of Services page

### ISSUE THREAD

**Issue by shivam-sharma7** [MonalikaPatnaik/UMatter#782]
### Describe the feature

Create Terms of Services page for user

### Add ScreenShots

not available for now

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Tanmaybhujade** [comment]
please assign this issue to me

**Comment by MonalikaPatnaik** [comment]
@shivam-sharma7 pls describe your feature a bit like where would u add it, what is its use in the website etc?
