### ISSUE TITLE
Enhancement Request: Add Toast Notifications for Errors, Warnings, and Success Messages

### ISSUE THREAD

**Issue by Nishitbaria** [MonalikaPatnaik/UMatter#788]
### Describe the feature

I propose adding toast notifications to the project for displaying errors, warnings, and successful messages. Toast notifications will provide a visually appealing and non-intrusive way to communicate important information to users. This enhancement will improve user experience and facilitate effective feedback during their interactions with the system.

## Key Benefits:

1. Improved User Experience: Toast notifications will provide concise and visually appealing feedback, enhancing the overall user experience.
2. Real-time Feedback: Users will receive immediate notifications, allowing them to address errors or react to warnings promptly.
3. Clarity and Context: Toast notifications will provide relevant information regarding the specific error, warning, or successful event, improving user understanding and navigation.

**_`NOTE : Please add appropriate tags like [gssoc23] [levelX] Tags `_** 

### Add ScreenShots

<div style="display: flex; justify-content: space-between;">
    <img src="https://github.com/MonalikaPatnaik/UMatter/assets/85815172/334d6ad4-2d60-43b8-a25d-d2f7e69f2cff" alt="Image 1" width="400" style="margin-right: 10px;">
    <img src="https://github.com/MonalikaPatnaik/UMatter/assets/85815172/4ab4da0d-d4c0-4241-9ee7-d85bf744bbe5" alt="Image 2" width="400">
</div>

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
Where would you add these toast notifications?
