### ISSUE TITLE
Fix the Content Visibility in the website for Mobile Users.

### ISSUE THREAD

**Issue by abhayy143** [MonalikaPatnaik/UMatter#80]
As a Contributor to GSSoc'23 I want to address this issue

## Issue
As you can see below many parts of the text section is not visible for mobile devices. 

![9](https://github.com/MonalikaPatnaik/UMatter/assets/53009878/f5d58674-1448-4f10-bbcf-0b0d64af6e2a)

![10](https://github.com/MonalikaPatnaik/UMatter/assets/53009878/1a6a5606-00e6-41f4-9135-42792f558e87)

## Solution 
Adding a bit of shadow to the text or changing the position will help the issue to be fixed.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
