### ISSUE TITLE
Feat:Adding option to subscribe to newsletter

### ISSUE THREAD

**Issue by ePSA-eJya** [MonalikaPatnaik/UMatter#801]
### Describe the feature

Adding option to subscribe to newsletter

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/120899038/6c3f0b8d-4b07-4af6-b057-5533a42c6e63)
 something similar

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by ePSA-eJya** [comment]
@MonalikaPatnaik please asssign this issue to me.

**Comment by MonalikaPatnaik** [comment]
Where would you add this?

**Comment by ePSA-eJya** [comment]
> Where would you add this?

in the footer section. @MonalikaPatnaik .....can you please assign this?
