### ISSUE TITLE
Feat:Enhancing the feedback form UI

### ISSUE THREAD

**Issue by ePSA-eJya** [MonalikaPatnaik/UMatter#802]
### Describe the feature

there is too much color in the form.

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/120899038/093f83b4-68e6-44cc-84f1-03cd97554bf7)
 could change the appearance 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by ePSA-eJya** [comment]
I an a gssoc 23 contributor.please assign this issue to me. @MonalikaPatnaik @TechSpiritSS

**Comment by ePSA-eJya** [comment]
Thanks. would finish in a week.

**Comment by MonalikaPatnaik** [comment]
> Thanks. would finish in a week.

Hey could you pls share a ss of the new ui to which you are changing?

**Comment by ePSA-eJya** [comment]
i have yet completed it..... but 
![image](https://github.com/MonalikaPatnaik/UMatter/assets/120899038/7c136cf0-5f7a-45c7-b762-3a419b7a6a97)
this bacgroung image(without text) could be  used with a more transparent form. the color scheme could be aligned with the website color scheme
