### ISSUE TITLE
BUG: Lots of Warnings and dependencies issues 

### ISSUE THREAD

**Issue by Pursottam6003** [MonalikaPatnaik/UMatter#804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While Inspecting the page I found some key value prop warnings and dependencies, styling warnings, unsupported use of <a> tags, etc  which are important to look at and should be resolved because many times these warnings create a lot of issues while production deployment

### Add ScreenShots

[Screencast from 19-06-23 12:32:30 AM IST.webm](https://github.com/MonalikaPatnaik/UMatter/assets/81693090/f381a130-6714-4da2-b7e4-450d441e3b66)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Pursottam6003** [comment]
Hey @Piyusharora2003  Thanks for reminding me  accidentally i deleted all the GitHub emails thus I forgot about this issue please wait I am currently working on it and about to push those changes by tomorrow 

Sorry for inconvience @TechSpiritSS

**Comment by TechSpiritSS** [comment]
waiting for one more day

**Comment by Pursottam6003** [comment]
Fixed the issue 

> @TechSpiritSS can i work on this issue as their is no response from the asigned from 2 weeks

Done changes   https://github.com/MonalikaPatnaik/UMatter/pull/1007 
Kindly do let me know if there is any more changes  need to be followed 
Thank You :)
