### ISSUE TITLE
BUG: Unusual blank spaces in many section

### ISSUE THREAD

**Issue by sayan2002-github** [MonalikaPatnaik/UMatter#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello I am a GSSoC'23 Contributor and I went through your project, it looked very exciting to me. So I discoverd some unusual bugs, including - 1. Unusual white blank space in the feedback section while in the dark mode,  2. While clicking on the main icon "UMatter", it should go to the home page. But it is not.
So as a fellow contributor, I would like to fixe those bugs and make a valuable contribution in this project.

### Add ScreenShots
![Screenshot (92)](https://github.com/MonalikaPatnaik/UMatter/assets/84588159/f70b7c2f-d131-4466-991b-2b2c58e185c6)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Niranjan-Kumar-Singh** [comment]
I want to work in this project. Please assign it to me.

**Comment by MonalikaPatnaik** [comment]
Hey it's been done now!
