### ISSUE TITLE
BUG: UI of footer section

### ISSUE THREAD

**Issue by Naina047** [MonalikaPatnaik/UMatter#808]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

UI of  footer section is a little messy. I want to first improve alignment of About us, Contact us and videos especially the underline are too close to data. secondly increease the space between data and social media sections

### Add ScreenShots

![Screenshot 2023-06-19 124812](https://github.com/MonalikaPatnaik/UMatter/assets/96466577/9d8adfa4-92ed-4db0-9cde-5c90392b5893)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
could you share the ss for reference to which you are changing?

**Comment by MonalikaPatnaik** [comment]
No, it's not looking good to me!
