### ISSUE TITLE
Password error in Sign up form

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [MonalikaPatnaik/UMatter#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While creating an account, after giving 8 characters in password 
then also it is showing error **"please enter atleast 8 characters"**
I tried with numbers and characters, even with more than 8 character.
But it is still showing error.
I'd like to fix this issue
could you assign this to me under Gssoc'23.

### Add ScreenShots

![2023-06-19 (2)](https://github.com/MonalikaPatnaik/UMatter/assets/71914071/6e83cc2a-711e-45ff-a330-f8140dd40708)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
the sign up form has been redesigned now!
