### ISSUE TITLE
Improving the website name in header

### ISSUE THREAD

**Issue by raiankitsr** [MonalikaPatnaik/UMatter#81]

**Comment by raiankitsr** [comment]
> _No description provided._

@Mansi168 @MonalikaPatnaik  I can add suitable animation to website to enhance its performance

**Comment by MonalikaPatnaik** [comment]
Heyy sure..you can work on this!
Thanks :-)

**Comment by MonalikaPatnaik** [comment]
Heyy @raiankitsrare u working on changing the U of Umatter...if u don't just lmk??

**Comment by raiankitsr** [comment]
Yeah, I can do that.

**Comment by MonalikaPatnaik** [comment]
Thanks..The current name in header is looking as normal text..you can try improving the font size and style or adding something that distinguishes it in the header beside the logo!

**Comment by raiankitsr** [comment]
Yes, I can do that

But I am not able to fetch code into my local repository,  ( I.e = Code is
not shown properly ) . That why there are delay in updating those things .


Please provide me direct code .

Thanks & Regards
Ankit Rai

**Comment by MonalikaPatnaik** [comment]
Hey, u can head over src/components/navbar/index.js around line 81

**Comment by MonalikaPatnaik** [comment]
for fetching the repo you can clone it and run npm start to see the site in your localhost

**Comment by raiankitsr** [comment]
I am talking about code!!

**Comment by MonalikaPatnaik** [comment]
> Hey, u can head over src/components/navbar/index.js around line 81

Read this..told you the path for the desired code only..you can look contributing.md file in the repo for the steps to contribute!

**Comment by raiankitsr** [comment]
Thanks, I'll check it out.
