### ISSUE TITLE
BUG: Adding link to GITHUB ICON

### ISSUE THREAD

**Issue by marshadkhn** [MonalikaPatnaik/UMatter#813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @MonalikaPatnaik @TechSpiritSS @AkankshaAI 
**I gone through the website well and checked all the existing issues. I just want to fix a simple bug**
**Want to add a github link in icon as the github is available for the project**

**My branch name will be - marshadkhn**

### Add ScreenShots

![Screenshot 2023-06-20 121811](https://github.com/MonalikaPatnaik/UMatter/assets/80325579/7c6fdafd-22a3-4660-9812-f5b4b27bb30a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Bhanuteja01** [comment]
Assign me this issue
I'm gssoc contributor

**Comment by marshadkhn** [comment]
@Bhanuteja01 please raise your own issue!

**Comment by marshadkhn** [comment]
@TechSpiritSS

**Comment by MonalikaPatnaik** [comment]
heyy similar issue is already been assigned!

**Comment by marshadkhn** [comment]
Ok
