### ISSUE TITLE
Feat: Gallery Slider in home page

### ISSUE THREAD

**Issue by Shr-reny** [MonalikaPatnaik/UMatter#815]
### Describe the feature

Since you've mentioned about workshops, creating a gallery slider in home page can make the home page attractive. I can add a slider made using html, css and js only. As of now we can add dummy images from online websites. It swiftly switches images. A preview of the same is attached below.

### Add ScreenShots

![Screenshot (76)](https://github.com/MonalikaPatnaik/UMatter/assets/125943681/3940021f-f959-4447-9d39-dee1e5d4a9e5)
![Screenshot (77)](https://github.com/MonalikaPatnaik/UMatter/assets/125943681/4233ecb2-c096-4182-9408-ed1815f78644)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
Hey..where would u add this and what's the use of it?

**Comment by Shr-reny** [comment]
We can add it just below "our services" section and since workshops are mentioned in services, a few snapshots from workshops can be displayed over.
