### ISSUE TITLE
Enhancing the "Get Started" button

### ISSUE THREAD

**Issue by abhayy143** [MonalikaPatnaik/UMatter#82]
## Issue 
As you can see the **Get Started** button can be enhanced by adding shadow on hover or other CSS elements. 

https://github.com/MonalikaPatnaik/UMatter/assets/53009878/dfcd9467-1c9d-4de8-b0c5-21700b3b6e40

**Comment by abhayy143** [comment]
@MonalikaPatnaik Sorry Actually I forgot to mention that I am a GSSoC'23 contributor.
Can you please add the GSSoC tag to the issue ?

**Comment by MonalikaPatnaik** [comment]
Yeah..you can work on this!
Thanks!
