### ISSUE TITLE
Feat: improving the ui of the navbar of the sign in page and the sign up page 

### ISSUE THREAD

**Issue by vishnubansal001** [MonalikaPatnaik/UMatter#821]
### Describe the feature

the navbar of the sign in and the sign up page is looking very odd one out in the dark theme 

### Add ScreenShots

![Screenshot (123)](https://github.com/MonalikaPatnaik/UMatter/assets/101445306/bb8701aa-9dfd-4142-aa4d-9d03c1c69d48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by TechSpiritSS** [comment]
I guess someone is already working on this

**Comment by vishnubansal001** [comment]
please can you check and if someone is not working on it please assign it to me
