### ISSUE TITLE
BUG: No testimonial heading and the testimonial cards do not fit properly

### ISSUE THREAD

**Issue by smty2018** [MonalikaPatnaik/UMatter#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

No testimonial heading and the testimonial cards do not fit properly. Want to add the testimonial heading with animation and fix the cards not fitting the black background issue,

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/74114936/aaef4b34-d114-4a51-8541-60aa7183a2c4)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by smty2018** [comment]
@TechSpiritSS @MonalikaPatnaik please assign me this issue

**Comment by MonalikaPatnaik** [comment]
Hey i think similar issue is already been assigned!
