### ISSUE TITLE
Add animation to cards in Services section

### ISSUE THREAD

**Issue by khushigupta123** [MonalikaPatnaik/UMatter#83]
I want to add an animation to the cards present in 'Our Services' section. It will be reflected on moving to this section.

I am GSSOC'23 contributor, kindly assign this issue to me.

**Comment by MonalikaPatnaik** [comment]
You can work on this!
Thanks!

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by khushigupta123** [comment]
> You can work on this! Thanks!

Sure, thank you for assigning.

**Comment by PayalPadmalyaPrusty** [comment]
@MonalikaPatnaik I want to contribute.Please assign me

**Comment by MonalikaPatnaik** [comment]
> I want to add an animation to the cards present in 'Our Services' section. It will be reflected on moving to this section.
> 
> I am GSSOC'23 contributor, kindly assign this issue to me.

Hey..Could you pls make a PR soon..it's been two days otherwise will assign this issue to someone else!

**Comment by MonalikaPatnaik** [comment]
> > > I want to add an animation to the cards present in 'Our Services' section. It will be reflected on moving to this section.
> > > I am GSSOC'23 contributor, kindly assign this issue to me.
> > 
> > 
> > Hey..Could you pls make a PR soon..it's been two days otherwise will assign this issue to someone else!
> 
> Sure ma'am, just give me some time, I will make a PR soon.

Pls do it!
