### ISSUE TITLE
Feat: Add close old issue bot

### ISSUE THREAD

**Issue by k-deepak04** [MonalikaPatnaik/UMatter#835]
### Describe the feature

this will maintain clean repo and will delete the untouched issue greater than 30 days
or you can customize the no. of days as per your requirement

### Add ScreenShots

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Bhanuteja01** [comment]
Assign me this issue
I'm gssoc contributor
