### ISSUE TITLE
Feat: Adding a book section in blog page

### ISSUE THREAD

**Issue by ajit1201** [MonalikaPatnaik/UMatter#839]
### Describe the feature

There are various excellent books on changing habits, such as atomic habit, and power of habit. I have read these books and I get inspired by them. 
I wanted to add a book section where we will have a list of books that an individual can refer to make good habits.

I want to work on this feature please assign me 

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/91869854/f3e33431-1342-473d-a104-a94bb1eccf37)
This is not the actual, I will do more research on books and I will make it more better

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
