### ISSUE TITLE
Adding a Scroll to Top Button

### ISSUE THREAD

**Issue by abhayy143** [MonalikaPatnaik/UMatter#84]
As a GSSoc'23 contributor I want to raise this issue.

## Issue
"Scroll to top" buttons enhance the overall navigation experience of a website. Instead of scrolling back through a lengthy page, users can reach the top instantly, especially on mobile devices where scrolling can be more challenging due to smaller screens. Adding a scroll to top button will enhance the UI/UX of the website.

Mentioned are the examples of some of the **Scroll to Top** button:

![11](https://github.com/MonalikaPatnaik/UMatter/assets/53009878/2a678348-272a-4392-bb64-6777480b792b)

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by MonalikaPatnaik** [comment]
Yes..Go ahead..
Thanks!

**Comment by vink08** [comment]
please assign to me.

**Comment by vink08** [comment]
Please assign to me..

**Comment by abhayy143** [comment]
Yes I am. Actually I got a bit busy with some assignments. I hope you understand. I'll be committing a PR by tomorrow solving the issue for sure.

**Comment by Deepanshu0703** [comment]
Is this issue is still available

**Comment by abhayy143** [comment]
Hey @Deepanshu0703 I'm working on it and will commit a PR by tonight. Thank you

**Comment by MonalikaPatnaik** [comment]
Hii @abhayy143 pls submit your PR today itself...otherwise will assign to someone else!

**Comment by Deepanshu0703** [comment]
I wanna contribute so plz assign it to me in above mentioned case .My code is ready

**Comment by abhayy143** [comment]
> Hii @abhayy143 pls submit your PR today itself...otherwise will assign to someone else!
> 
> 

Hey @MonalikaPatnaik I was a bit busy with college assignments and semester exams, I didn't get much time to work on the issue. But hopefully I'll push the PR by tonight. Thank you

**Comment by Deepanshu0703** [comment]
Hey @MonalikaPatnaik can you now assign it to me

**Comment by MonalikaPatnaik** [comment]
Hey @Deepanshu0703 you can now work on this!
