### ISSUE TITLE
BUG: UMatter link in the Navbar is broken

### ISSUE THREAD

**Issue by ritik48** [MonalikaPatnaik/UMatter#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

UMatter link in the navbar do not wotk. It takes to a blank page instead og redirecting to the home page.

current link: https://monalikapatnaik.github.io/
correct link: https://monalikapatnaik.github.io/UMatter

### Add ScreenShots

Clicking on UMatter on the navbar results in the following:

![umatter issue](https://github.com/MonalikaPatnaik/UMatter/assets/84488726/0107cd6e-273a-44ff-9e38-b7cb67d4f8d0)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by AnushkaKohli** [comment]
Hey, I would like to work on this issue.

Iwould navigate the user to the home page once the user clicks on the UMatter logo.
