### ISSUE TITLE
Improvements in Forgot Password and OTP verification pages.

### ISSUE THREAD

**Issue by yogeyyy** [MonalikaPatnaik/UMatter#841]
### Describe the feature

Hey, 
Now that my last PR is merged in the main, there are some issues with the forgot password and OTP verification page from the design point of view. Since the UI of the SignIn / SignUp page is changed, these 2 pages feel out of place.

Forgot Password Page issues: 
1. The background is white even in the dark mode. 
2. When you hover over the continue button, it changes to a muted orange colour (not in the colour palette or branding). 
3. There is no heading for this section and a lot of blank space above and below the box. 
4. The footer does not appear on this page.
5. Does not align with the current UI of forms on the page. 

![image](https://github.com/MonalikaPatnaik/UMatter/assets/122149755/5f46d067-28d8-4af8-8a79-1a65469f1052)

OTP Verification Page issues: 
1. Verify OTP button is not centred.
2. When you hover over the Verify OTP button, it changes to a muted orange colour (not in the colour palette or branding). 
3. There is a random UMatter heading that takes you to an Error 404 page. 
4. The footer does not appear on this page.
5. Text inside OTP boxes gets filled in white colour, which Is not visible on with white background. 

![image](https://github.com/MonalikaPatnaik/UMatter/assets/122149755/71224cf6-c122-4d22-8b03-3e9decd33957)

### Add ScreenShots

Improvements: 
Improvements -

1. Simplifying the UI of the page as shown below.
2. Fixing the above-mentioned issues.
3. Overall More formal, designed look in accordance with the branding and colour palette.

![image](https://github.com/MonalikaPatnaik/UMatter/assets/122149755/afd375f4-22fd-4a82-abd1-49d8c9fa5ebc)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/122149755/334679e8-81d5-4a64-8e21-e7aa82a4aacf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
Hay..are u done with your changes?

**Comment by yogeyyy** [comment]
Eyup almost done ... sending a PR tomorrow morning
