### ISSUE TITLE
Feat:Email verification 

### ISSUE THREAD

**Issue by Soulpurr** [MonalikaPatnaik/UMatter#844]
### Describe the feature

While signing up we should implement a way to verify email i.e send code to email them verify it .
Pls assign this to me under gssoc23.

### Add ScreenShots

Ss

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Soulpurr** [comment]
@TechSpiritSS pls add level and gssoc23 lables too

**Comment by TechSpiritSS** [comment]
Level and GSSoC tag will be added at PR

**Comment by Soulpurr** [comment]
> Level and GSSoC tag will be added at PR

Which level this issue comes under???
