### ISSUE TITLE
Cursor not changing on hover for the "Get Started" button

### ISSUE THREAD

**Issue by Prajwal0225** [MonalikaPatnaik/UMatter#85]
### I encounter that cursor not changing on hover for the "Get Started" button

**Description**:
I have encountered an issue where the cursor does not change when hovering over the "Get Started" button on the webpage. Currently, the cursor remains in its default state, indicating that the button is not interactive.

**Observation**:
Upon investigating the issue, I noticed that the cursor does not change when hovering over the "Get Started" button. This behavior is inconsistent with user expectations and may lead to confusion or frustration.

**Proposed Solution**:
To address this issue, I suggest adding the CSS property cursor: "pointer" to the style definition of the "Get Started" button. This will change the cursor to a pointer icon, indicating that the button is clickable and interactive.

**Visual Representation**:
Here is a comparison of the button's appearance before and after implementing the suggested CSS property:

Before ⤵️ 

![change 1](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/da4c0e06-5ff2-499e-a782-9f585d346d0d)

 
**After** ⤵️ 

![change1 after](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/5f8d1345-20e4-4e76-854b-15b611bedb83)

**Comment by Kwamecody** [comment]
Hello,

Please I will like to be assigned this issue.

I am a contributor for GSSoC 2023.

Thank you in advance.

**Comment by MonalikaPatnaik** [comment]
Hey @Prajwal0225, I liked your explanation but it's already being resolved..
Thanks..
