### ISSUE TITLE
Feat: Dockerize the Application

### ISSUE THREAD

**Issue by Codeansh** [MonalikaPatnaik/UMatter#854]
### Describe the feature

Docker containers encapsulate everything an application needs to run (and only those things), they allow applications to be shuttled easily between environments. So I think it would be helpful to dockerize this application.

### Add ScreenShots

![Screenshot 2023-06-22 172742](https://github.com/MonalikaPatnaik/UMatter/assets/73956838/7a06d880-af1d-4e51-bc3b-a9b5005753ec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
Don't you think Docker introduces an additional layer of complexity to development and deployment process..we need to manage dockerfiles, container orchestration, networking etc etc...also not everyone is familiar with Docker or containerization, so there might be a learning curve for everyone involved.

**Comment by TechSpiritSS** [comment]
Majority of contributors might be using Windows Home Edition which is default in most of the laptops and running Docker on Windows Home is a tricky task.

**Comment by Codeansh** [comment]
> Don't you think Docker introduces an additional layer of complexity to development and deployment process..we need to manage dockerfiles, container orchestration, networking etc etc...also not everyone is familiar with Docker or containerization, so there might be a learning curve for everyone involved.

Docker might sound tricky, but it's actually pretty cool! It helps developers work together smoothly by making sure everyone uses the same setup for their projects. It also makes it easy to put our apps on different computers without any trouble. Docker is very useful for saving computer resources, making things faster and cheaper. Lots of people use Docker, so there are plenty of friendly helpers and tools to make our lives easier.
Using Docker may require some initial learning, but the benefits it brings make it worth the effort. Docker provides resources and community support to help us get started. Once we become familiar with Docker, it is very easy to use.

**Comment by Codeansh** [comment]
> Majority of contributors might be using Windows Home Edition which is default in most of the laptops and running Docker on Windows Home is a tricky task.

You raise a valid concern. While Docker on Windows Home Edition can be a bit challenging, there are alternative solutions available. One option is to use Docker Toolbox, which is specifically designed for Windows Home users. It provides a simplified Docker environment and allows you to run Docker containers effectively. Additionally, there are community forums and resources available that offer guidance and workarounds for running Docker on Windows Home Edition. By leveraging these resources and alternative solutions, you can still benefit from Docker's advantages, even on Windows Home Edition.

**Comment by TechSpiritSS** [comment]
I know about this using WSL, but WSL tends to be heavy on resources for budget laptops.

**Comment by Codeansh** [comment]
Just wanted to check if we can close the issue now based on our discussion. Appreciate your input and collaboration. Let me know your thoughts. Thanks!

**Comment by TechSpiritSS** [comment]
Your idea is good but the project is too simple for a docker. This issue will hold great value in complex applications where dependency issues are common.

**Comment by Codeansh** [comment]
Understood. Docker is typically more beneficial for complex applications that involve managing dependencies and potential issues. In this project, it may not provide significant advantages. 
I really appreciate your input and the value it brings to my learning. It's helpful in shaping my understanding. Thank you so much for taking the time to share your insights.

**Comment by Codeansh** [comment]
Closing the issue.
