### ISSUE TITLE
Feat: Add Captcha Verification in SignUp page

### ISSUE THREAD

**Issue by Manice18** [MonalikaPatnaik/UMatter#859]
### Describe the feature

A captcha must be present in a signup/register form to prevent bots from crawling up.
And a captcha differentiates human from bots.

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/91601706/b34b8622-bd3e-44a9-8397-2f207f8122a0)
will like to add the Captcha verification here

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Manice18** [comment]
@MonalikaPatnaik can you please add the level tag

**Comment by Manice18** [comment]
https://github.com/MonalikaPatnaik/UMatter/assets/91601706/bbf9ca61-6285-4350-afc9-e5327f1948e6

@MonalikaPatnaik can you please check whether this is or or not?

**Comment by MonalikaPatnaik** [comment]
LGTM..However the buttons are looking clumsy, you can make both the buttons of same size.

**Comment by Manice18** [comment]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91601706/bfe56f0f-c58f-4694-bcc9-79de76d7c5d8)

@MonalikaPatnaik  how about this one ?

**Comment by MonalikaPatnaik** [comment]
Hii, could you increase the form height a bit and try to make both the buttons of same size?

**Comment by Manice18** [comment]
ok 
will get back soon

**Comment by Manice18** [comment]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91601706/e4bc554c-7ddb-4173-8575-9d1185e50b7f)

@MonalikaPatnaik

**Comment by Manice18** [comment]
the sign up button has less text than captcha button
that's the reason this is happening

**Comment by Manice18** [comment]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/91601706/45cb92ba-e50e-4f8d-97f3-29c74dceb445)
@MonalikaPatnaik  ?

**Comment by MonalikaPatnaik** [comment]
Yess, LGTm👍

**Comment by Manice18** [comment]
@MonalikaPatnaik made the PR
