### ISSUE TITLE
Feat: Add Consult With Doctor webpage 

### ISSUE THREAD

**Issue by Prajwal0225** [MonalikaPatnaik/UMatter#865]
### Describe the feature

The current website lacks a "Consult With Doctor" webpage in the services section. As a result, the "Consult With Doctor" section on the website is inactive and does not link to any webpage. To enhance the website's functionality and provide users with the ability to consult with doctors online, we need to create a dedicated webpage for this purpose.

I wanted to create it.

### Add ScreenShots

**Here are some rough visual references to give an idea of the webpage that I am going to make:**

- **Home page** 
![homepage ](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/3e49a8cd-e7f7-412a-aaac-4e51c635b107)

- **Appointment form: make an appointment**
The button on the home page is linked to this form 
![make an appointment](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/d23cec73-7b92-462b-bfb3-8841156fa1b6)

- **Doctor/therapist profiles**
![Doctor_Therapist Profiles](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/1e4e556e-d6d1-4343-9cc7-46911db8d52d)

- **Consultation process**
![Consultation Process](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/859aa00e-e235-4b5d-b7a7-342038b8bcf8)

**Can you please assign this issue to me? So, that I can start working on it.**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Prajwal0225** [comment]
https://github.com/MonalikaPatnaik/UMatter/assets/103810119/62536b97-a179-4eaa-942d-8ada7ac2a7bc

Only the navbar and footer are remaining I will add them before making pr.

Is there any chance you want if there is then I can make appropriate changes before making a pr...

**Comment by MonalikaPatnaik** [comment]
LGTM <3
However you can add a bg behind the consult doctor homepage.

**Comment by Prajwal0225** [comment]
Link Doctor or hospital photo?

**Comment by MonalikaPatnaik** [comment]
Yes..doctors bg will look good..add the dark linear gradient to it so that the text above it is visible...also you can add navbar and footer to this page.

**Comment by Prajwal0225** [comment]
Yaaa 👍

**Comment by Prajwal0225** [comment]
I added the doctor bg add I try dark linear gradient on text but white looks good so I keep it as it is.
