### ISSUE TITLE
BUG: text visibility in blog section

### ISSUE THREAD

**Issue by devWonderkind** [MonalikaPatnaik/UMatter#869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@MonalikaPatnaik card text is not visible properly need to be improve UI. please assign this issue to me.

### Add ScreenShots

![visibility](https://github.com/MonalikaPatnaik/UMatter/assets/110322061/54c5b682-f7fa-4894-95c8-13df1069b15c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by ParthMadhvani2** [comment]
hey, can you please this task to me under GSSoC'23 as I am a contributor please accept my pull request.
