### ISSUE TITLE
BUG: Hover effect in testimonials

### ISSUE THREAD

**Issue by Ks103** [MonalikaPatnaik/UMatter#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In testimonials there is not hover effect while other sections looks good while hovering , testimonials section too require hover effect . I request you to please assign me this issue so that I can contribute to this project.

### Add ScreenShots

![Screenshot (195)](https://github.com/MonalikaPatnaik/UMatter/assets/86292101/9a3fd314-2bb7-49f1-9c85-b5b59efe1cd6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by aditi-chaurasia** [comment]
Please assign this issue to me . I wnat to work on this.

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
