### ISSUE TITLE
Can I create a good navbar with better UI design

### ISSUE THREAD

**Issue by AvinashChourasia** [MonalikaPatnaik/UMatter#874]
### Describe the feature

Making the navbar flow good with the use of great colour combination.

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
Could you share the ss to which you are changing into?

**Comment by AvinashChourasia** [comment]
![Screenshot (89)](https://github.com/MonalikaPatnaik/UMatter/assets/97829396/a381f65f-faa2-4a8c-a381-9c938ee2816f)

Not able to differentiate between navbar height and main page. I think you understand.
Want to enhance the user interface.
Also want to create a good navbar with better UI.
