### ISSUE TITLE
Feat: Add the blog about Mental Health 

### ISSUE THREAD

**Issue by Parmesh119** [MonalikaPatnaik/UMatter#875]
### Describe the feature

You have to add a blog related to mental health and what are the things that destroy mental health and how to solve them.

### Add ScreenShots

![problem-mental health](https://asset20.ckassets.com/blog/wp-content/uploads/sites/5/2019/02/Mental-Health.jpg)

![Solution-mental health](https://pbs.twimg.com/media/DNPzo_cV4AAvtIe?format=jpg&name=large)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by priyanka7976** [comment]
I am GSSoc contrbutor. I would like to work on the issue pls assign it to me.
