### ISSUE TITLE
Clickable Links Issue!

### ISSUE THREAD

**Issue by SaurabhDwivedi231003** [MonalikaPatnaik/UMatter#88]
While clicking on title UMatter dosen't navigate to about section.
If we direct user to about section just by clickig on title , it will enhance user experience and remove extra about section to make our app user friendly and more simple.
Media Queries are required to enhace responsive to make our app run smoothly on mobile app and other devices.

Hope i get to work in this project to enhance more such feature !
Thankyou :)

**Comment by avnigoyal25** [comment]
i can work on this issue please assign this to me

**Comment by avnigoyal25** [comment]
i am a GSSOC contributer

**Comment by MonalikaPatnaik** [comment]
@SaurabhDwivedi231003: you are assigned!
Thanks for contributing!

**Comment by SaurabhDwivedi231003** [comment]
Thank you so much!

**Comment by Dimple-01** [comment]
This work is not done yet.
I want to work on this issue.
I will fix this within few hours.
Please assign this work to me.
