### ISSUE TITLE
BUG:Show password button

### ISSUE THREAD

**Issue by shraddha761** [MonalikaPatnaik/UMatter#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

this button work together open one will open both 

### Add ScreenShots

![Screenshot 2023-06-24 170526](https://github.com/MonalikaPatnaik/UMatter/assets/106100728/31eef238-b1dc-492d-a601-6283f7b4f9ee)

### What browser are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Safari, Arc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by adarsh-aur** [comment]
I would like to contribute to this, I can use basic js.
Kindly assign it to me.
Thanks!

**Comment by shraddha761** [comment]
Hye @MonalikaPatnaik There is bug in show password button. That is both password field and confirm password field button both are working together if we want just to see password field pass then button of confirm password will automatically open.

**Comment by MonalikaPatnaik** [comment]
Hey, signin, signup forms have been totally redesigned..checkout the updated ones!

**Comment by adarsh-aur** [comment]
> Hey, signin, signup forms have been totally redesigned..checkout the updated ones!

@MonalikaPatnaik Could you tell me where to check the updated ones?

**Comment by MonalikaPatnaik** [comment]
You can check out the updated site in the deployed link mentioned in readme and about of the project.

**Comment by shraddha761** [comment]
@MonalikaPatnaik I'll check the deployed version but didn't find

**Comment by MonalikaPatnaik** [comment]
[umatter-eight.vercel.app/](https://umatter-eight.vercel.app/)

**Comment by shraddha761** [comment]
> [umatter-eight.vercel.app/](https://umatter-eight.vercel.app/)

Please Checkout signUp page Still same Bug

**Comment by MonalikaPatnaik** [comment]
> Please Checkout signUp page Still same Bug

You attached the old ss of sign-up page so I thought you haven't checked the updated one, yes it is a bug..you can work on this!
