### ISSUE TITLE
BUG:improvment in footer section

### ISSUE THREAD

**Issue by govindgupta1912** [MonalikaPatnaik/UMatter#889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In footer section instagram,facbook,twitter,youtube button is not working
either attached a link make this button active or reomve the option

### Add ScreenShots

![Screenshot (84)](https://github.com/MonalikaPatnaik/UMatter/assets/123895890/734ea58c-f1ec-4c12-abe2-3e4f30d66058)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Shikhar9425** [comment]
please assign this issue to me

**Comment by Shikhar9425** [comment]
issue #889 solved ,  remove "#" in every link with the respective URL .
