### ISSUE TITLE
[bug] Footer Social Media icons not working

### ISSUE THREAD

**Issue by parthpathakpp1** [MonalikaPatnaik/UMatter#89]
When we click on the social media icons in footer it get redirected to 404 page . I will add suitable links to it . 
![ummater](https://github.com/MonalikaPatnaik/UMatter/assets/85991449/e98a95f4-4982-4495-b53c-08a23e8ca028)

**Comment by parthpathakpp1** [comment]
assign me this issue . I will fix this issue very quickly.

**Comment by MonalikaPatnaik** [comment]
Hey..actually the links are not there which we can provide you to fix this..

**Comment by parthpathakpp1** [comment]
> ually the links are not there which we

ok
