### ISSUE TITLE
BUG: dark theme and styling

### ISSUE THREAD

**Issue by BhartiNagpure** [MonalikaPatnaik/UMatter#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have seen that in forget password page there is need of some styling and also dark theme not applied on that page.

### Add ScreenShots

![2023-06-26 (3)](https://github.com/MonalikaPatnaik/UMatter/assets/104631882/c9c6b362-7238-4387-ad50-9b6b704fd0e5)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
Hey, similar issue is already been assigned!
