### ISSUE TITLE
BUG: the testimonial section name 

### ISSUE THREAD

**Issue by k-deepak04** [MonalikaPatnaik/UMatter#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the testimonial section heading animation is way to fast it's not looking good

### Add ScreenShots

https://github.com/MonalikaPatnaik/UMatter/assets/96341431/2758fa68-76ce-4734-9041-0a8c344e7f67

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by k-deepak04** [comment]
@MonalikaPatnaik i want to resolve this issue also there are 2-3 more issues in the testimonial section 
shall i list them down in this one only or open a issue for every bug?
let me know :)

**Comment by MonalikaPatnaik** [comment]
> @MonalikaPatnaik i want to resolve this issue also there are 2-3 more issues in the testimonial section shall i list them down in this one only or open a issue for every bug? let me know :)

Hey, you could fix all the bugs in testimonial under single issue only bcoz this issue is too minor for gssoc...Could you list other bugs in testimonial also?

**Comment by k-deepak04** [comment]
okay

in small screen size so much gap is before and after testimonial , it looks like a blank screen

![image](https://github.com/MonalikaPatnaik/UMatter/assets/96341431/9c55b117-7852-411f-8a44-bb3a270f7438)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/96341431/642dbf4e-838c-4817-a536-595948ecd913)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/96341431/0a0e54f6-c918-4bb6-9f5a-c8ee52f6d0e0)

see the web it's nicely align in phone it's not aligned properly

![image](https://github.com/MonalikaPatnaik/UMatter/assets/96341431/99e559fc-eea3-42bf-bcfc-e32313d17b39)


also manual arrows are not there is small screen for changing the testimonial, only automatic change is there

![image](https://github.com/MonalikaPatnaik/UMatter/assets/96341431/313df67b-f3a7-400b-852a-7dc143b582f4)

**Comment by k-deepak04** [comment]
@MonalikaPatnaik shall i fix all this things?

**Comment by k-deepak04** [comment]
@MonalikaPatnaik got few more issue 
i'm listing them and will be solving all with this PR only.

**Comment by k-deepak04** [comment]
Issue 
1) umatter placed in retry section i.e visible in dark mode only and not light mode
2) umatter hover color is different from all the other thing i guess we should keep a uniformity in that also 
3) dark mode is covering the retry box a little

**Comment by k-deepak04** [comment]
look this video for reference


https://github.com/MonalikaPatnaik/UMatter/assets/96341431/2c1510d7-2f0f-49ab-9d54-c3f947aba116

**Comment by k-deepak04** [comment]
@MonalikaPatnaik i'm starting working on this
