### ISSUE TITLE
BUG: social icons link not working 

### ISSUE THREAD

**Issue by k-deepak04** [MonalikaPatnaik/UMatter#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the social icon in the footer does not redirect to the social accounts
if you have social accounts please give me or atleast i can add ###github link there

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/96341431/1c500429-e1bc-47e3-8c48-3f353dd7fc25)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by TechSpiritSS** [comment]
There are no social links as of now

**Comment by k-deepak04** [comment]
@TechSpiritSS Atleast i can add github 
Shall i do this or close the issue?

**Comment by MonalikaPatnaik** [comment]
Github link is already been added in the footer..checkout the deployed site.
[umatter-eight.vercel.app/](https://umatter-eight.vercel.app/)
