### ISSUE TITLE
Needs a lot of styling ,for example in links  and also concerned about padding and working of buttons

### ISSUE THREAD

**Issue by piyushkhurana2019** [MonalikaPatnaik/UMatter#9]
styling in links is an issue as well as padding problem in "lets come together" section of the website

<img width="1440" alt="Screenshot 2023-05-20 at 1 56 09 AM" src="https://github.com/MonalikaPatnaik/UMatter/assets/96003210/eba5d51c-f6d1-4fac-94e8-c28967f60784">

also there is lack of responsiveness in mobile view

<img width="1440" alt="Screenshot 2023-05-20 at 1 48 33 AM" src="https://github.com/MonalikaPatnaik/UMatter/assets/96003210/a12bbc20-0ccd-44e9-9af9-5c28e49bbb99">

sign up button is also not working

**Comment by MonalikaPatnaik** [comment]
Heyy..could you pick one? I mean the part which you actually want to do :-)

**Comment by Shrejal123** [comment]
I will manage the styling part,  could you please assign to me.

**Comment by PoorvaU** [comment]
I can style the Get Started button in About section like add hover effect , changing color of the text and more accordingly .Please assign me this issue under GSSOC .

**Comment by PoorvaU** [comment]
@Mansi168 , mam could you assign this issue to me? Thanks in advance

**Comment by Mansi168** [comment]
All these issues are already being handled....will assign you in future if needed :)

**Comment by Mansi168** [comment]
you can work on padding and working of buttons ! anybody interested???

**Comment by Shrejal123** [comment]
yes i am interested  to improve padding and working of buttons

**Comment by Mansi168** [comment]
okay @Shrejal123 you r assigned..!

**Comment by piyushkhurana2019** [comment]
@Mansi168 i had raised this issue first, kindly assign any part to me, i have potential to do any part

**Comment by Mansi168** [comment]
on which part would you like to work?

**Comment by piyushkhurana2019** [comment]
> on which part would you like to work?

mam, I would like to add styling to the navbar and give it a better look, as at present it is not looking that nice. kindly assign this task to me

**Comment by Shrejal123** [comment]
@Mansi168 mam, I have a problem on node version , it gives an error unsupported file due to version ,I don't know how to resolve it. Please help me mam.
![img](https://github.com/MonalikaPatnaik/UMatter/assets/114261409/6f120e06-6d1c-4697-ac23-9e47a2a54de1)

**Comment by Mansi168** [comment]
@piyushkhurana2019 navbar related tasks are already being assigned :( i will assign you if i need more improvements :)

**Comment by Mansi168** [comment]
@piyushkhurana2019 navbar related tasks are already being assigned :( i will assign you if i need more improvements :)

**Comment by Mansi168** [comment]
@Shrejal123 can you drop ss of error!

**Comment by Shrejal123** [comment]
@Mansi168 mam, I am facing this issue but i can resolve by watching youtube videos and download nvm and also install the version  but right now i am unable to upgrade/degrade  the version .Please help me mam.

**Comment by Mansi168** [comment]
nvm install node
nvm use node

use these commands once..let me know if this worked or not

**Comment by piyushkhurana2019** [comment]
> @piyushkhurana2019 navbar related tasks are already being assigned :( i will assign you if i need more improvements :)

sure mam

**Comment by Shrejal123** [comment]
mam , it is showing
![Screenshot ](https://github.com/MonalikaPatnaik/UMatter/assets/114261409/33346007-5ad1-4d08-8a35-d4b611501a68)

**Comment by piyushkhurana2019** [comment]
@Mansi168, mam i have raised issue #184, kindly go through it once and please assign that to me

**Comment by Shrejal123** [comment]
Ma'am, I have resolved the issue of opening the sign-in page when the 'Get Started' button is clicked. However, I have another doubt regarding the signup button on the navbar. Do I need to fix that too?"

**Comment by Shrejal123** [comment]
@i-am-SnehaChauhan ma'am i am saying that Mansi ma'am assign the issue to improve working of buttons so I have resolved the issue of opening the sign-in page when the 'Get Started' button is clicked . but I have a doubt regarding  
navbar signup button but mansi ma'am clear my doubt and  said that no only working on get started button .
![img7](https://github.com/MonalikaPatnaik/UMatter/assets/114261409/f75431aa-907e-43c0-8039-bf359a523d22)

**Comment by MonalikaPatnaik** [comment]
Hey.. @Shrejal123, I think you are improving the UI of buttons.. I recommend you to make a PR soon..otherwise will  assign it to someone else!

**Comment by Shrejal123** [comment]
@MonalikaPatnaik mam  I have worked on working of buttons and I have created a pr and  mansi mam merge already
