### ISSUE TITLE
Changes in Navbar

### ISSUE THREAD

**Issue by parthpathakpp1** [MonalikaPatnaik/UMatter#90]
Current Navbar does not look good . I can completely update the ui of navbar and make it look good.
![umater2](https://github.com/MonalikaPatnaik/UMatter/assets/85991449/4e4c13da-e9f6-462a-b9dc-6d643dd7397c)

**Comment by Piyusharora2003** [comment]
i did like to work on it .

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Piyusharora2003** [comment]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/74443858/7bea6c97-66f1-44d9-a4cd-1d69b54330fc)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/74443858/eb79d68d-02c3-4df8-8e86-882a8387e866)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/74443858/db9a2d34-a8a8-48b8-8436-6c990097b335)
resolved ! please check and allow the pull request
