### ISSUE TITLE
Signup Page

### ISSUE THREAD

**Issue by parthpathakpp1** [MonalikaPatnaik/UMatter#91]
There is no SignUp page in the website . I will create a entire signup page .

**Comment by parthpathakpp1** [comment]
assign the issue to me  . I will create a sign up page.

**Comment by kasturimandlik** [comment]
Hello, I would like to create to sign up page for this website.
The sign up page will have all the necessary details which should be collected from the user like email address, name, password, mobile number, username, etc.
I would like to work on this issue under GSSOC'23. Please assign me this isse

**Comment by i-am-SnehaChauhan** [comment]
@parthpathakpp1 u are assigned.

**Comment by Kwamecody** [comment]
> There is no SignUp page in the website . I will create a entire signup page .

Hello friend. If you are not done, I will like to be a contributor. Thank you in advance

**Comment by MonalikaPatnaik** [comment]
Heyy...sorry for the confusion..this issue is being resolved by #12
Thanks!

**Comment by parthpathakpp1** [comment]
> Heyy...sorry for the confusion..this issue is being resolved by #12 If that is not done...then i will assign it to you Thanks!

ok

**Comment by Kwamecody** [comment]
Well noted

**Comment by shivam-sharma7** [comment]
close this @parthpathakpp1
