### ISSUE TITLE
HeroSection Changes 

### ISSUE THREAD

**Issue by parthpathakpp1** [MonalikaPatnaik/UMatter#92]
In hero container the black background does not fit the whole hero section . There is some space left which does not look good .
![ummerete3](https://github.com/MonalikaPatnaik/UMatter/assets/85991449/2621f1db-e123-4fef-a896-4ddee329545b)

**Comment by parthpathakpp1** [comment]
assign this issue to me . I will fix it quickly

**Comment by i-am-SnehaChauhan** [comment]
@parthpathakpp1 This issue is already raised before if It will not resolve then we will assign it to u.

**Comment by parthpathakpp1** [comment]
> @parthpathakpp1 This issue is already raised before if It will not resolve then we will assign it to u.
ok

**Comment by MonalikaPatnaik** [comment]
Hey..this has been already done..closing it!
Thanks!
