### ISSUE TITLE
Complete Login and Sign up Backend

### ISSUE THREAD

**Issue by Hemant2335** [MonalikaPatnaik/UMatter#93]
As by using the website I realised particularly there was no backend for the user login and sign up

-> I will include a database for you 
-> and Also will make a sign up page 

therefore , Please assign this issue to me 

Thank you

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by MonalikaPatnaik** [comment]
Hey @Hemant2335..once the frontend of these pages is done..we'll move to its backend...then will assign it to you..
Thanks!

**Comment by Hemant2335** [comment]
> Hey @Hemant2335..once the frontend of these pages is done..we'll move to its backend...then will assign it to you.. Thanks!

Ok Thank you
