### ISSUE TITLE
BUG: Icons not correctly aligned in Mobile Phone Preview

### ISSUE THREAD

**Issue by sabhisharma-ise** [MonalikaPatnaik/UMatter#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The icons in the Create Account section are not aligned properly before the input boxes.

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/100849696/28003a8d-9291-4e57-8ede-f9612895bfd9)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushK79** [comment]
I can resolve this. Please assign this issue to me.
