### ISSUE TITLE
Feat: make the "Bottom to Top" button Static

### ISSUE THREAD

**Issue by sabhisharma-ise** [MonalikaPatnaik/UMatter#935]
### Describe the feature

The Bottom to Top button in the website currently keeps moving up and down (in it's position), which kind of doesn't looks good for a professional website. 

Would like to make it static, so that it doesn't distracts the user from the main website!

### Add ScreenShots

https://github.com/MonalikaPatnaik/UMatter/assets/100849696/1e559212-49bb-4a2e-a6e4-a3646c6d3264

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
