### ISSUE TITLE
Feat: Add hover effect on testimonials.

### ISSUE THREAD

**Issue by akshaysoni10** [MonalikaPatnaik/UMatter#939]
### Describe the feature

I want to add hover effect on testimonials to make it more attractive.

### Add ScreenShots

![Screenshot (115)](https://github.com/MonalikaPatnaik/UMatter/assets/109035961/03eaf0e7-e5d7-4e77-8a13-463fba42fee0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
