### ISSUE TITLE
Add Back To Top Button

### ISSUE THREAD

**Issue by ishita80** [MonalikaPatnaik/UMatter#94]
The user has to scroll back to get to the top. So, I want to add a Back To Top Button to the Home Page for a better user experience.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by ishita80** [comment]
@adityavpawar I already asked the project admin to assign me this issue which I created.

**Comment by MonalikaPatnaik** [comment]
Hey,,it is being resolved by #84 
Thanks!

**Comment by ishita80** [comment]
@MonalikaPatnaik Okay, just assign it to me incase he/she isn't able to do it as I have already done that.
