### ISSUE TITLE
Feat: Improve Responsiveness of Website

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [MonalikaPatnaik/UMatter#940]
### Describe the feature

The page is not responsive for smaller screens

### Add ScreenShots

<img width="636" alt="image" src="https://github.com/MonalikaPatnaik/UMatter/assets/70560812/5d007ae9-cbed-40e0-93cc-b70fa2c5e0b5">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'23 contributor
- [ ] I want to work on this issue

**Comment by PiyushK79** [comment]
I can fix this. Please assign this issue to me under Gssoc 23 tag.
