### ISSUE TITLE
BUG:No proper hover in "Our services" section

### ISSUE THREAD

**Issue by Shreyans2004** [MonalikaPatnaik/UMatter#947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On hovering over the cards of the our service section,they are very less increasing in size.It becomes difficult for user to make this out.I can change some styling so that it looks better and attractive. 

### Add ScreenShots

Before hovering
![image](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/62dc414c-783f-4efd-84fc-2812b7b597e8)

On hovering
![image](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/d8fc3aa2-eda3-4fa6-aa91-c59fa0abcef8)

### What browser are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it
