### ISSUE TITLE
Feat:style of contact us page

### ISSUE THREAD

**Issue by Shreyans2004** [MonalikaPatnaik/UMatter#950]
### Describe the feature

The contact us page is looking different from website's taste.I can make it like feedback page so that thee remains a uniformity in the webiste.Can you assign thi task to me?

### Add ScreenShots

![image](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/b8651653-e09a-49c7-8a9a-3caac72a20c9)

![image](https://github.com/MonalikaPatnaik/UMatter/assets/128773151/9f263a5c-6f3b-48e0-8932-bb8ff0437a4c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Shreyans2004** [comment]
@MonalikaPatnaik Can you assign this task to me?

**Comment by MonalikaPatnaik** [comment]
It's been updated already!
