### ISSUE TITLE
Feat:  Enhancing Website Responsiveness for a Seamless User Experience

### ISSUE THREAD

**Issue by devasyarajguru** [MonalikaPatnaik/UMatter#977]
### Describe the feature

Enhance the accessibility and responsiveness of our website AT CERTAIN POINTS shown in the SCREENSHOTS  I will be implementing a series of improvements.

### Add ScreenShots

<img width="771" alt="U1" src="https://github.com/MonalikaPatnaik/UMatter/assets/84851506/c8473680-5de2-432a-b6b1-e63ed6cb0a79">
<img width="919" alt="U2" src="https://github.com/MonalikaPatnaik/UMatter/assets/84851506/75f4f864-a2b5-4cd8-af05-1077fc5e936a">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by devasyarajguru** [comment]
Hey @TechSpiritSS . Please assign me this issue.

**Comment by devasyarajguru** [comment]
Hey @TechSpiritSS it would be great if you take a look on this issue and assigned me!

**Comment by TechSpiritSS** [comment]
It's Express_js_Server, there might be typo in the README.md.
