### ISSUE TITLE
Feat: Word and letter spacing is required in the About section and other section

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#986]
### Describe the feature

I want to add Word and letter spacing is the About section and other sections of the website.

### Add ScreenShots

![13](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/155f73ad-4db6-42db-8ce6-f83a63d2528a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Neha626177** [comment]
I would like to add letter spacing and work on this issue . Please me this project.
Thank You!
