### ISSUE TITLE
Feat: The hover effect is missing in the read more button  and also want to improve the footer hover effect 

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#987]
### Describe the feature

I want to add a hover effect on the read more button and  want to add a left to right animation underline effect on the footer content

### Add ScreenShots

![14](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/d3e6b5c5-1f62-4a62-a77f-3e2de3ce7db9)
![15](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/28d89041-2520-420a-addc-8763a8c477e7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by omprakashchhetri** [comment]
Can you please assign me this issue!

**Comment by Neha626177** [comment]
I would like to add hover effect in this button. please assign me this assign..
Thank You!
