### ISSUE TITLE
About section have some grammatical errors

### ISSUE THREAD

**Issue by HimanshuNarware** [MonalikaPatnaik/UMatter#99]
About section has some grammatical errors, I want  to resolve those issues kindly assign me this issue
![umatter grmmer](https://github.com/MonalikaPatnaik/UMatter/assets/83147410/155e33b4-abaf-4634-b56e-74ba6332fec8)

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
