### ISSUE TITLE
DOC:enhancement of feedback form

### ISSUE THREAD

**Issue by DIVYANSHURATHAUR** [MonalikaPatnaik/UMatter#993]
### What's wrong with the existing documentation

enhance the ui and fields of feedback form

### Add ScreenShots

mail and username should be separate and colour combination should also proper

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by MonalikaPatnaik** [comment]
Okay change the UI matching the taste of signin, signup and contact form.

**Comment by Nitish-hack** [comment]
there is no action on this issue from a while , please assign this to me
