### ISSUE TITLE
Building a MVC architecture for the backend

### ISSUE THREAD

**Issue by Piyusharora2003** [MonalikaPatnaik/UMatter#999]
#Describe the feature
Here there is need of implementing MVC architecture int the backend code as  it makes the code clean and make it developer friendly , easy for developers to identify the bug

Add ScreenShots
No proper folder structure
![image](https://github.com/MonalikaPatnaik/UMatter/assets/74443858/277199b4-6fd5-4246-b86a-57f9bea572c9)

Record
 I agree to follow this project's Code of Conduct
 I want to work on this issue

**Comment by TechSpiritSS** [comment]
someone is already working on backend; you can check his ID in PR and collab with him to fix the backend.
update me once done and I'll assign the issue to you too.

**Comment by Piyusharora2003** [comment]
Sorry I could not find anyone who is currently working on it , please mention me in the issue if it is active or assign me so that i could start working on it
